MH-13685: Added dublincore, security to publish (merge) and replublish-oaimph
opencast/opencast pull request #1025
Opened 2019-08-08 11:36 UTC by TurRil

Added dublincore and security to publish (merge) and replublish-oaimph, and small ui updates to use mediapackage.start or dcCreated.

This fixes the bug where dcCreated is not filled in correctly and the ACL's are not merged in for events where a caption gets added from an attachment workflow.

2019-09-03 21:22 UTC, gregorydlogan commented
As annoying as it would be, this should be two issues.  That being said, this is filed.  Next time.

Regarding the ACL changes, these seem fine to me.  I don't see anything obvious that prevents a merge.
Regarding the dcCreated field, this is more problematic.  We discussed a bunch of dc and (specifically) datetime related things this morning.  @wsmirnow had things to say about this.  Would this cause issues with, or fix things you're looking at.  cc @karendolan

2019-09-16 16:45 UTC, wsmirnow requested changes

2019-09-16 16:45 UTC, wsmirnow commented on etc/workflows/attach-watson-transcripts.xml
> +        <configuration key="download-source-flavors">dublincore/*,security/*</configuration>
Why are you updating dublincore and security catalogs here? The `attach-watson-transcription` operation should not touch any metadata.

2019-09-16 16:45 UTC, wsmirnow commented on etc/workflows/attach-watson-transcripts.xml
> +        <configuration key="source-flavors">dublincore/*,security/*</configuration>
Same here… Removing this line should leave the metadata in the oai-pmh repository untouched but add/update all `download-source-tags` marked assets.

2019-09-16 16:45 UTC, wsmirnow commented on etc/workflows/publish-uploaded-assets.xml
> +        <configuration key="download-source-flavors">${download-source-flavors},dublincore/*,security/*</configuration>
Updating already published metadata on asset upload isn't intuitive. Here you only want to add new asset to the publication.

2019-09-16 16:45 UTC, wsmirnow commented on etc/workflows/publish-uploaded-assets.xml
> +       <configuration key="source-flavors">${download-source-flavors},dublincore/*,security/*</configuration>
See above…

2019-09-16 16:49 UTC, wsmirnow commented
> As annoying as it would be, this should be two issues. That being said, this is filed. Next time.
> 
> Regarding the ACL changes, these seem fine to me. I don't see anything obvious that prevents a merge.
> Regarding the dcCreated field, this is more problematic. We discussed a bunch of dc and (specifically) datetime related things this morning. @wsmirnow had things to say about this. Would this cause issues with, or fix things you're looking at. cc @karendolan

I've only touched the Admin UI. My PR #1079 does not conflict with this PR.

2019-09-16 17:41 UTC, karendolan commented
I notice that dcTitle is also not guaranteed to exist and has a fallback value, per the JavaScript. I wonder why the assumption that mediapackage "start" will exist if the dcCreated does not. How are @TurRil 's mediapackages getting compiled and published without some core metadata?    
> Regarding the dcCreated field, this is more problematic. We discussed a bunch of dc and (specifically) datetime related things this morning.

2019-11-08 09:54 UTC, wsmirnow commented
@TurRil, I would splitt this PR into two seperate PRs. The second part (theodul model start date fallback) is fine for me. But…

Why do you want to update dc and security catalogs on transcriptions add/update? Does the transcription operation touch any data of the dublincore catalog? The ACLs shouldn't be touched anyway.

2020-03-04 12:56 UTC, KatrinIhler commented
@TurRil Conflicts!

2020-03-04 13:16 UTC, karendolan commented
@TurRil I don't understand why this pull adds the dublincore and ACLS to be publish during an upload asset and attach caption workflow. Are you seeing those files being removed during your attach caption or upload asset workflows? Does your site have a process that modifies those files when captions or other attachments are added to a mediapackage?

Our site uses the upload asset and attach caption workflows every day in our modified Opencast v5/6/7/8x and have had no problems with existing published dublincore or ACLs.

2020-08-08 12:42 UTC, gregorydlogan commented
@TurRil any progress here?

2021-02-24 13:48 UTC, KatrinIhler commented
@TurRil What's the status here? If there can't be any work done on this in the foreseeable future, it might be better to close this PR and reopen at a later date.

2021-03-08 16:16 UTC, KatrinIhler commented
As per our recent discussion in the dev meeting and the proposal that followed, I'm going to close this PR since this has seen no updates within the past 1,5 years. This does not constitute a rejection, feel free to re-open once you have time to address the review findings. :)

2021-03-08 16:16 UTC, closed without merging