MH-6610: Pushing to Maven Central
opencast/opencast pull request #1035
Opened 2019-08-28 19:51 UTC by gregorydlogan

This pull request enables appropriately configured users to push to Maven central.  That's right, no more hacky script pushing to our own Nexus infrastructure!

I've already applied this to 6.6 and 7.2 to push them to Maven central, but have not walked backwards to apply it to the rest.

2019-09-03 12:13 UTC, mtneug requested changes

2019-09-03 12:13 UTC, mtneug commented on docs/guides/developer/docs/infrastructure/maven-repository.md
> +- Let the QA Coordinator know about your user, they will comment on [on our repo creation ticket](https://issues.sonatype.org/browse/OSSRH-36510) or create a new issue to give your user permissions
`on [on`

2019-09-03 16:12 UTC, gregorydlogan commented on docs/guides/developer/docs/infrastructure/maven-repository.md
> +- Let the QA Coordinator know about your user, they will comment on [on our repo creation ticket](https://issues.sonatype.org/browse/OSSRH-36510) or create a new issue to give your user permissions
Fixed!

2019-09-09 09:05 UTC, lkiesow commented
@gregorydlogan, the tests are still failing. Can you fix that?

2019-09-09 15:51 UTC, gregorydlogan commented
@lkiesow didn't get a notice that tests failed, odd.  Should be fixed.

2019-09-16 21:27 UTC, gregorydlogan commented
@lkiesow would be nice if this could be in 7.3 native, otherwise I have to push a patched 7.3 to Nexus...

2019-09-17 18:54 UTC, lkiesow reviewed
Except for the minor version complaint, this looks good. The documentation sounds sensible and is easy to understand although I haven't tried this myself.

One question for me would be if we want uploading the releases to stay a manual process or if we wouldn't want to make this part of the CI. But that's also true for some of the other CI steps and we might want to discuss that at some point.

@gregorydlogan, do you want to quickly update the version? Or should I just merge this?

2019-09-17 18:54 UTC, lkiesow commented on pom.xml
> +        <version>1.6.7</version>
Minor thing but can we use the latest version [1.6.8](https://search.maven.org/artifact/org.sonatype.plugins/nexus-staging-maven-plugin/1.6.8/maven-plugin)?

2019-09-17 19:28 UTC, gregorydlogan commented
@lkiesow bumped to 1.6.8.  Latest version was 1.6.7 at time of writing :)

I'm already partially through updating the buildbot infra to push snapshots.  Pushing releases is a little more complicated, but is a planned next step - as is pushing the builds to github, and building the release packages (and possibly docker images).  But let me get the snapshots going first :)

2019-09-17 20:14 UTC, merged

2019-09-17 20:14 UTC, lkiesow commented
Merged.