NOISSUE: CAS security example is very out of date
opencast/opencast pull request #1056
Opened 2019-09-11 21:15 UTC by gregorydlogan

This patch fixes two issues with the existing CAS security example file:

1) It adds a number of missing paths which were added to the default file, but not to the example
2) It attempts to re-enable CAS, which appears to have been accidentally removed.

2019-09-11 21:28 UTC, gregorydlogan commented
Per discussion at https://groups.google.com/a/opencast.org/d/msg/users/NoZFBjxkzzg/aSa9t6UqBAAJ, this appears to be working for at least one user.

2019-09-16 09:25 UTC, miesgre reviewed
It does not work for me. I get this error:
```
2019-09-16 11:14:03,154 | ERROR | (SpringSecurityConfigurationArtifactInstaller:102) - Unable to refresh spring security configuration file /opencast-miesgre/build/opencast-dist-develop-7-SNAPSHOT/etc/security/mh_default_org.xml: {}
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Filter beans '<casFilter>' and '<org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0>' have the same 'order' value. When using custom filters, please make sure the positions do not conflict with default filters. Alternatively you can disable the default filters by removing the corresponding child elements from <http> and avoiding the use of <http auto-config='true'>.
Offending resource: OSGi resource[file:/opencast-miesgre/build/opencast-dist-develop-7-SNAPSHOT/etc/security/mh_default_org.xml|bnd.id=113|bnd.sym=opencast-kernel]
```

2019-09-16 09:54 UTC, miesgre requested changes
It does not work for me. I get this error:
```
2019-09-16 11:14:03,154 | ERROR | (SpringSecurityConfigurationArtifactInstaller:102) - Unable to refresh spring security configuration file /opencast-miesgre/build/opencast-dist-develop-7-SNAPSHOT/etc/security/mh_default_org.xml: {}
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Filter beans '<casFilter>' and '<org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0>' have the same 'order' value. When using custom filters, please make sure the positions do not conflict with default filters. Alternatively you can disable the default filters by removing the corresponding child elements from <http> and avoiding the use of <http auto-config='true'>.
Offending resource: OSGi resource[file:/opencast-miesgre/build/opencast-dist-develop-7-SNAPSHOT/etc/security/mh_default_org.xml|bnd.id=113|bnd.sym=opencast-kernel]
```

2019-09-16 09:54 UTC, miesgre commented on etc/security/security_sample_cas.xml-example
> +    <sec:form-login authentication-failure-url="/admin-ng/login.html?error" authentication-success-handler-ref="authSuccessHandler" />
Comment this line to make CAS work

2019-09-16 21:24 UTC, gregorydlogan commented
@miesgre this should be working now!

2019-09-17 10:50 UTC, miesgre commented
@gregorydlogan It works, but there are two issues:

1.  I get this warning. I don't know if it's important or not:
```
2019-09-17 12:04:53,826 | WARN  | (SingleSignOutHandler:147) - Front Channel single sign out redirects are disabled when the 'casServerUrlPrefix' value is not set.
```
2.  You need to configure a role provider to get roles, if not you get a bad credentials, and user is not logged in. This happens in the previous versions too (6.x, ...)

2019-09-18 01:00 UTC, gregorydlogan commented
@miesgre no idea, I don't have anything to test against, just attempting to revert the merge by sight.

Regarding the role provider, that's expected isn't it?

2019-09-18 07:06 UTC, miesgre approved these changes
@gregorydlogan I think it can be merged as is.
I can Log in and not noticed any problems. It works in the same way old releases works

2019-09-19 06:48 UTC, merged