close esc function for new event and new series modals
opencast/opencast pull request #1073
Opened 2019-09-24 12:51 UTC by ek926m

This PR makes the modals for new event and new series closable by using the escape key.

2019-09-26 17:29 UTC, gregorydlogan requested changes

2019-09-26 17:29 UTC, gregorydlogan commented on modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventController.js
> +.directive('escKey', function() {
I feel like the directive in this PR and #1067 should be moved into its own file, and then reused, rather than copy and pasted.

2019-09-26 17:29 UTC, gregorydlogan commented on modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/newSeriesController.js
> +  .directive('escKey', function() {
Same as above

2019-10-01 16:37 UTC, KatrinIhler commented
Why only for these modals? Won't this create an inconsistency with the others, or does this already work for the rest?

2019-10-01 17:07 UTC, gregorydlogan commented
@KatrinIhler brings up an even better point wrt moving this to a directive: It's much, much easier to share a directive around than copy and paste everywhere :)

2019-10-01 17:16 UTC, lkiesow commented
> Why only for these modals? Won't this create an inconsistency with the others, or does this already work for the rest?

It does already work for the rest. 

@gregorydlogan, @KatrinIhler: Please note that @ek926m does not work for us any longer and this was a last-minute fix to remove some inconsistencies. So it's either merging or declining this. Sry.

2019-10-01 17:17 UTC, ek926m commented
@lkiesow @KatrinIhler @gregorydlogan I try to do a quick fix now

2019-10-01 17:38 UTC, ek926m commented
@lkiesow @KatrinIhler @gregorydlogan it should be fixed now.

2019-10-01 17:44 UTC, ek926m commented
@gregorydlogan and yes, @lkiesow is right, I don't work for them anymore

2019-10-08 20:09 UTC, merged