MH-13308 Nibity Transcription Service
opencast/opencast pull request #1096
Opened 2019-09-27 08:15 UTC by smarquard

Adds support for the Nibity Transcription Service API (v1), http://nibity.com

Migrated forward from local UCT implementation for Opencast 6.x.

Initial commit, not yet tested.

This PR includes #1093 and #1095

2019-09-27 15:04 UTC, smarquard commented
For anyone who'd like to test this, I can arrange client ID and keys from Nibity.

@JamesUoM @tyfranck Stuart expressed some interest in this. It uses the same db tables as the Google Speech implementation so you should be able to backport it locally if interested.

2019-10-01 10:07 UTC, tyfranck commented
@smarquard I want to test that, great if you can arrange client ID

2019-10-03 09:10 UTC, tyfranck commented
@smarquard  I am currently getting a 502 error when trying to call the API. 

```
2019-10-03 10:02:24,140 | WARN  | (NibityTranscriptionService:531) - Exception when calling the captions endpoint
org.opencastproject.transcription.api.TranscriptionServiceException: Unable to submit job: API returned status 502
	at org.opencastproject.transcription.nibity.NibityTranscriptionService.createRecognitionsJob(NibityTranscriptionService.java:498) [186:opencast-transcription-service-nibity:9.0.0.SNAPSHOT]
	at org.opencastproject.transcription.nibity.NibityTranscriptionService.process(NibityTranscriptionService.java:418) [186:opencast-transcription-service-nibity:9.0.0.SNAPSHOT]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:314) [60:opencast-common:9.0.0.SNAPSHOT]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:273) [60:opencast-common:9.0.0.SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

2019-10-03 09:19 UTC, smarquard commented
Currently the Nibity API only works with http or https callback media URLs (they're looking into why that is the case), so if your dev instance is running on 8080/8081/8082/etc. then please reconfigure for testing to run directly on port 80 (or put an nginx proxy in front of it and adjust the server url in custom.properties).

2019-10-03 12:23 UTC, smarquard commented
Testing:

* Get Nibity API client ID and key 
* Configure an Opencast instance with a publicly-accessible URL, running on port 80 or 443 (so the Nibity API can request the media submission files from /transcripts/nibity/submission/...)
* Upload/ingest a demo video into Opencast using fast testing workflow (publish without editing)
* Run the Start Nibity Transcription on the event to submit to Nibity
* For testing purposes, Nibity may process the job very quickly. To start polling to retrieve results before the default time (as Nibity API doesn't support callbacks when complete), run this mysql query:

````
update oc_transcription_service_job set date_expected=now() where status='InProgress';
````

After a successful retrieval of results (polled every 60s when there are pending jobs), the Attach Nibity Transcription workflow will run. This should attach a zip file and vtt file (extracted from the zip file) to the mediapackage (inspect in asset manager). The vtt file will also be published, so the captions are available for playback (tested so far with Theodul player). The zip file will contain the .docx transcript produced by Nibity as part of the captioning process.

![image](https://user-images.githubusercontent.com/5888197/66126254-5a802900-e5e9-11e9-9b47-d54c32d2f1a6.png)

2019-11-14 11:34 UTC, smarquard commented
Pinging @tyfranck, have you had a chance to run this through yet?

2019-11-14 15:17 UTC, tyfranck commented
@smarquard, the requirement for opencast instance with publicly-accessible URL stopped me in my track :-( . I'm investigating few options to get one so will give it another try hopefully next week.

2019-11-28 14:52 UTC, tyfranck commented
@smarquard , I am getting the following line in the log which is propably an error but shows as info. Any hint? Hope my nibity client id and key are still valid.
`2019-11-28 14:41:21,712 | INFO  | (NibityTranscriptionService:514) - mp b3cc91c3-c946-431b-975a-e78fab678a0a has been submitted to nibity: file id: 5148 status 500 type mp4`

2019-11-28 17:47 UTC, smarquard commented
This line means a successful submission:

````
2019-11-28 15:14:13,353 | INFO | (NibityTranscriptionService:514) - mp f1cd33dc-277f-4a90-8454-ebcdf16d6c15 has been submitted to nibity: file id: 5149 status 500 type mp4
````

The 500 is a Nibity response code, not an http response code. It means "500 - Media transferred successfully"  https://documenter.getpostman.com/view/5815470/RznFpyb6?version=latest

The subsequent lines are saying that no transcript is available yet for the job ids.

2019-11-28 18:22 UTC, gregorydlogan commented
IMO we need to translate that 500 into something sane. I would have assumed status means an error...

2019-11-29 09:53 UTC, tyfranck commented
These are very strange definitions of status codes. A mixture of standard and their own definition: 
`301 - Job ID not found
401 - Transcript ID not found
403 - Unauthorized to access transcript
500 - Media transferred successfully
502 - Unable to access media file or download corrupt
503 - Not authorized to access media file
504 - Authorized to access media file`
The best solution is for Nibity team to stick to the standard, otherwise I agree with @gregorydlogan, we need to convert them in something sensible.

@smarquard , I uploaded a 1 min video yesterday but no transcriptions yet. What is the usual response time?

2019-11-29 18:44 UTC, smarquard commented
On the response codes, these are not http status codes; they are defined by the API and included inside a JSON response. I could make that clearer in the logging so they're not confused with http status codes.

2019-11-29 19:32 UTC, gregorydlogan commented
+1 for a translation layer. Looking at the full list of codes in @tyfranck's post it's doubly important. 500 vs 504 mean *very* different things, but I would assume both are errors.

2019-12-02 09:33 UTC, tyfranck commented
@smarquard, I got the result back (1.5 days turnaround). Looks good.
I've noticed that in addition to the vtt file, nibity also provides a nibity-transcription.zip file which contains a human readable version of the caption (docx file). I think it is worth mentioning that in the documentation.

2019-12-02 23:02 UTC, gregorydlogan requested changes
Minor nits, but looks good to me otherwise.

2019-12-02 23:02 UTC, gregorydlogan commented on docs/guides/admin/docs/workflowoperationhandlers/nibity-attach-transcription-woh.md
> +|target-caption-format|The caption format to be generated. Optional. If not entered, the raw resulting file will be attached to the media package.|EMPTY|vtt|
What is the default if no type is provided?  VTT?  Or is that just your example?

2019-12-02 23:02 UTC, gregorydlogan commented on modules/transcription-service-nibity/src/test/java/org/opencastproject/transcription/nibity/NibityTranscriptionServiceTest.java
> +public class NibityTranscriptionServiceTest {
Is this empty test class deliberate?  Or are there commits missing from the squash?

2019-12-02 23:02 UTC, gregorydlogan commented on modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/NibityAttachTranscriptionOperationHandler.java
> +    String captionFormatOption = StringUtils.trimToNull(operation.getConfiguration(TARGET_CAPTION_FORMAT));
This variable isn't used aside from line 111, and then beyond that everything seems to assume a vtt format.  I'm fine with vtt, but it somewhat defeats the purpose of having a format configuration option when it's basically discarded...

2019-12-02 23:02 UTC, gregorydlogan commented on modules/transcription-service-nibity/src/main/java/org/opencastproject/transcription/nibity/NibityTranscriptionService.java
> +    logger.info("Nibity Transcription Service enabled with client id {}", nibityClientId);
We should be validating that these aren't blank at the very least IMO

2019-12-02 23:02 UTC, gregorydlogan commented on modules/transcription-service-nibity/src/main/java/org/opencastproject/transcription/nibity/NibityTranscriptionService.java
> +    CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
I'd use `makeHttpClient` here, adding a paramter for the `RequestConfig` to the method

2020-03-03 11:35 UTC, gregorydlogan commented
@smarquard is this going to move forward?

2020-03-03 13:31 UTC, smarquard commented
It is indeed. I will make sure it's wrapped up in time for the 9.x branch.

2020-03-04 12:55 UTC, KatrinIhler commented
@smarquard Conflicts!

2020-08-08 12:42 UTC, gregorydlogan commented
@smarquard any progress here?

2020-09-25 16:50 UTC, gregorydlogan commented
Reminder: As a feature this has until 2020-10-05 to be merged for it to make it in 9.0!

2021-02-24 13:49 UTC, KatrinIhler commented
@smarquard What's the status here? If you're planning to get this into OC 10, that deadline is approaching. If not, it might make more sense to close this for now and re-open when it's ready.

2021-03-08 16:26 UTC, KatrinIhler commented
As per our recent discussion in the dev meeting and the proposal that followed, I'm going to close this PR since this has seen no updates within the past 1 year. This does not constitute a rejection, feel free to re-open once you have time to address the review findings. :)

2021-03-08 16:26 UTC, KatrinIhler commented
As per our recent discussion in the dev meeting and the proposal that followed, I'm going to close this PR since this has seen no updates within the past 1 year. This does not constitute a rejection, feel free to re-open once you have time to address the review findings. :)

2021-03-08 16:26 UTC, closed without merging

2021-04-08 14:36 UTC, smarquard commented
We're still running this in production at UCT but haven't had time to resolve the concerns for upstream contribution due to local COVID-19 priorities. We aim to get back to it soon.