MH-12746, Library Update
opencast/opencast pull request #115
Opened 2018-03-02 21:47 UTC by lkiesow

This patch updates several Java dependencies.

2018-03-05 16:32 UTC, staubesv requested changes
Found a cosmetic issue (indentation, see comment).

Except that, seems to work.

2018-03-05 16:32 UTC, staubesv commented on assemblies/karaf-features/src/main/feature/feature.xml
> +	 <bundle>mvn:commons-collections/commons-collections/${commons-collection.version}</bundle>
Indentation

2018-03-05 17:08 UTC, gregorydlogan approved these changes

2018-03-05 17:09 UTC, gregorydlogan commented
Approved pending fix identified by @staubesv

2018-03-05 17:25 UTC, lkiesow commented
Indentation fixed.

2018-03-06 08:26 UTC, staubesv approved these changes
Works as expected.

2018-03-06 09:51 UTC, merged