Warn about using H2
opencast/opencast pull request #1203
Opened 2019-10-31 23:23 UTC by lkiesow

This patch makes Opencast log a warning message when using the internal
H2 database as it is not qualified for use in production:

    2019-11-01 00:18:23,006 | WARN  | (Activator:64) -
    ######################################################
    #                                                    #
    # WARNING: Opencast uses its internal H2 database.   #
    #          Never do this in production.              #
    #                                                    #
    #          For more information about configuring    #
    #          a proper database, see:                   #
    #                                                    #
    #          https://docs.opencast.org                 #
    #                                                    #
    ######################################################

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated testing
* [ ] have a clean commit history
* [ ] have proper commit messages (title and body) for all commits
* [ ] have appropriate tags applied

2019-11-01 01:20 UTC, gregorydlogan requested changes

2019-11-01 01:20 UTC, gregorydlogan commented on modules/db/src/main/java/org/opencastproject/db/Activator.java
> +          + "# WARNING: Opencast uses its internal H2 database.   #\n"
Opencast is using...

2019-11-01 10:10 UTC, lkiesow commented on modules/db/src/main/java/org/opencastproject/db/Activator.java
> +          + "# WARNING: Opencast uses its internal H2 database.   #\n"
yep, makes sense → fixed.

2019-11-02 00:31 UTC, lkiesow commented
@gregorydlogan I guess you wanted to merge this with commit c1a98b109d8ce0357672a2040f68081273ca8e2b?

2019-11-03 20:08 UTC, merged

2019-11-03 20:08 UTC, gregorydlogan commented
Derp, that went into the wrong branch...