MH-12391 Add audio and video stream selectors for tracks to ExecuteMany WOH
opencast/opencast pull request #1234
Opened 2019-11-22 14:06 UTC by smarquard

ExecuteMany WOH can limit element selection to tags and flavor, but in some cases you can have two presenter/source tracks, one video and one audio.

Add an option to restrict element selection to video and/or audio.

This branch also includes PR #1231: adds the ability for the ExecuteMany workflow operation handler to set workflow properties as output rather than creating a new track.

This is similar to the support for workflow properties for ExecuteOnce introduced in MH-12286.

2019-12-17 17:16 UTC, KatrinIhler requested changes
Took me a while to figure out how to test this, but it works. Just one minor thing below.

2019-12-17 17:16 UTC, KatrinIhler commented on docs/guides/admin/docs/workflowoperationhandlers/execute-many-woh.md
>  ### Operation Example
Examples?

2019-12-19 18:15 UTC, smarquard commented
Thanks for the review @KatrinIhler. Any ideas about how to make it easier to test or for new adopters to use the operations? Maybe we should include some template scripts or something as examples.

2019-12-19 18:15 UTC, smarquard commented
Please squash on merge.

2019-12-20 10:02 UTC, KatrinIhler commented
@smarquard Yes, an example script that goes with the workflow operation examples sounds like a good idea!

2019-12-20 10:03 UTC, merged