Implement save buttons for metadata
opencast/opencast pull request #1285
Opened 2019-12-11 14:43 UTC by pmiddend

This PR changes the way metadata is updated in the Admin UI. Instead of the metadata fields being updated *immediately*, there’s a “Save metadata” button at the bottom to bulk-save the metadata. This is consistent with the already-existing bulk update metadata modal (and this modal was also adapted).

Editing a metadata field now doesn’t produce a little checkmark at the right, but a red “is dirty” symbol that I picked at random.

Also included in this PR is the ability to trigger a workflow on all affected events. Meaning: all events in the series in case of a series metadata change, a single event in case of the normal “Edit event” modal or all selected events in case of the “Bulk edit events” modal.

Editing metadata and then trying to exit the modal results in a prompt to confirm unsaved changes.

Also fixed is the “is a workflow running on the event” detection, which behaved weirdly.

This work is sponsored by the University of Vienna as part of the 2019/2020 crowdfunding campaign.

2019-12-12 14:52 UTC, pmiddend commented
Note that @mtneug brought up a change that's still missing from this PR: the ability to auto-trigger workflows from the External API. It's not ready to merge just yet.

2020-03-02 02:27 UTC, gregorydlogan commented
@pmiddend Did the auto-trigger from the external API get finished?  If not, I'm assuming it's not forthcoming at this point?

2020-03-02 17:45 UTC, pmiddend commented
@gregorydlogan Oh damn. Yes, the auto-trigger stuff is finished, I just didn't edit/delete my comment above.

2020-03-04 15:53 UTC, KatrinIhler commented
@pmiddend Conflict!

2020-03-04 17:31 UTC, KatrinIhler requested changes
I've tested this and I noticed some weird behavior. Examples:

- "Dirty" symbol in event-details doesn't show up after save was hit once.
- "Dirty" symbols in series-details don't disappear after save was hit.

- When using extended metadata, the event-details modal appears to double for a moment when hitting save. (???)
- Saving extended metadata doesn't seem to work for series.

- I can hit the save button of the series again even if I just started a workflow, leading to an error. This was not supposed to work, right?

2020-03-04 17:31 UTC, KatrinIhler commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +  private boolean startChangeWorkflow(final Collection<String> mpIds)
In this endpoint, this only ever takes a single id, so why not simply take a String?

2020-03-04 17:31 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
> +          metadataList.setLocked(MetadataList.Locked.WORKFLOW_RUNNING);
I'm wondering whether locking series metadata even works?

2020-03-04 17:31 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
> +        if (workflowsStarted) {
This condition doesn't look right. Shouldn't it be !workflowsStarted?

2020-08-08 13:16 UTC, gregorydlogan commented
@KatrinIhler I see the force push, are your issues resolved?

2020-08-10 06:21 UTC, KatrinIhler commented
@gregorydlogan Thanks for the reminder, this completely fell of my radar with everything that's been going on. Hopefully I'll get this done sometime this month...

2021-03-19 10:41 UTC, KatrinIhler requested changes
Just realized that I forgot to post my review, whoops. Some comments are also works in progress, but I'm gonna leave it as is right now.

The gist of it is: This still doesn't work properly, and since Plapadoo obviously can't fix this, we as a community should think about how we can pour some time into this to fix it, because generally this is something we want.

2021-03-19 10:41 UTC, KatrinIhler commented on etc/org.opencastproject.adminui.endpoint.OsgiEventEndpoint.cfg
> +# org.opencastproject.admin.ui.event-metadata-change-workflow=republish-metadata
TODO: Is this the default? Or is no workflow started by default?

2021-03-19 10:41 UTC, KatrinIhler commented on modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
> +          ng-click="metadataSave(seriesCatalog)">
Why does it only get a parameter here?

2021-03-19 10:41 UTC, KatrinIhler commented on etc/org.opencastproject.adminui.endpoint.OsgiEventEndpoint.cfg
> +# org.opencastproject.admin.ui.event-metadata-change-workflow-config={}
No newline at end of file

2021-03-19 10:41 UTC, KatrinIhler commented on etc/org.opencastproject.adminui.endpoint.SeriesEndpoint.cfg
> +# org.opencastproject.admin.ui.series-metadata-change-workflow-config={}
See OsgiEventEndpoint.cfg

2021-03-19 10:41 UTC, KatrinIhler commented on etc/org.opencastproject.adminui.endpoint.SeriesEndpoint.cfg
> +# org.opencastproject.admin.ui.series-metadata-change-workflow=republish-metadata
See OsgiEventEndpoint.cfg

2021-03-19 10:41 UTC, KatrinIhler commented on etc/org.opencastproject.external.endpoint.EventsEndpoint.cfg
> +# metadata-change-workflow=republish-metadata
See OsgiEventEndpoint.cfg

2021-03-19 10:41 UTC, KatrinIhler commented on etc/org.opencastproject.external.endpoint.SeriesEndpoint.cfg
> +# metadata-change-workflow=republish-metadata
See OsgiEventEndpoint.cfg

2021-03-19 10:41 UTC, KatrinIhler commented on etc/org.opencastproject.external.endpoint.SeriesEndpoint.cfg
> +# metadata-change-workflow-config={}
See OsgiEventEndpoint.cfg

2021-03-19 10:41 UTC, KatrinIhler commented on modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
> +    $translate) {
I'm really not a fan of spacing the dependencies out like this.

2021-03-19 10:41 UTC, KatrinIhler commented on modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
> +      window.unloadConfirmMsg = translation;
Why not in HTML?

2021-03-19 10:41 UTC, KatrinIhler commented on modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
> +      return $scope.metadata.entries.some(
Why check both?

2021-03-19 10:41 UTC, KatrinIhler commented on modules/admin-ui-frontend/test/test/unit/shared/resources/eventMetadataResourceSpec.js
> +            }];
Why this change?

2021-03-19 10:41 UTC, KatrinIhler commented on modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
> +         "WARNING_UNSAVED": "Warning, there are unsaved changes. Really quit?",
Right spot?

2021-03-19 10:41 UTC, KatrinIhler commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
> +  private String metadataChangeWorkflow;
TODO: test external API changes

These changes also require a new external API verson and this should only work for the newer version. 
Also is this documented?

2021-03-19 10:41 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
> +  private boolean startChangeWorkflow(final Collection<String> mpIds)
Why does this take a list?

2021-04-30 08:28 UTC, KatrinIhler commented
Since this still requires some work, I converted this to a draft for now.

2021-11-18 15:23 UTC, lkiesow commented
This is superseded by pull request #3176

2021-11-18 15:23 UTC, closed without merging