update license information for admin-ui
opencast/opencast pull request #137
Opened 2018-03-10 15:36 UTC by ziegenberg

For all *.js and *.scss files, which are clearly not a vendor library, the copyright header was added.

Signed-off-by: Daniel Ziegenberg <daniel@ziegenberg.at>

2018-03-10 15:38 UTC, ziegenberg commented
Special attention should be given to: modules/admin-ui/src/main/webapp/scripts/shared/directives/opencastScrollGlue.js
That's clearly a library and it had no license information on it.

2018-03-10 19:12 UTC, gregorydlogan commented
Altered title since I created a ticket for this.  There are also likely other places where this was missed.

2018-03-12 16:26 UTC, gregorydlogan requested changes

2018-03-12 16:26 UTC, gregorydlogan commented on modules/admin-ui/src/main/webapp/scripts/shared/services/languageService.js
> +'use strict';
Removing this resolves most of the build issues, which stem from line 357:

[INFO]  TypeError: Attempted to assign to readonly property. in /home/greg/opencast/upstream/modules/admin-ui/src/main/webapp/scripts/shared/services/languageService.js (line 357)

2018-03-12 16:26 UTC, gregorydlogan commented on modules/admin-ui/src/main/webapp/scripts/shared/services/playerAdapterFactoryDefault.js
> +'use strict';
This is causing the build to complain about line 123:

TypeError: Attempted to assign to readonly property. in /home/greg/opencast/upstream/modules/admin-ui/src/main/webapp/scripts/shared/services/playerAdapterFactoryDefault.js (line 123)

2018-03-12 18:11 UTC, ziegenberg commented
I've removed the mentioned 'use strict;" statements. It builds now and the tests pass. I would say good enough for now, although I do not like this "solution".

2018-03-12 20:00 UTC, gregorydlogan commented
Good enough for now.  Thanks for the patch!

2018-03-12 20:00 UTC, merged