Adding documentation on how to use the multiserver docker-compose
opencast/opencast pull request #1500
Opened 2020-03-31 21:43 UTC by gregorydlogan

This PR adds docs about the multi-node docker-compose file filed at https://github.com/opencast/opencast-docker/pull/133.  Useful for testing.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated testing
* [ ] have a clean commit history
* [ ] have proper commit messages (title and body) for all commits
* [ ] have appropriate tags applied

2020-04-01 18:06 UTC, mtneug requested changes

2020-04-01 18:06 UTC, mtneug commented on docs/guides/developer/docs/development-environment-docker.md
> +example, to access the presentation node run ```docker-compose exec --user opencast-builder presentation bash```.
This should now be `opencast-$nodetype` and `opencast-presentation`.

2020-04-01 18:08 UTC, mtneug requested changes

2020-04-01 18:08 UTC, mtneug commented on docs/guides/developer/docs/development-environment-docker.md
> +downloading the single-node docker file, download the multi-node version:
I would replace `docker file` with `Docker compose file`

2020-04-01 19:45 UTC, gregorydlogan commented
@mtneug thanks for the review, fixed.

2020-04-02 12:05 UTC, mtneug approved these changes

2020-04-02 12:06 UTC, merged