TagWorkflowOperationHandler now allows wildcards in target flavor
opencast/opencast pull request #1580
Opened 2020-05-12 15:33 UTC by marwyg

This pull request should close #1513.

As described in the feature request, the `TagWorkflowOperationHandler` should now allow target flavors starting with `*/...`. When using this wildcard, all MediaPackages passing the operation should keep their flavor type and just change the subtype.

Example:
Defined target flavor: `*/foobar`

Mediapackge 1 flavor: `presentation/source`
after passing the `TagWorkflowOperationHandler`: `presentation/source` -> `presentation/foobar`

Mediapackge 2 flavor: `somethingelse/source`
after passing the `TagWorkflowOperationHandler`: `somethingelse/source` -> `somethingelse/foobar`

2020-05-15 08:22 UTC, wsmirnow commented
Hi @marwyg, thanks. What is about `dublincore/*` as target flavor? I know, this is an edge case but we are here to improve the tag WOH and make it more intuitive to use.

2020-06-04 20:44 UTC, gregorydlogan commented
@wsmirnow as a *target* flavor?  Or do you mean source?

@marwyg looks good to me, happy to merge.

2020-06-04 20:44 UTC, gregorydlogan approved these changes

2020-06-04 21:42 UTC, wsmirnow commented
I mean the target flavor.

2020-06-04 21:50 UTC, gregorydlogan commented
I can see the usecase, but it is very much an edge case IMO.  I'll let you guys discuss internally regarding time spent (or not) adding that.

2020-06-05 10:44 UTC, wsmirnow commented
Please do not merge this PR, we will improve this patch to handle wildcards in flavor type and sub type.

2020-07-22 21:18 UTC, gregorydlogan commented
Marking this as work-in-progress, please unlabel when ready

2020-09-28 15:30 UTC, gregorydlogan requested changes

2020-09-28 15:30 UTC, gregorydlogan commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/TagWorkflowOperationHandler.java
> +        throw new RuntimeException(errorMsg);
This should be `WorkflowOperationException`

2020-09-28 15:30 UTC, gregorydlogan commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/TagWorkflowOperationHandler.java
> +      wildcardInTargetFlavorType = "*".equals(targetFlavorTypes[0]);
Ideally this should be a class level constant.

2020-09-28 15:30 UTC, gregorydlogan commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/TagWorkflowOperationHandler.java
> +          targetFlavor = targetFlavor.replaceFirst("\\*", element.getFlavor().getType());
This call escapes the *, the following one does not.  They should be the same, right?

2020-09-28 16:45 UTC, lkiesow reviewed
I didn't properly read through all the code but wouldn't it be easier to do something like:


```java
flavor = MediaPackageElementFlavor.parseFlavor(flavorStr == "*" ? "*/*" : flavorStr)
…
if (flavor().getType() == "*") {
  targetFlavor = new MediaPackageElementFlavor(element.getFlavor().getType(), flavor.getSubType());
}
```

Seems easier than all the string handling plus the boolean flags.

2020-09-28 16:45 UTC, lkiesow commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/TagWorkflowOperationHandler.java
> +        throw new RuntimeException(errorMsg);
Don't log an error when you throw an exception anyway. The result will just be that you see the same error twice in the logs. Also, I like short messages ;-)

```suggestion
        final String errorMsg = String.format("The configured target flavor `%s` has a wrong format.", configuredTargetFlavor);
        throw new RuntimeException(errorMsg);
```

2020-09-30 15:12 UTC, marwyg commented
@gregorydlogan 

The code improvement from Lars doesn't work like he suggested I think, but he gave me an idea. The whole boolean part above the loop were redundant, because the whole "checking if the flavor string is correct" already exists in `MediaPackageElementFlavor.parseFlavor()`. So I removed the block and just parse the configuredTargetFlavor with this method. I think the code is much more readable this way now. I am also using the constants, like you suggested. The tests still work as it seems. What do you think?

2020-09-30 16:05 UTC, gregorydlogan commented
LGTM.

2020-09-30 16:05 UTC, merged