Aditive Filter for Api/events endpoint
opencast/opencast pull request #1615
Opened 2020-05-29 15:32 UTC by mliradelc

This PR modifies the filter to be additive. That means that you can ask for different types of events in the same query that are mutually exclusive

For Example:

/api/events/?=filter=series:<series-id-1>&filter=series:<series-id-2>

If this is accepted I can make this enhancement for the others endpoints too

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

2020-06-02 18:45 UTC, lkiesow commented
Just wondering: Do we still care about bumping the API version when modifying the API?

2020-06-02 18:51 UTC, gregorydlogan commented
IMO yes.  Just because what we have is suboptimal does not mean that someone who is integrating with it does not care about API stability.

2020-06-04 12:06 UTC, mliradelc commented
I made the changes, now is the version 1.5.0 for the API.

2020-06-04 14:15 UTC, mliradelc commented
@gregorydlogan I'm having issues with the tests:
```
[ERROR]   ApiMediaTypeTest.testDefaultVersionAndFormat:32 expected:<v1.4.0> but was:<v1.5.0>
[ERROR]   BaseEndpointTest.testGetApiInfo:64 expected:<v1.[4].0> but was:<v1.[5].0>
[ERROR]   BaseEndpointTest.testGetVersion:125 expected:<v1.[4].0> but was:<v1.[5].0>
[ERROR]   BaseEndpointTest.testGetVersionDefault:141 expected:<v1.[4].0> but was:<v1.[5].0>
```
Should I change the tests to v1.5.0 or should be accepted because it is a lower minor version?

2020-06-04 14:19 UTC, gregorydlogan commented
Looking at the test names, I would expect 1.5.0.  They're looking at the *current* version, as well as the default, both of which should be 1.5.0 if we're bumping it.

2020-06-05 08:50 UTC, mliradelc commented
Ok, I understand, I will update the tests. I thought that it was 1.4.0 or greater.

2020-06-08 08:05 UTC, mliradelc commented
Ok, is ready, tests also in check.

2020-06-08 22:19 UTC, gregorydlogan requested changes

2020-06-08 22:19 UTC, gregorydlogan commented on docs/guides/developer/docs/api/base-api.md
> -`200 (OK)`: The api information is returned as a JSON object containing the following fields:
While the original response descriptions were in a passive voice, the switch to active voice doesn't quite work.  This kind of thing is quite common in technical writing.

2020-06-08 22:19 UTC, gregorydlogan commented on docs/guides/developer/docs/api/events-api.md
> +`filter`               | [`string`](types.md#basic)  | A comma-separated list of filters to limit the results with (see [Filtering](usage.md#filtering)). See the below table for the list of available
Version 1.5.0 and newer support comma separated use of the `filter` keyword, creating a logical OR.

2020-06-08 22:19 UTC, gregorydlogan commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +            logger.info("No value for filter {} in filters list: {}", filterTuple[0], filter);
I would move this to debug since your server admin probably doesn't care what random junk their users are dropping into the filter :)

2020-06-08 22:22 UTC, gregorydlogan commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +        if (optSort.isSome()) {
I would move the sorting logic into a helper function rather than duplicating code.

2020-06-10 15:35 UTC, mliradelc commented on docs/guides/developer/docs/api/base-api.md
> -`200 (OK)`: The api information is returned as a JSON object containing the following fields:
Maybe it is because of my background with UK English but I will roll back that. I trust in a native speaker more :smile:

2020-06-10 15:40 UTC, mliradelc commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +        if (optSort.isSome()) {
You are right!. How I didn't see that! 

It was bothering me a lot have to duplicate the code. Creates a new point of failure. I will create the helper function to do that.

2020-07-08 17:07 UTC, gregorydlogan commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +        if (optSort.isSome()) {
Sounds good.  Please ping me when this is done!

2020-10-02 21:03 UTC, merged