MH-12607 (Harvard DCE), Lossless Concat Operation
opencast/opencast pull request #171
Opened 2018-04-04 09:37 UTC by lkiesow

This is an updated version of pull request #14 which @phoebem updated [here](https://github.com/lkiesow/opencast/pull/1). During my review of #14, I noticed a few issues for which I provided some patches which are included here.

To make the review easier, this pull request contains only the lossless concat parts of #14.

2018-04-04 09:40 UTC, lkiesow commented
- @gregorydlogan, I already included fixes based on your review from yesterday.
- @phoebem, can you check if this works for you too.

2018-05-15 08:53 UTC, staubesv commented
As discussed with @lkiesow and @gregorydlogan, I'm taking over this review.

2018-05-15 11:30 UTC, staubesv requested changes
Hi @lkiesow 

Just finished a first round of review. Haven't found any major issues, just some minor comments.

2018-05-15 11:30 UTC, staubesv commented on docs/guides/admin/docs/workflowoperationhandlers/concat-woh.md
> +- A *same codec* mode which assumes the restriction is already met and can hence concatinate the files much faster while
concat**e**nate

2018-05-15 11:30 UTC, staubesv commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
> +      arguments.add(3, "");
Why not "false"?

2018-05-15 12:57 UTC, lkiesow commented
@staubesv, This should fix both issues you raised.
Please wait with the merge though. I like to rebase this to ensure the new Markdown linter does not complain. I'll make that update later today. That should not keep you from testing though ;-)

2018-05-15 14:26 UTC, lkiesow commented
Rebased this to the head of develop to include all of the updated style and formatting requirements and tests. Let's wait for the build to finish though I hopefully got all of them.

2018-05-15 16:43 UTC, lkiesow commented
Finally seems like I've got all errors fixed.
There had also been some Javadoc errors.
Should be ready to be merged now.

2018-05-16 16:35 UTC, staubesv approved these changes

2018-05-16 16:35 UTC, merged