This fixes #1969: The admin interface displays the correct role
opencast/opencast pull request #2112
Opened 2020-11-30 19:29 UTC by mheyen

If a role is not provided by the admin interface's list provider, it will now be displayed in the role selection.

Previously, there was a bug and the UI displayed [object, Object] in the role selection.
Now it shows the name of the role.

This fixes #1969.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2020-12-02 19:18 UTC, lkiesow requested changes
While the issue is a bit harder to reproduce, it also applies to `r/9.x`. It you are ready, it would be great if you could rebase this to `r/9.x`. But there seem to be two issues with this:

First, the interface now seems to be constantly complaining about requiring at least one role with read and write priviledges, even if there is one. Since `ROLE_ADMIN` has always access, we could potentially even drop this restriction:

![opencast-acl-warning](https://user-images.githubusercontent.com/1008395/100920205-10d7ea80-34db-11eb-9c49-73c4b065b650.png)

Second, ingesting an ACL with just one read role seems to somewhat break the user interface still:

![opencast-acl-user-read-only](https://user-images.githubusercontent.com/1008395/100920345-44b31000-34db-11eb-90cf-fb5759146a0a.png)

This was ingested using:

```sh
curl -f -i -u admin:opencast \
  http://localhost:8080/ingest/addMediaPackage/fast \
  -F 'flavor=presentation/source' \
  -F 'BODY=@sintel_trailer-1080p.mp4' \
  -F title=acl-test-user \
  -F creator="J. Doe" \
  -F acl='{"acl": {"ace": [{"allow": true,"role": "ROLE_USER","action": "read"}]}}'
```

2020-12-03 15:36 UTC, lkiesow commented
The second error is also reported as #1798

2021-03-18 14:50 UTC, lkiesow commented
> This pull request has conflicts frowning_face
> Please resolve those so we can review the pull request.
> Thanks.

Conflicts are against `develop` not against `r/9.x`

2021-03-18 15:56 UTC, mheyen commented
The issue with the notification "requiring at least one role with read and write privileges" seems to be fixed as well, at least I cannot replicate it anymore.

2021-03-18 16:39 UTC, lkiesow commented
Seems to work. I did see the „requiring at least one role with read and write privileges“ once again but could not reliably reproduce this. In the end this is definitely a huge improvement → merging

2021-03-18 16:51 UTC, merged

2021-03-20 15:51 UTC, mheyen commented
I also saw the notification once during processing. But after finishing ingesting, it seems to work correctly.