Feature/lti deeplinking #2164
opencast/opencast pull request #2165
Opened 2020-12-17 13:17 UTC by flyapen

This PR adds a new LTI tool, deeplink. Which enables users to easily add opencast content to their LMS.
This implementation was originally done by @ppettit , but when we had the LTI module rewritten to react this was no longer compatible. This fixes this by implementing this feature within the new LTI react module.

We tested this against our own LMS ( brightspace ), but behaviour might vary with other LMS'es.

2021-02-12 15:52 UTC, flyapen commented
We'll have a look at the style errors, we're not getting those locally for some reason ...

2021-05-28 16:08 UTC, wsmirnow commented
@kristofkeppens please ducument this LTI tool in [documentation](https://github.com/opencast/opencast/blob/r/10.x/docs/guides/admin/docs/modules/ltimodule.md)

2021-05-31 10:03 UTC, kristofkeppens commented
@wsmirnow forgot about that one, fixed now.

2021-06-23 19:05 UTC, lkiesow requested changes
This is just a quick review of the code surface, since I don't really have any idea what LTI deep linking is supposed to do. Some parts of this feel somewhat unsafe… but then I'm not sure what to expect…

2021-06-23 19:05 UTC, lkiesow commented on docs/guides/admin/docs/modules/ltimodule.md
> +  ( http://www.imsglobal.org/specs/lticiv1p0 ), use the following parameters
```suggestion
- To show a selection dialog to insert opencast content into the LMS via the
  [LTI deeplink protocol](https://www.imsglobal.org/specs/lticiv1p0), use the following parameters
```

2021-06-23 19:05 UTC, lkiesow commented on docs/checkstyle/checkstyle-suppressions.xml
> +    <suppress checks="LineLength" files="modules/lti/.+\.(java|properties)"/>
We shouldn't add exceptions for new features. They should adhere to the rules.

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/package.json
> +    "http-mock-server": "^0.5.2",
It should suffice to have this as a dev dependency down below

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/package.json
> +    "engage-ui": "../engage-ui",
Why do we depend on the engage ui?
Given its state, that doesn't feel healthy for a new module.

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/package.json
> +    "dangerously-set-html-content": "^1.0.8",
> React uses dangerouslySetInnerHtml prop to render raw html, and works pretty much well for almost all the cases, but what if your html has some scripts tags inside??

That sounds… dangerous and somewhat unsafe. Is this well thought through?

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/OpencastRest.ts
> +                creators: result.mediapackage.creators !== undefined ? result.mediapackage.creators.creator : [],
Why reformat this (same below)?
Readability before was far better.

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/main/java/org/opencastproject/lti/LtiServlet.java
> +public class LtiServlet extends HttpServlet implements ManagedService {
Why implement a `ManagedService`?

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/main/java/org/opencastproject/lti/LtiServlet.java
> +    }
```suggestion
    final boolean test = "true".equals(req.getParameter(TEST));
```

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/main/java/org/opencastproject/lti/LtiServlet.java
> +  public void activate(ComponentContext cc) {
```suggestion
  public void activate() {
```

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/main/java/org/opencastproject/lti/LtiUtils.java
> +      throw new Error(e);
Any particular reason to turn the Exceptions into `Error`?
Will the errors be logged?

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/main/java/org/opencastproject/lti/LtiUtils.java
> +    }
```suggestion
```

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/main/java/org/opencastproject/lti/LtiUtils.java
> +    text.append("      window.console && console.log('Launching http from https in new window!');\n");
```suggestion
    text.append("      window.console && console.debug('Launching http from https in new window!');\n");
```

2021-06-23 19:05 UTC, lkiesow commented on modules/lti/src/main/java/org/opencastproject/lti/LtiUtils.java
> +    text.append("<div id=\"ltiLaunchFormArea_");
This whole block is hard to read and seems like it should be a template. I'm also not sure if and how user input is passed in here and if this is safe. E.g. thinking of passing a backspace character in to manipulate the web page.

2021-06-29 08:58 UTC, kristofkeppens commented on docs/guides/admin/docs/modules/ltimodule.md
> +  ( http://www.imsglobal.org/specs/lticiv1p0 ), use the following parameters
@lkiesow regarding the unsafe part, is this referring to the LTI deeplinking protocol, or the implementation we made?

2021-06-29 09:11 UTC, kristofkeppens commented on modules/lti/package.json
> +    "engage-ui": "../engage-ui",
This was to import the css file and reuse this on this page, but I agree that this seems unnecessary, especially given the limited use of that css file, removed the dependency and will include the necessary css directly in the relevant css file for this page.

2021-06-29 09:12 UTC, kristofkeppens commented on modules/lti/package.json
> +    "http-mock-server": "^0.5.2",
removed engage-ui, moved http-mock-server to dev dependency. Still having a look at the dangerously-set-html-content on what to do with this.

2021-07-13 13:33 UTC, kristofkeppens commented on modules/lti/src/main/java/org/opencastproject/lti/LtiServlet.java
> +public class LtiServlet extends HttpServlet implements ManagedService {
@lkiesow it seems that this is necessary to make the following work : `consumerDetailsService.loadConsumerByConsumerKey(consumerKey);`

2021-08-10 16:37 UTC, gregorydlogan commented
Per discussion in the technical meeting today, we're going to close this for now.  When you're ready please feel free to refile this!

2022-05-18 16:47 UTC, karendolan commented
Hi @kristofkeppens, my site relies on an early version of your LTI Deeplinking OC implementation. We are upgrading and need to adapt it to the current stable OC. I'm heavily leaning on your pull to help guide the way. If my work is general enough, I will make a pull onto your feature/lti-deeplinking branch.

2022-05-19 06:43 UTC, kristofkeppens commented
Hi @karendolan , if it helps I can update it to our latest version ( for opencast 11.x ).

2022-05-19 12:50 UTC, karendolan commented
> Hi @karendolan , if it helps I can update it to our latest version ( for opencast 11.x ).

Yes! That would be great, thank you @kristofkeppens

2022-05-20 07:44 UTC, kristofkeppens commented
@karendolan I've updated the branch ( https://github.com/mm-dict/opencast/tree/feature/lti-deeplinking ), should be working, if anything isn't working have a look at our https://github.com/mm-dict/opencast/tree/r/11.x-ugent branch, but this contains some other things as well.

2022-06-03 14:11 UTC, karendolan commented on modules/lti/package.json
> +    "dangerously-set-html-content": "^1.0.8",
@kristofkeppens I found a potential option for avoiding that lib, however, it negates the easy way to view the content item data before posting it. It's replacing the dangerous...'s `InnerHTML` with the following `LtiLaunchForm`. Inspired by https://github.com/remarkablemark/html-react-parser/issues/94

```
import React, {useEffect} from "react";
import DOMPurify from "dompurify"; // 2mill+ downloads per week, well supported
import parse from "html-react-parser"; // 600k downloads per week, active

// Input properties used for LTI DeepLinking launch form
interface LtiLauchFormProps {
    // LTI Launch form in a serialized HTML <pre> snippet
    // sent by the tool provider (Opencast)
    // in response to the /lti/ci POST of the video selection.
    readonly formString: string,
}

// The LTI Launch form, returned by Opencast (OC) on /lti/ci POST
// is rendered and submitted to the tool consumer by this component.
// The form submission embeds the video as an LTI Deep Link (DL) launch
// in the host.
// The benefit of a video DL launch is that current host user and course
// context LTI data from the host is passed to Opencast at the time
// the video is launched from the host in the future.
export const LtiLaunchForm: React.FunctionComponent<LtiLauchFormProps> = ({
    formString,
}) => {

    // Auto-Submit the rendered LTI Deep Link form as soon as it's mounted.
    // The user has already selected this video to embed, per the /lti/ci POST.
    useEffect(()=>{
       const forms = document.getElementsByName('ltiLaunchForm');
       // NOTE: The debug/testing javascript from the HTML snippet
       // is scrubbed. It is not possible to view the html prior to posting
       // using this component. To view form post content, use the
       // native browser's inspector/developer tool's network tab
       if (forms.length > 0 && forms[0] instanceof HTMLFormElement) {
           // TODO: error handling for rejected submit?
           // Examples of rejection are when the host does not support
           // LTI DeepLink components or the user's session
           // with the host has timed out.
           forms[0].submit();
       }
    })

    // De-serialize the serialized form snippet
    const cleanString = DOMPurify.sanitize(formString);
    const cleanForm = parse(cleanString);

    // Return the rendered form.
    return (
        <div>
            {cleanForm}
        </div>
)}
```

2026-02-26 10:30 UTC, karendolan commented
@lkiesow @kristofkeppens was the LTI content item feature abandoned in upstream Opencast? We have been using this feature for at least 6 years. Our version may be slightly custom. Is it worth creating a new pull?

2026-02-28 11:20 UTC, karendolan commented
Will use this issue ticket for working on fresh pull

2026-02-28 11:21 UTC, karendolan commented
Opps, will open a new pull with issue ticket #2164

2026-02-28 11:21 UTC, closed without merging