Add Firewall Documentation
opencast/opencast pull request #2166
Opened 2020-12-17 23:21 UTC by lkiesow

This patch adds a simple overview of network communication in an
Opencast cluster and suggests two simple configurations.

---

The graphviz renders as:
![network](https://user-images.githubusercontent.com/1008395/102555278-bd62c080-40c6-11eb-960d-c7bff95d8275.png)

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2020-12-18 09:55 UTC, Arnei commented
I successfully build this (according to the instructions in `docs/guides/readme.md`) , but the graphic does not show. Is that to be expected?
![Bildschirmfoto vom 2020-12-18 10-52-25](https://user-images.githubusercontent.com/14070005/102600461-2544f580-411f-11eb-9521-dbbc37f39471.png)

2020-12-18 11:06 UTC, lkiesow commented
Ups, there seems to be one dependency missing from the docs. Try:

```sh
pip install mkdocs mkdocs-windmill
pip install markdown_inline_graphviz_extension
pip install markdown-inline-graphviz-extension-png
```

If I remember correctly, you had to run them as separate commands due to setup whankyness.
Will fix the docs…

2020-12-18 13:00 UTC, Arnei approved these changes

2021-01-08 22:13 UTC, gregorydlogan requested changes

2021-01-08 22:13 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/firewall.md
> +- Often Elasticsaecrh and ActiveMQ are run on the admin node since most communication then happens on the server
Elastics**ea**rch

2021-01-08 22:13 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/firewall.md
> +- All servers should get storage access
`network storage access` perhaps?  Something to make it clear that something like NFS is required.

2021-01-08 22:13 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/firewall.md
> +3. Allow the admin node to access Elasticsearch
4. Allow all nodes access to the storage infrastructure ?
I get that you're deliberately excluding other services (cf SSH), but I can see how people might be confused here if we don't mention it.

2021-01-08 22:13 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/firewall.md
> +- Capture agents communicate with Opencast via HTTP(S). All communication is established by the agent.
This is the only item with periods.  The lines in the diagram are already directional, maybe omit the last sentence.  Or add periods to all of them :)

2021-01-12 14:29 UTC, lkiesow commented
Fixed another typo. Ready for re-review

2021-01-12 14:46 UTC, merged