MH-12829 Switch and rename event details tabs
opencast/opencast pull request #218
Opened 2018-05-07 14:48 UTC by KatrinIhler

This PR switches the metadata and general tabs in the event details modal so that the metadata tab is in front. This accomplishes two things: 1. It's consistent with the series details modal, and 2. it makes more sense in my opinion to view the metadata first.

Additionally the general tab is renamed to publications tab since it contains publications and nothing else. For consistency a number of files and identifiers are also renamed. Because of naming conflicts (see discussion on list here) I thought it best to rename the resources for the assets tab to contain 'Asset' in their name, thus avoiding conflicts concerning 'eventPublicationsResource'. (I hope I didn't miss anything during my renaming spree, if I did, just comment and I'll fix it.)

See the attached screenshot for more details.

_This work is sponsored by ETH._

2018-05-08 11:21 UTC, staubesv requested changes
Hi @KatrinIhler 

Just found one little typo (wrong role name in mh_default_org.xml). Except for this, lgtm.

2018-05-08 11:21 UTC, staubesv commented on etc/security/mh_default_org.xml
> +    <sec:intercept-url pattern="/admin-ng/event/*/publications.json" method="GET" access="ROLE_ADMIN, ROLE_UI_EVENTS_PUBLICATIONS_GENERAL_VIEW" />
Remove "GENERAL"

2018-05-09 06:44 UTC, KatrinIhler commented on etc/security/mh_default_org.xml
> +    <sec:intercept-url pattern="/admin-ng/event/*/publications.json" method="GET" access="ROLE_ADMIN, ROLE_UI_EVENTS_PUBLICATIONS_GENERAL_VIEW" />
Thanks, fixed!

2018-05-09 07:26 UTC, KatrinIhler commented
@staubesv I had also missed to check in the changes I made to etc/listproviders/publication.channels.properties, fixed that, too.

2018-05-11 11:04 UTC, staubesv commented
Hi @KatrinIhler I'm currently testing this and found a first issue: If you click on the "Yes" in the Events table for a published event, the Event Detail modal opens the tab metadata. This should be the tab "Publications"

2018-05-14 12:36 UTC, KatrinIhler commented
@staubesv This was broken already, but wasn't visible until now - fixed!

2018-05-14 15:46 UTC, staubesv approved these changes

2018-05-14 15:54 UTC, merged