MH-12871 Ability to use user names in to/cc/bcc fields in send-email woh
opencast/opencast pull request #220
Opened 2018-05-07 20:53 UTC by rute-santos

Send-email WOH will look for a user in the user directory and use the user's email address if cc/to/bcc don't have a valid email address.

2018-05-08 11:18 UTC, staubesv requested changes
Hi @rute-santos 

I've done a first round of review and have the following findings:

- Typo (see comment)
- Usernames vs. email addresses (see comment)
- You should specify the dependency to the user directory in the pom too, shouldn't you?
- Please resolve the CI errors (see https://travis-ci.org/opencast/opencast/jobs/376081500)

After that, I will continue with the final tests.

2018-05-08 11:18 UTC, staubesv commented on modules/notification-workflowoperation/src/main/resources/OSGI-INF/operations/email.xml
> +  <reference name="userDIrectoryService" cardinality="1..1" interface="org.opencastproject.security.api.UserDirectoryService"
userD**I**rectoryService

2018-05-08 11:18 UTC, staubesv commented on modules/notification-workflowoperation/src/main/java/org/opencastproject/workflow/handler/notification/EmailWorkflowOperationHandler.java
> +        InternetAddress emailAddr = new InternetAddress(part);
This code assumes that usernames don't have the format of email addresses while a lot of services suggest users to use their email addresses as usernames. Just tested that Opencast works with usernames that are valid email addresses - it does.

I suggest to just omit this whole try block, i.e. try to look up the user. If a user is found, use its email address if available. If no user is found, just use the plain string.

If a user is found but has no email address, it might be better to log an error (instead of taking the raw string).

What do you think?

2018-05-09 15:59 UTC, rute-santos commented on modules/notification-workflowoperation/src/main/java/org/opencastproject/workflow/handler/notification/EmailWorkflowOperationHandler.java
> +        InternetAddress emailAddr = new InternetAddress(part);
Good point! I will make the changes.

2018-05-09 20:02 UTC, rute-santos commented
Hi @staubesv,
I made all the changes you requested. Thanks for your comments!
Rute

2018-05-11 08:48 UTC, staubesv approved these changes

2018-05-11 08:48 UTC, merged

2018-05-11 08:50 UTC, staubesv commented on docs/guides/admin/docs/workflowoperationhandlers/send-email-woh.md
> +        <configuration key="body-template-file">eventDetails</configuration>
Hi @rute-santos In case you have a good 'eventDetails' template at hands, it would be great if you could contribute it, too.