Remove dom4j
opencast/opencast pull request #2262
Opened 2021-01-27 23:13 UTC by lkiesow

This patch removes the dom4j dependency which was used solely to provide
an empty XML file for testing but was marked as non-test runtime
dependency. The included version of dem4j has some severe security
vulnerabilities and we should never use this.

Since this only included but never actually used, there is no security
risk.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2021-02-02 15:48 UTC, gregorydlogan commented
Should this be in `r/9.x`?

2021-02-03 13:59 UTC, lkiesow commented
No. This doesn't really hurt in 9.x since it's testing only and there would be merge conflicts, so I didn't bother.

2021-02-25 10:02 UTC, KatrinIhler commented
@lkiesow In the opencast-common pom there's a line that seems to explicitly exclude this:
>              !org.dom4j.*,

Can this then go as well?

2021-02-25 10:05 UTC, KatrinIhler requested changes
In the opencast-common pom there's a line that seems to explicitly exclude this:
>              !org.dom4j.*,

Can this then go as well?

Otherwise, this works just fine!

2021-02-25 16:31 UTC, lkiesow commented
> Can this then go as well?

If I remember correctly, no, it needs to stay.

2021-02-26 07:47 UTC, KatrinIhler approved these changes

2021-02-27 13:51 UTC, lkiesow commented
@gregorydlogan, since @KatrinIhler approved this already, and you do not seem to have any problem with the patch, do you still want to do an additional review? Or can we merge this?

2021-02-27 14:35 UTC, merged

2021-02-27 14:36 UTC, gregorydlogan commented
Merged. I hadn't had time to test this yet but if others are saying it works then I'm happy.