Added the access_policy to elasticsearch and made it searchable
opencast/opencast pull request #2293
Opened 2021-02-04 12:47 UTC by marwyg

closes #2104 

The events table in the admin ui should be searchable by the access_policy again, so someone can find events by the read and write rights.

2021-03-19 12:12 UTC, LukasKalbertodt requested changes
I tested this locally and it seems to work. That is: entering the name of a user or a group into the full-text search field shows events that contain that user/group in its ACL. Note however, that this is not equivalent to "all events the user has access to". If an event's ACL contains a group and a user gets access to the event through that group, searching for the user in the full-text search won't show the event. 

Also: Issue #2104 (which this PR fixes) was caused by https://github.com/opencast/opencast/pull/1090.  That PR and the linked issue seems like the only intended change was the `type: "keyword"` to `type: "text"`. So I wonder if the `index:false, store: false` addition was by mistake or whether there was a point in doing so? Maybe @wsmirnow can help us out here?

2021-03-19 12:12 UTC, LukasKalbertodt commented on modules/elasticsearch-impl/src/main/resources/elasticsearch/series-mapping.json
> +        "access_policy": { "type" : "text" },
Accidentally incorrect indentation change.

2021-04-27 12:58 UTC, marwyg commented on modules/elasticsearch-impl/src/main/resources/elasticsearch/series-mapping.json
> +        "access_policy": { "type" : "text" },
Removed the incorrect indentation. 

I talked with @wsmirnow about this. I think there were no particular reason for the change(?) I can't exactly remember what he said, only that he gave me the OK to remove the options, so the field can be searchable again.

2021-04-27 13:00 UTC, marwyg commented on modules/elasticsearch-impl/src/main/resources/elasticsearch/series-mapping.json
> +        "access_policy": { "type" : "text" },
So if it works and @wsmirnow don't have any complaints, is it ready to be merged?

2021-04-29 10:55 UTC, wsmirnow commented on modules/elasticsearch-impl/src/main/resources/elasticsearch/series-mapping.json
> +        "access_policy": { "type" : "text" },
I can't remember the exact reason for PR #1090. The [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html) matches the use case here, imo. Using type `text` and `index=true` (default preset) make sense for me.

2021-04-30 08:11 UTC, LukasKalbertodt commented on modules/elasticsearch-impl/src/main/resources/elasticsearch/series-mapping.json
> +        "access_policy": { "type" : "text" },
Ok I guess then it all makes sense and this can be merged.

2021-04-30 08:11 UTC, LukasKalbertodt approved these changes
After the discussion above we concluded this change makes sense!

2021-04-30 08:19 UTC, KatrinIhler commented
Merged since Lukas approves. :D

2021-04-30 08:19 UTC, merged