New woh: conditional-config
opencast/opencast pull request #2590
Opened 2021-05-10 20:51 UTC by rute-santos

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2021-05-10 20:54 UTC, gregorydlogan commented
Without looking at the code:
- Needs a note in the release notes
- _Could_ be moved to 9.x, although I don't actually care if we do.

2021-05-11 11:50 UTC, mtneug requested changes
I still need to run a test workflow, but it looks good from what I see so far. Only some minor complaints.

2021-05-11 11:50 UTC, mtneug commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/ConditionalConfigWorkflowOperationHandler.java
> +        logger.warn("Invalid condition to evaluate: {}.", condition);
This should be an error.

```suggestion
        logger.error("Invalid condition to evaluate: {}.", condition);
```

2021-05-11 11:50 UTC, mtneug commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/ConditionalConfigWorkflowOperationHandler.java
> +          logger.warn("Condition {}  evaluated to true, but no value informed to set {} variable in {}",
This should be an error.
```suggestion
          logger.error("Condition {}  evaluated to true, but no value informed to set {} variable in {}",
```

2021-05-11 11:50 UTC, mtneug commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/ConditionalConfigWorkflowOperationHandler.java
> +    return createResult(Action.CONTINUE);
I guess one could argue both ways: the operation evaluated a bunch of expressions, so it did something, but really nothing has changed after this operation. So maybe `SKIP` would be more appropriate? Regardless, I'm fine with either one.

2021-05-11 11:50 UTC, mtneug commented on modules/workflow-workflowoperation/src/test/java/org/opencastproject/workflow/handler/workflow/ConditionalConfigWorkflowOperationHandlerTest.java
> +    String xml = WorkflowConditionInterpreter.replaceVariables(WorkflowParser.toXml(workflowInstance),
`workflowInstance` is used directly.
```suggestion
    String xml = WorkflowConditionInterpreter.replaceVariables(WorkflowParser.toXml(wf),
```

2021-05-11 11:50 UTC, mtneug commented on docs/guides/admin/docs/workflowoperationhandlers/conditional-config-woh.md
> +All _condition-**X**_ are sorted as strings and then evaluated in sequence e.g. condition-1, condition-2, etc.
Could you add a description of what happens if multiple conditions are `true`? Conditions are evaluated in alphabetical order, which might be surprising (`condition-10` is evaluated before `condition-2`).

2021-05-11 15:07 UTC, rute-santos commented on docs/guides/admin/docs/workflowoperationhandlers/conditional-config-woh.md
> +All _condition-**X**_ are sorted as strings and then evaluated in sequence e.g. condition-1, condition-2, etc.
Will do. Yes, they are sorted alphabetically. The idea was that the part after the '-' could be anything, not only numbers, but I can change it to numbers if you think it is better. Please let me know.

2021-05-11 15:18 UTC, rute-santos commented on modules/workflow-workflowoperation/src/test/java/org/opencastproject/workflow/handler/workflow/ConditionalConfigWorkflowOperationHandlerTest.java
> +    String xml = WorkflowConditionInterpreter.replaceVariables(WorkflowParser.toXml(workflowInstance),
Good catch!

2021-05-11 20:21 UTC, mtneug commented on docs/guides/admin/docs/workflowoperationhandlers/conditional-config-woh.md
> +All _condition-**X**_ are sorted as strings and then evaluated in sequence e.g. condition-1, condition-2, etc.
No, I would also prefer any string. Just wanted to document the behaviour ;).

2021-05-11 20:22 UTC, mtneug approved these changes

2021-05-11 23:57 UTC, mtneug commented
Works for me.

2021-05-11 23:57 UTC, merged