Remove automatic handling of HLS bitrate ladder
opencast/opencast pull request #2591
Opened 2021-05-11 09:00 UTC by mtneug

When using HLS Opencast currently forces the use of `-b:v` and `-b:a`
for each stream. The bitrate is determined either from the same options
in the encoding profile or geometrically distribute between a min and a
max. This limits the rate control mechanism to either Average Bitrate
(ABR) (i.e. only setting `-b`) or Constant Bitrate (CBR) (i.e. setting
`-b`, `-maxrate`, `-minrate`, `-bufsize`). In particular, Constrained
Encoding (VBV) (i.e. setting `-crf`, `-maxrate`, `-minrate`, `-bufsize`)
is not possible.

This removes the bitrate handling in Opencast completely forcing the
user to properly setup the rate control in the used encoding profiles.

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2021-06-14 08:04 UTC, mtneug commented
As this could require config changes to the encoding profiles, this can't go into 10.x anymore, correct?

2021-10-20 14:57 UTC, mliradelc commented
It is a good PR, makes the encoding with HLS more future-proof.  I think needs  some documentation, specially in the upgrade guide for 11.x

2021-10-20 14:58 UTC, mliradelc commented
> As this could require config changes to the encoding profiles, this can't go into 10.x anymore, correct?

Yes, this can break some opencast installations because of the config changes.

2021-11-08 15:46 UTC, mtneug commented
Fixed conflicts.

2021-11-15 13:38 UTC, mliradelc requested changes
I approve the code, but it needs to be added a note in the documentation and upgrade guide about this change.

2021-11-17 18:28 UTC, mtneug commented
@mliradelc: I added a release note and updated the documentation that mentioned the removed keys. Maybe this can still make it into 11?

2021-11-17 19:10 UTC, mliradelc approved these changes

2021-11-17 19:10 UTC, mliradelc commented
> @mliradelc: I added a release note and updated the documentation that mentioned the removed keys. Maybe this can still make it into 11?

Yes, with this we can do it to 11

2021-11-17 19:10 UTC, merged