Closing tags for non-void elements in Admin UI
opencast/opencast pull request #2719
Opened 2021-06-12 14:00 UTC by Rillke

- Angular JS only supports `<void elements/>` from the HTML spec.

See
- angular/angular.js#1237
- https://stackoverflow.com/a/31724215/2683737

- Add static testing to CI to avoid silent future breakage
  - Test uses html-validate
    - https://html-validate.org/
    - https://gitlab.com/html-validate/html-validate

- Add a creator to WF status for a more complete mock server response

Resolves #2657
Resolves #2025
Based on/ Contains #2718

![image](https://user-images.githubusercontent.com/2311611/121775822-14cf7e00-cb8a-11eb-8889-d650df28f572.png)
![Screenshot from 2021-06-12 15-09-33](https://user-images.githubusercontent.com/2311611/121778421-15224600-cb97-11eb-99a5-ed22908e7c23.png)

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/#development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2021-06-14 05:22 UTC, JulianKniephoff commented
Since @Rillke called me out in Matrix, I'll just take this and #2718. :wink:

2021-06-14 06:17 UTC, JulianKniephoff requested changes
Very cool, more automated checking is always great, thanks for this! :smile: 

I have a couple very minor stylistic nitpicks. If you could still resolve those until tomorrow that would be great!

2021-06-14 06:17 UTC, JulianKniephoff commented on modules/admin-ui-frontend/app/scripts/shared/partials/modals/edit-events-metadata-modal.html
> +          <header translate="BULK_ACTIONS.EDIT_EVENTS_METADATA.REQUEST_ERRORS.TABLE.CAPTION" ></header>
```suggestion
          <header translate="BULK_ACTIONS.EDIT_EVENTS_METADATA.REQUEST_ERRORS.TABLE.CAPTION"></header>
```

2021-06-14 06:17 UTC, JulianKniephoff commented on modules/admin-ui-frontend/app/scripts/shared/partials/modals/edit-events-modal.html
> +                    <th class="fit" translate="BULK_ACTIONS.EDIT_EVENTS.SUMMARY.NEXT" ></th>
```suggestion
                    <th class="fit" translate="BULK_ACTIONS.EDIT_EVENTS.SUMMARY.TYPE"></th>
                    <th class="fit" translate="BULK_ACTIONS.EDIT_EVENTS.SUMMARY.PREVIOUS"></th>
                    <th class="fit" translate="BULK_ACTIONS.EDIT_EVENTS.SUMMARY.NEXT"></th>
```

2021-06-14 07:32 UTC, Rillke commented
> If you could still resolve those until tomorrow that would be great!

@JulianKniephoff pressed some buttons and your suggestions went into a new commit.

2021-06-14 13:23 UTC, JulianKniephoff approved these changes
Unfortunately I totally forgot our new rules about PRs having to be discussed at a technical meeting first, before being merged. I wasn't technically allowed to merge #2718, either. This will have to wait for 9.7, unfortunately. :slightly_frowning_face:

2021-06-14 13:45 UTC, Rillke commented
> Unfortunately I totally forgot our new rules about PRs having to be discussed at a technical meeting first, before being merged.

If we would like to get picky, we could say, while it applies to [newer versions](https://docs.opencast.org/develop/developer/development-process.html#acceptance-criteria-for-patches-in-different-versions), this requirement is [not yet documented for Version 9 of Opencast](https://docs.opencast.org/r/9.x/developer/development-process.html).

2021-06-15 09:03 UTC, JulianKniephoff commented
Alright, let's be pragmatic about this. :smile:

2021-06-15 09:03 UTC, merged