Fix Maven Plugin Multithreading Problems
opencast/opencast pull request #2863
Opened 2021-07-25 23:10 UTC by lkiesow

This patch fixes a few issues appearing when building with multiple
threads:

- The download-maven-plugin file locking [was broken
  ](https://github.com/maven-download-plugin/maven-download-plugin/issues/95),
  causing several modules (e.g. studio, editor) to fail. Updating the
  plugin fixes the problem.

- The phantomjs-maven-plugin is not thread-safe and causes all Theodul
  modules to fail. Unfortunately, [it is no longer maintained
  ](https://github.com/klieber/phantomjs-maven-plugin#phantomjs-maven-plugin)
  and we should consider removing it. Especially, since it it only
  needed for running the Jasmine tests which are disabled by default and
  also partly broken and known to be unreliable (that's why they were
  deactivated back then).

  For now, this patch makes Maven skip the phantomjs-maven-plugin as
  well if the Jasmine tests are disabled.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2021-07-26 09:40 UTC, mliradelc commented
I was looking how to run/try this, is
```
$ mvn clean install -T $(sysctl hw.physicalcpu | grep -o '[0-9]') -Pdev
```
(`...sysctl hw.phys...` is for macOS only)

2021-07-26 09:54 UTC, mtneug commented
`nproc` gives you the number of threads on your system. But `1.0C` should give you that aswell.

2021-07-26 10:04 UTC, mliradelc commented
> `nproc` gives you the number of threads on your system. But `1.0C` should give you that aswell.

Yes, but you need to install `coreutils` before to use it, anyway, is more easy to use `nproc` 😄 

Is it 1.0C single thread?

2021-07-26 10:30 UTC, mtneug commented
I'm using the following:

```
# sequential
$ rm -rf ~/.m2
$ mvn clean install

# parallel
$ rm -rf ~/.m2
$ mvn clean install --threads 1.0C -Pnone
```

The parallel build fails for `editor-service-endpoint-remote`:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:unpack (unpack) on project opencast-editor-service-endpoint-remote: Unable to find/resolve artifact.: Could not find artifact org.opencastproject:opencast-editor-service-endpoint:jar:10-SNAPSHOT in central (https://repo.maven.apache.org/maven2/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :opencast-editor-service-endpoint-remote
```

2021-07-26 12:50 UTC, mtneug requested changes
Fix build with clean local repository.

2021-07-26 12:51 UTC, mtneug commented
If we want to support parallel builds, we should also use that in CI. What do you think?

2021-07-26 16:09 UTC, lkiesow commented
> If we want to support parallel builds, we should also use that in CI. What do you think?

I think that's a good idea, but I thought, I let people play with it for a bit and figure out more problems first :grin:

2021-07-26 16:12 UTC, lkiesow commented
> Is it 1.0C single thread?

No. That's a core modifier. It depends on your machine. For me, that will result in 16 threads.
On an octa-core it should result in 8 threads, …

2021-07-26 16:15 UTC, lkiesow commented
> `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:unpack (unpack) on project opencast-editor-service-endpoint-remote: Unable to find/resolve artifact.: Could not find artifact org.opencastproject:opencast-editor-service-endpoint:jar:10-SNAPSHOT in central (https://repo.maven.apache.org/maven2/) -> [Help 1]`

Kind of sounds like a potential problem?

2021-07-26 19:46 UTC, mtneug commented
To be clear: `editor-service-endpoint` has not been built yet. Apparently, `editor-service-endpoint-remote` depends on `editor-service-endpoint`. Since it's not locally available, Maven tries to download it. Looking at the POM file, it seems some class files are copied over?

2021-07-26 20:38 UTC, lkiesow commented
That's a perfect example of something working by accident. There is definitely a dependency definition missing, since it clearly depends on the other package. Will you create a pull request fixing that, or shall I?

2021-07-27 15:33 UTC, mliradelc commented
> > Is it 1.0C single thread?
> 
> No. That's a core modifier. It depends on your machine. For me, that will result in 16 threads.
> On an octa-core it should result in 8 threads, …

Thanks for the answer, the docs I found on the internet, didn't tell anything about that is for choosing all the cores.

2021-07-29 19:01 UTC, lkiesow commented
> To be clear: `editor-service-endpoint` has not been built yet. Apparently, `editor-service-endpoint-remote` depends on `editor-service-endpoint`. Since it's not locally available, Maven tries to download it. Looking at the POM file, it seems some class files are copied over?

That's now fixed in #2879

2021-08-07 08:46 UTC, lkiesow commented
Pull request #2879 is merged. Anything holding this back?

2021-08-09 22:47 UTC, mtneug approved these changes
No LGTM

2021-08-09 22:47 UTC, merged

2021-08-10 10:57 UTC, mtneug commented
Found another problem on systems with a clean npm install: the `opencast-engage-paella-player` module runs `npm cache verify` which could interfere with parallel `npm install` operations. I don't see why Opencast builds should execute `npm cache verify` so let's remove it: #2917