Only run Github database test for sql scripts
opencast/opencast pull request #2877
Opened 2021-07-29 09:26 UTC by KatrinIhler

This way, the test script won't fail if we put any other scripts into our upgrade folders, as currently happening for #2857.

I tested this by creating a small test PR. When you put an sql script into an upgrade folder, that causes this test run, but a simple text file now won't trigger the test script, while it did before.

2021-07-29 09:26 UTC, KatrinIhler commented
@gregorydlogan Do you want to take a look at this?

2021-07-29 15:04 UTC, lkiesow requested changes
> This way, the test script won't fail if we put any other scripts into our upgrade folders, as currently happening for #2857.

Not true. This way, the test will not __run__ if you put other things in there. But the test will run and fail as soon as the next person actually touches the scripts.

2021-07-29 15:07 UTC, lkiesow commented
Modify https://github.com/opencast/opencast/blob/develop/docs/upgrade/.test.sh and test if `$dir/mysql5.sql` exists. Skip a folder if it does not.

2021-07-30 18:27 UTC, lkiesow commented
Or use
```
for sqlfile in *_to_*/mysql5.sql; do
   ...
done
```

2021-08-02 15:08 UTC, KatrinIhler commented
@lkiesow Okay, I think now I got it. The first commit ensures that the test only runs if an SQL script was changed. The second commit will check if a version folder actually contains an SQL script before trying to run it. :)

2021-08-02 15:35 UTC, lkiesow approved these changes

2021-08-06 10:00 UTC, merged