Sign publication URL of events in External API
opencast/opencast pull request #3002
Opened 2021-09-13 16:03 UTC by KatrinIhler

The External API already offers the `sign`-parameter to sign distribution URLs when requesting one or more events with their publications.
With this change, from version 1.7.0 onward the publication URLs themselves will also be signed if that flag is set and a signing provider is configured accordingly. The reason for this change is that SWITCH uses Stream Security to protect an external player.

This affects the following endpoints of the External API:
- getEvent
- getEvents
- getEventPublication
- getEventPublications

Version 1.7.0 was already introduced by #2814 for OC11, so I'm piggybacking off of that. ;) I also amended the docs accordingly.

2021-10-13 10:04 UTC, mliradelc requested changes

2021-10-13 10:04 UTC, mliradelc commented on docs/guides/developer/docs/api/events-api.md
> +`sign`                     | [`boolean`](types.md#basic) | Whether publication urls (version 1.7.0 or higher) and distribution urls should be pre-signed.
I don't understand about the meaning of `pre-signed`, Is it another signing before the Stream security signing?

2021-10-13 15:07 UTC, mliradelc commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +        return URI.create(urlSigningService.sign(url.toString(), expireSeconds, null, null));
Would be a nice idea to add a `logger.debug` to know if the url was succesfully signed

2021-10-13 15:08 UTC, mliradelc commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +        return URI.create(urlSigningService.sign(url.toString(), expireSeconds, null, null));
The code works, I've checked with the debugger 😄

2021-10-13 15:28 UTC, KatrinIhler commented on docs/guides/developer/docs/api/events-api.md
> +`sign`                     | [`boolean`](types.md#basic) | Whether publication urls (version 1.7.0 or higher) and distribution urls should be pre-signed.
No, I just meant that the URL is already signed when requesting the event, in contrast to signing the URL explicitly afterwards with requests to /signing. This wasn't supposed to be confusing...

2021-10-13 15:30 UTC, KatrinIhler commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +        return URI.create(urlSigningService.sign(url.toString(), expireSeconds, null, null));
I'd rather not add a debug log for something like that, since it's pretty apparent if the URL is signed or not, and this code could potentially be called a lot. :D

2021-10-15 07:49 UTC, mliradelc commented on modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
> +        return URI.create(urlSigningService.sign(url.toString(), expireSeconds, null, null));
I don't have strong opinions on this matter, so it's ok for me :)

2021-10-15 08:10 UTC, mliradelc commented on docs/guides/developer/docs/api/events-api.md
> +`sign`                     | [`boolean`](types.md#basic) | Whether publication urls (version 1.7.0 or higher) and distribution urls should be pre-signed.
Ok, so pre-sign means We don't make a request to the signing services after the query. from what I understand with versions lower than 1.6 all stays like always.

2021-10-15 08:42 UTC, mliradelc approved these changes
After testing and the doubts are now explained, its ok

2021-10-15 08:42 UTC, merged