Fixed limit value returned by search service endpoint
opencast/opencast pull request #3050
Opened 2021-10-08 13:12 UTC by Arnei

Previously, the limit value in the response xml/json was guessed at. This changes the value to actual limit that was being used.

Resolves #1173.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2021-10-11 07:26 UTC, lkiesow approved these changes

2021-10-13 14:58 UTC, lkiesow requested changes

2021-10-13 14:58 UTC, lkiesow commented on modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrRequester.java
> +    result.setLimit(limit);
Tested this, but unfortunately, it does not work like this.
Setting no limit or setting `limit=0` causes the limit to be set to the default value:

```
    if ((q.getLimit() > 0) && (q.getLimit() < QUERY_MAX_ROWS)) {
      query.setRows(q.getLimit());
    } else {
      query.setRows(QUERY_MAX_ROWS);
    }
```

…but this would claim 0. The same goes for values exceeding the `QUERY_MAX_ROWS`.

2021-10-15 09:44 UTC, Arnei commented on modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrRequester.java
> +    result.setLimit(limit);
Thanks for checking. It seems the `row` parameter of the SolrQuery would then make for a more appropriate `limit`.

2021-10-15 15:07 UTC, lkiesow approved these changes

2021-10-15 15:08 UTC, merged