Mediapackage directory cleanup
opencast/opencast pull request #3187
Opened 2021-11-19 15:26 UTC by lwillmann

Currently directories in the mediapackage folder of the Working File Repository and the Workspace will never be deleted. If you have a large installation like SWITCH it is impossible to use unix tools like `du` or `ls` to browse these directories or to find out how much disk space is used by each subfolder. Also the mediapackage folder inside the WFR is never cleaned up in any way.

This PR tries to improve the cleanup process of WFR and Workspace in the following ways:
1. Add a cleanup of old files in the mediapackage folder of the Working File Repository (including directories). 
2. Remove unused directories during the Workspace cleanup
3. Use the same implementation for both modules     

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2021-12-14 09:07 UTC, lwillmann commented
Please contact @KatrinIhler if you want some changes for this PR. I resigned from my job at ELAN e.V.

2022-02-09 08:57 UTC, geichelberger requested changes
I would suggest some code style changes and some minor changes.

2022-02-09 08:57 UTC, geichelberger commented on modules/working-file-repository-service-api/src/main/java/org/opencastproject/workingfilerepository/api/WorkingFileRepository.java
> +  boolean cleanupOldFilesFromMediapackage(long days) throws IOException;
MediaPackage should be written in camel case.

2022-02-09 08:57 UTC, geichelberger commented on modules/working-file-repository-service-impl/src/main/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryImpl.java
> +  public boolean cleanupOldFilesFromMediapackage(long days) throws IOException {
MediaPackage should be written in camel case.

2022-02-09 08:57 UTC, geichelberger commented on modules/working-file-repository-service-impl/src/main/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryRestEndpoint.java
> +  @RestQuery(name = "cleanupOldFilesFromCollection", description = "Remove files and directories from the working file repository under /mediapackage that are older than N days", returnDescription =
RestQuery name should be cleanupOldFilesFromMediaPackages

2022-02-09 08:57 UTC, geichelberger commented on modules/working-file-repository-service-impl/src/test/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryTest.java
> +  public void testCleanupOldFilesFromMediapackageNothingToDelete() throws Exception {
Camel case MediaPackage

2022-02-09 08:57 UTC, geichelberger commented on modules/working-file-repository-service-impl/src/test/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryTest.java
> +  public void testCleanupOldFilesFromMediapackageSomethingToDelete() throws Exception {
Camel case MediaPackage

2022-02-09 08:57 UTC, geichelberger commented on modules/working-file-repository-service-remote/src/main/java/org/opencastproject/workingfilerepository/remote/WorkingFileRepositoryRemoteImpl.java
> +  public boolean cleanupOldFilesFromMediapackage(long days) throws IOException {
Camel case MediaPackage

2022-02-09 08:57 UTC, geichelberger commented on modules/working-file-repository-service-impl/src/test/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryTest.java
> +    // Cleanup files older than 1 day, nothing should be deleted
The comment is wrong. This test case deletes files.

2022-02-18 15:36 UTC, gregorydlogan commented
@KatrinIhler ping.  I noticed that @lwillmann is gone, making sure you're following this.

2022-02-21 12:42 UTC, KatrinIhler commented
@gregorydlogan It's on my to do list, but not close to the top right now :D

2022-03-16 15:53 UTC, KatrinIhler commented
@geichelberger Thanks for the review, I addressed all your findings :)

2022-03-17 10:39 UTC, KatrinIhler commented
Btw, this is currently running on the SWITCH productive system, and it shrunk our work nfs share from multiple TB to a couple hundred GB. It was great. :D

2022-03-18 13:48 UTC, geichelberger approved these changes
It is working as expected on my local test instance. I will backport this feature and run it in production :)

2022-03-21 15:10 UTC, KatrinIhler commented
Since @geichelberger tested and approved this, I'm gonna go ahead and merge it. :)

2022-03-21 15:10 UTC, merged