MH-12966: Fix pre-select-from for metadata fields
opencast/opencast pull request #334
Opened 2018-07-09 13:34 UTC by pmiddend

This adds a new attribute called `pre-select-from-value` to select inputs which use `pre-select-from`. With this enabled, the single value isn’t taken directly from the list given, but from the `.value` attribute of the selected list element.

We need this for the metadata fields, for example in the “Event Details” modal. This is currently broken, as it tries to set the value of the series to an object containing a label and a value, instead of just the value.

This work was sponsored by SWITCH.

2018-07-09 13:35 UTC, pmiddend commented
See also:

https://github.com/opencast/opencast/pull/312

2018-08-06 14:17 UTC, KatrinIhler commented
I guess this might no longer be necessary if PR #312 gets merged, or is it?

2018-08-15 22:38 UTC, lkiesow commented
@KatrinIhler, do you want to take the review for this? You seem to be involved anyway.

2018-08-17 09:03 UTC, KatrinIhler requested changes
So this fixes the preselectfrom on metadata fields without breaking it in other places, which is good. I don't agree with the way it works on the metadata fields though (and which was one reason the preselection was removed completely from metadata fields in PR #312), and even though this PR only recreates the old behaviour, I think it could be fixed here:

In my opinion, the preselection of a value for a metadata field should only happen if the field is required, because if it is not, there are really two valid options: The value, or no value at all. Otherwise the user might have to set the fields back to blank that should not be filled, so the preselection doesn't save any work in that case...

2018-08-17 14:01 UTC, staubesv commented
Hi @KatrinIhler 

This PR was basically created because of concerns mentioned in #312.

It is true that the pre-selection would need to consider whether a field is mandatory or not if used in the metadata property sheets. But as #312 has removed this directly from the metadata property sheet, the problem does not exist anymore.

I see two options here:
a) we just decline the PR as it is not needed anymore
b) we merge the PR in case it would be needed in the future

No strong opinion from my side - what do you prefer?

2018-08-17 14:24 UTC, KatrinIhler commented
@staubesv Well there is a third option: Add to this PR so that preselection will only happen on metadata fields that are required. Not sure how long that would take though. If that option is not acceptable, I guess I would prefer declining this PR and maybe holding on to that code somewhere else in case someone wants to go for option 3, because there's already a lot of code in opencast that is there "just in case" and as a developer I find that more confusing than helpful.

2018-08-17 14:33 UTC, staubesv commented
@KatrinIhler We don't need the pre-select-from in the metadata property sheets for us and therefore won't work on this anymore.

-> I'm fine with this PR being declined

2018-08-20 06:41 UTC, KatrinIhler commented
@staubesv I don't have the rights to decline a PR (not a commiter yet), so can you do it?

2018-08-20 07:21 UTC, staubesv commented
I decline this PR as it has become obsolete.

2018-08-20 07:21 UTC, closed without merging