MH-12987 Prohibit changing a scheduled event to be in the past
opencast/opencast pull request #335
Opened 2018-07-09 15:24 UTC by krinnewitz

While it is not possible to create a scheduled event which ends in the
past, changing an existing one to end in the past is still possible
using Event Details -> Scheduling.

Fixed by adding an error message and not saving the data.

This work is sponsored by SWITCH.

2018-07-09 16:02 UTC, karendolan commented
Hi @krinnewitz, "As an administrator... I would like to stop a recording for a class that has ended early withouth having to figure out the current time and then add a few minutes to the current time to put in the schedule end time in order to stop the event prior to it's scheduled end time". In other words, how hard would it be to add an "end now" button that adds the magic minimum now+buffer time to the schedule end time and submits the change? The button prevents the user from *wanting* to add a time in the past to the schedule end.

2018-07-10 08:16 UTC, krinnewitz commented
Hi @karendolan, I think adding such a button would take about one or two hours. Buffer time should be configurable, I guess.

2018-07-16 18:24 UTC, lkiesow commented
@karendolan, note that CAs would need to support updating the schedule while they are already recording.

Btb, do you want to review and merge this?

2018-07-26 22:26 UTC, gregorydlogan commented
@krinnewitz conflicts here

2018-07-27 17:17 UTC, krinnewitz commented
Thanks @gregorydlogan. I have fixed the conflict.

2018-08-16 21:34 UTC, lkiesow requested changes
@krinnewitz, looks good and is ready to be merged except for the notification which reads `Scheduling error: The event has already ended.` But since it's scheduled and the date could not be changed to something in the past, it has not yet ended :-)

My suggestion would be to use a notification like this:

>  The schedule could not be updated: You cannot schedule an event to be in the past.

2018-08-17 09:55 UTC, krinnewitz commented
@lkiesow good point. I updated the PR accordingly, based on your proposal.

2018-08-17 12:02 UTC, merged

2018-08-17 12:02 UTC, lkiesow commented
Thanks for the change → merged