Remove solr after workflows from xml to databases tables
opencast/opencast pull request #3377
Opened 2022-01-26 16:16 UTC by Arnei

This PR requires/contains #XY!

Removes all Solr functionality from the workflow service. The workflow service now instead completely relies on the database. Code that would only work with the Solr Index has also been removed.

Key changes:
- Removes internal collecting and storing of workflow statistics from the workflow service, as well as related endpoints. Instead, numbers about workflows can already be gotten from [the metrics endpoint](https://docs.opencast.org/r/11.x/admin/#modules/metrics/#metrics-openmetrics-prometheus)
- Removes the full text workflow query endpoint from the workflow service and External API, since it requires indexing of workflow data. By creating an Elasticsearch index for workflows, the query could be reintroduced to the External API in the future.
- Modifies the count endpoint in the workflow service by removes querying for current operation. By creating an Elasticsearch index for workflows, querying by current operation could be reintroduced to the External API in the future.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-05-10 19:15 UTC, lkiesow commented
Rebased this on `develop` which now includes the final version of #3376.
The original commit was 75ce0f50e1899f36ee8e0495c410e810d7aede5f.

2022-05-11 21:32 UTC, lkiesow requested changes

2022-05-11 21:32 UTC, lkiesow commented on docs/guides/admin/docs/releasenotes.md
> +
```suggestion
```

2022-05-11 21:32 UTC, lkiesow commented on modules/conductor/src/main/java/org/opencastproject/event/handler/WorkflowPermissionsUpdatedEventHandler.java
> +      List<WorkflowInstance> result = workflowService.getWorkflowInstancesBySeries(seriesId);
This may be dropped by the removal of ActiveMQ

2022-05-11 21:32 UTC, lkiesow commented on modules/conductor/src/main/java/org/opencastproject/event/handler/WorkflowPermissionsUpdatedEventHandler.java
> +        if (SeriesItem.Type.UpdateAcl.equals(seriesItem.getType())) {
Why do we even want to update series ACLs for old workflows?

2022-05-11 21:32 UTC, lkiesow commented on modules/conductor/src/main/java/org/opencastproject/event/handler/WorkflowPermissionsUpdatedEventHandler.java
> +                    dublinCoreService.serialize(seriesDublinCore));
And we just trow the data for these old workflows somewhere in the working file repository and workspace? That doesn't sound right.

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java
> +        ),
These queries are identical

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java
> +                name = "Workflow.toCleanup",
/me: Check usage

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowService.java
> +   * Only used internally when a series is updated
Maybe, we can remove this?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabase.java
> +  List<WorkflowInstance> getWorkflowInstancesForCleanup(WorkflowInstance.WorkflowState state, Date dateCreated)
Check what this is used for…

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
>     * {@inheritDoc}
indentation

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
> +      throw new WorkflowDatabaseException(e);
```suggestion
      throw new WorkflowDatabaseException("Error fetching workflows from database", e);
```

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
> +  public int countWorkflows(WorkflowInstance.WorkflowState state) throws WorkflowDatabaseException {
Maybe return long instead?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
> +      Query query = em.createNamedQuery("Workflow.getCount");
TypedQuery?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
> +      throw new WorkflowDatabaseException(e);
```suggestion
      throw new WorkflowDatabaseException("Could not find number of workflows.", e);
```

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
> +      Query query = em.createNamedQuery("Workflow.bySeries");
TypedQuery?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/endpoint/WorkflowRestService.java
> +    } catch (WorkflowException e) {
collapse

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
> +    return false;
Why sometimes return `false` and sometimes throw an `UnauthorizedException`?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
> +      throw new WorkflowDatabaseException(e);
Why rethrow this?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
> +      } catch (UnauthorizedException e) {
simplify

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
> +      }
Do we want to check every workflow or is the current archived ACL the “correct” one?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
> +      throw new WorkflowDatabaseException(e);
why rethrow?

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
>    public void updated(Dictionary properties) {
empty.

2022-05-11 21:32 UTC, lkiesow commented on modules/workflow-service-remote/src/main/java/org/opencastproject/workflow/remote/WorkflowServiceRemoteImpl.java
> +    queryStringParams.add(new BasicNameValuePair("seriesId", seriesId));
I don't think this is used

2022-05-11 22:20 UTC, lkiesow commented on modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java
> +        ),
Seems like `Workflow.getCountOperationState` is unused.

2022-05-12 16:16 UTC, lkiesow approved these changes

2022-05-12 21:16 UTC, gregorydlogan approved these changes
Very minor questions, IMO PR can go ahead as is.  It's *much* easier to review when at least one other reviewer has already done a review haha

2022-05-12 21:16 UTC, gregorydlogan commented on docs/guides/admin/docs/releasenotes/remove-solr-from-workflow-service.txt
> +- [TBD] - Remove tasks.json Endpoint from Admin-UI JobEndpoint
I'm assuming we'll go back and fix this in a follow on PR?

2022-05-12 21:16 UTC, gregorydlogan commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
> +      return currentUser.hasRole(GLOBAL_ADMIN_ROLE) || authorizationService.hasPermission(mediaPackage, action);
Should this also be checking the org admin roles?  From the looks of things `authorizationService` doesn't...

2022-05-13 13:33 UTC, lkiesow commented on modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
> +      return currentUser.hasRole(GLOBAL_ADMIN_ROLE) || authorizationService.hasPermission(mediaPackage, action);
Fixed. Organization admins now get access as well.

2022-05-13 13:35 UTC, lkiesow commented on docs/guides/admin/docs/releasenotes/remove-solr-from-workflow-service.txt
> +- [TBD] - Remove tasks.json Endpoint from Admin-UI JobEndpoint
This I actually missed. The TBD are actually things which happened. But this meant that some rather important documentation was missing. In particular, the breaking changes to the External API, but also the API modifications from the workflow service itself. I've updated the documentation. Do you want to read through it again?

2022-05-13 22:22 UTC, lkiesow commented
Rebased to fix merge conflicts

2022-05-17 23:17 UTC, lkiesow commented
No complaints on list either → merging.

2022-05-17 23:20 UTC, merged