Fix version sorting in Matrix room bot
opencast/opencast pull request #3552
Opened 2022-03-23 17:31 UTC by gregorydlogan

Using the correct sort type resolves in the issue in testing

﻿### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-03-23 19:48 UTC, lkiesow requested changes

2022-03-23 19:48 UTC, lkiesow commented on .github/workflows/update-matrix-room.yml
> +          STABLE="$(echo "$TAGS" | sort -version-sort | tail -n1)"
Didn't test this, but this should be:
```suggestion
          MAJOR="$(echo "$TAGS" | sed 's/\..*$//' | sort --version-sort | tail -n1)"
          STABLE="$(echo "$TAGS" | sort --version-sort | tail -n1)"
```

2022-03-23 20:16 UTC, gregorydlogan commented
Derp, that's what I get for using a crappy keyboard, and a bit too much copy+paste

2022-03-24 21:59 UTC, lkiesow approved these changes

2022-03-29 20:22 UTC, merged