Disable group removement upon missing group roles
opencast/opencast pull request #3672
Opened 2022-04-13 14:23 UTC by jduehring

This PR addresses #3509 . When logging in via Shibboleth there is currently a check which matches all the primary group roles of a user with its corresponding group memberships. If a primary group role is not present, but the user is part of the corresponding group, the user gets removed from the group. 

The problem is that when adding a new user to a group, the user will get saved in the database, but won't get the primary group role and therefore will be removed from the group after the next login. 

I do not really see a reason for making it a hard constraint that the primary group role must be present in the users role list in order to be part of that group. It should be sufficient to rely on the `oc_group_member` database table to track all group memberships. 
For that reason I removed the part in the code which was responsible for the removement of group memberships when checking the primary group roles.

I would need someone with a Shibboleth system to test, if this fixes the problem, since I do not have a suitable local setup to test this. 

I would also appreciate feedback if the removal of group memberships served any special purpose which I might have missed.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-04-20 20:28 UTC, majosch commented
I've just deployed this PR (on Opencast 11.6) to our test installation (Rocky 8.5, shibboleth 3.3.0) and can confirm that users are not removed from groups after login/logout anymore.

Martin Schamberger
(University of Vienna)

2022-04-25 17:50 UTC, gregorydlogan requested changes
IMO this behaviour is important enough that this change should be accompanied by a unit test as well.  The fact that you can make this change *without changing existing testing* is worrying enough...

2022-04-25 17:50 UTC, gregorydlogan commented on modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaGroupRoleProvider.java
> +      if (roleList.contains(group.getRole())) {
This *seems* reasonable, but breaks things in at least one subtle way:

- `JpaUserAndRoleProvider`:496 uses `updateGroupMembershipFromRoles` to set the group membership to an empty set before deleting the user.  Removing the removal here will leave dangling references.

2022-05-31 15:33 UTC, gregorydlogan commented
@majosch @jduehring can you confirm that there aren't dangling references left behind?  This should make the next 11.x release.

2022-06-05 20:03 UTC, jduehring commented
@gregorydlogan I put the removal in a separate method, including some unit testing and checked for other usages of `updateGroupMembershipFromRoles`. There should be no dangling references left.

2022-06-06 17:24 UTC, gregorydlogan approved these changes
LGTM

2022-06-06 17:25 UTC, merged