MH-13023 Let default value fulfill requirement
opencast/opencast pull request #370
Opened 2018-08-08 07:52 UTC by KatrinIhler

This fixes a problem where a required metadata field is not considered filled even though there is a default value set.

2018-08-13 14:38 UTC, staubesv requested changes
I've just found a minor cosmetic issue (dubious newline). Once that fixed, this PR is ready to go.

2018-08-13 14:38 UTC, staubesv commented on modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-group/metadata.js
> +
Please remove that newline (or is there a specific reason to add it?)

2018-08-14 08:36 UTC, KatrinIhler commented
@staubesv Fixed, thanks for noticing!

2018-08-14 09:03 UTC, staubesv approved these changes

2018-08-14 09:03 UTC, merged