Add Placeholder for Height Resolution to Rename-Files
opencast/opencast pull request #3781
Opened 2022-05-19 20:18 UTC by Piriya-VM

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-05-20 13:03 UTC, lkiesow commented
A short notice that Apereo has received @Piriya-VM 's ICLA. As usual, it might take a bit of time for them to process it, meaning that you might still see complaining tests if you file new pull requests right now. Ignore that and point to this comment if necessary. There is now no reason to not accept patches from you based on the ICLA. Also, thanks for filing it!

2022-05-24 12:51 UTC, geichelberger requested changes
LGTM

2022-05-24 12:52 UTC, geichelberger requested changes

2022-05-24 12:52 UTC, geichelberger commented on modules/rename-files-workflowoperation/src/main/java/org/opencastproject/workflow/handler/rename/RenameFilesWorkflowOperationHandler.java
> +
Only one blank line should be sufficient.

2022-05-30 22:02 UTC, merged