MH-13044, Organization server configuration documentation
opencast/opencast pull request #390
Opened 2018-08-20 15:48 UTC by lkiesow

In the previous configuration it was not exactly clear how this should
be configured in a non-multi-tenant system and neither where the values
it should get if multi-tenancy was used.

2018-08-20 15:50 UTC, lkiesow commented
@JulianKniephoff, can you check if this is correct?

2018-08-21 07:30 UTC, JulianKniephoff requested changes
Regarding the content this looks right. I added a few nitpicks about the wording, though. :wink:

2018-08-21 07:30 UTC, JulianKniephoff commented on etc/org.opencastproject.organization-mh_default_org.cfg
> +# Server names that identifies the organization (tenant)
Typo: "[...] names that **identify** [...]"

2018-08-21 07:30 UTC, JulianKniephoff commented on etc/org.opencastproject.organization-mh_default_org.cfg
> +# Server names that identifies the organization (tenant)
I'm also not sure whether "identify" is really the best choice of word here. The organization can have more hosts than are listed here, as you correctly state below, namely those potentially listed by other nodes.

Maybe something like:

> Server names that **belong** to the organization (tenant)

2018-08-21 07:30 UTC, JulianKniephoff commented on etc/org.opencastproject.organization-mh_default_org.cfg
> +# The usage of this is to map a request to a specific organization. For example:
I'm not sure this example is entirely clear to me. Maybe expand it a bit? Trying it myself, though, makes this comment super long which is also not ideal so maybe it's fine. :thinking:

2018-08-21 07:30 UTC, JulianKniephoff commented on etc/org.opencastproject.organization-mh_default_org.cfg
> +# Even though admin-a and admin-b are the same node.
Maybe "might be" instead of "are".

2018-08-21 10:06 UTC, JulianKniephoff approved these changes

2018-08-21 12:12 UTC, merged