Add navigation shortcuts in admin ui modals
opencast/opencast pull request #3998
Opened 2022-07-19 17:28 UTC by owi92

This adds key combinations to switch tabs in the new-event and new-series modals.

The combinations are: 
`alt + enter` for **next** or - if applicable - the **create** button,
and:
`alt + backspace` for the **previous** button.
(alt == option on macOS)

**Note**: Shortcuts will not be detected while `<input>` or `<select>` elements are focused. In most cases, you will need to press the `enter`key first. There might be a workaround/fix by adding the `mousetrap`class to those elements, but I am uncertain if this would disrupt any other functionality or if this is even an issue, so any feedback on that would be appreciated.

US translations for the hotkey cheatSheet are included and can be seen by pressing the `?`key while the modals are open.

This feature was originally requested by the ETH (closes eth-244).

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-07-19 17:46 UTC, lkiesow commented
Apereo received an ICLA from Ole. Please ignore that failed test.

2022-07-20 08:59 UTC, lkiesow requested changes
ESLint fails on your code. Should be easy to fix though:

```
 [INFO] > eslint
[INFO] > eslint --config ../../docs/checkstyle/eslintrc.js --rule 'no-unused-vars: off' --rule 'no-empty: off' app/ --resolve-plugins-relative-to .
[INFO] 
[INFO] 
[INFO] /home/runner/work/opencast/opencast/modules/admin-ui-frontend/app/scripts/shared/directives/wizardDirective.js
[INFO]   121:7  error  Trailing spaces not allowed  no-trailing-spaces
[INFO]   123:7  error  Trailing spaces not allowed  no-trailing-spaces
[INFO]   277:9  error  Missing semicolon            semi
[INFO]   282:9  error  Missing semicolon            semi
[INFO] 
[INFO] ✖ 4 problems (4 errors, 0 warnings)
[INFO]   4 errors and 0 warnings potentially fixable with the `--fix` option.
```

2022-08-18 08:21 UTC, Arnei approved these changes

2022-09-08 13:03 UTC, mtneug commented
@Arnei, @lkiesow can this be merged?

2022-09-08 14:59 UTC, Arnei commented
I'd say this can be merged.

2022-09-15 00:05 UTC, merged