Add comments in the event index
opencast/opencast pull request #4029
Opened 2022-07-28 09:55 UTC by Arnei

Adds comment reason, text and resolvedStatus to the events index. This allows for filtering events by certain comments in the Admin UI by using the searchbar. For example, if you are using the notes column in the events table, you could search for all events that have a note that contains "silent". 

Does not add all available comment information to the index. Maybe it should?
Does not add replies (comments that reply to comments). Maybe it should?

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-08-13 11:24 UTC, lkiesow commented
Will the index be migrated without resetting the whole thing and rebuilding the index?

2022-09-15 00:06 UTC, gregorydlogan commented
@Arnei ping above.

2022-09-15 07:13 UTC, Arnei commented
I'm not sure. Will take a look at this when I have the time.

2022-09-15 14:29 UTC, Arnei commented
Nope, as it is this requires a rebuild :(

2022-09-16 15:22 UTC, gregorydlogan commented
Ok, please add the relevant bits to the release notes then!

2022-09-16 15:23 UTC, gregorydlogan requested changes
Requesting release notes txt file

2022-10-06 18:43 UTC, merged