Add thumbnail support to new editor backend
opencast/opencast pull request #4086
Opened 2022-08-17 07:35 UTC by Arnei

Modifies the editor-service to support thumbnails.

The editor service sends exisiting thumbnails to the frontend, and gets newly generated thumbnails from the frontend to save in the archive. It does not do any thumbnail generation itself.

As of now, thumbnails received from the frontend are not added to any publication (maybe they should?), just the archive. When using the thumbnail editor, Opencast workflows will need to be modified in such a way that they do not accidentally overwrite thumbnails.

Related editor PR: https://github.com/opencast/opencast-editor/pull/760

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-09-16 15:49 UTC, gregorydlogan requested changes
LGTM, needs the release notes file still.

2022-09-16 15:49 UTC, gregorydlogan commented on modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
> +              .orElse(null);
I'm concerned this `null` will cause issues in the future, but this is *probably* fine for now since nothing else is using this.  Yet.

2022-09-23 10:41 UTC, Arnei commented
@gregorydlogan Just noticed that I filed this against develop. Do you think it would be fine to go into r/12.x?

2022-09-27 04:08 UTC, gregorydlogan commented
I think so, given that the code should work without config changes.

2022-10-04 23:46 UTC, merged