Add optional key "skip-if-target-flavor-has-elements" to Image WOH
opencast/opencast pull request #4089
Opened 2022-08-17 13:43 UTC by Arnei

Adds an optional key to the image workflow operation handler that skips the operation if the specified target flavor contains at least one element. This can for example be useful if, for some events, you provide the images in some other form and don't want them to be overwritten by your image operation.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-08-17 16:03 UTC, geichelberger requested changes

2022-08-17 16:03 UTC, geichelberger commented on modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/ImageWorkflowOperationHandler.java
> +  public static final String OPT_SKIP_IF_TARGET_FLAVOR_HAS_ELEMENTS = "skip_if_target_flavor_has_elements";
All the other keys use dashes. Changing the style to underscores could be unexpected and error-prone.

2022-08-24 09:37 UTC, lkiesow commented
Assuming you have `presenter/img` and `presentation/img` as target flavor, the new option is set to `true` and someone previously uploaded `presenter/img`, would the operation now also skip generating `presentation/img`?

2022-08-24 09:41 UTC, lkiesow commented on modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/ImageWorkflowOperationHandler.java
> +      if (cfg.skipIfTargetFlavorHasElements && mp.getElementsByFlavor(cfg.targetImageFlavor).length > 0) {
Couldn't the target flavor be `*/*`? In which case it would end up being the source flavor? This check wouldn't catch that, would it?

2022-08-30 19:42 UTC, mtneug commented
I don't like this very specific option for just a single operation. We actually have a more generic solution for this with the `AnalyzeMediapackageWorkflowOperationHandler` operation.

2022-09-08 13:06 UTC, mtneug commented
@Arnei do you think this can be dropped in favor of `AnalyzeMediapackageWorkflowOperationHandler`?

2022-09-08 15:03 UTC, Arnei commented
It completely slipped my mind that `AnalyzeMediapackageWorkflowOperationHandler` is a thing, I agree that the more generic solutions is better, so I'll close this PR.

2022-09-08 15:03 UTC, closed without merging