Add index for oc_job_argument table
opencast/opencast pull request #4179
Opened 2022-09-09 10:46 UTC by mtneug

JPA previously did not create an index for the job_argument table (that has no primary key). This differs compared to the custom DDL script we used to have until Opencast 8. We have seen very slow query times resulting in slow scheduling.

Also see #4076.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-09-13 15:44 UTC, gregorydlogan commented
NB: This needs testing to see if that the index is autogenerated on existing schemas.  This may affect mergability depending on how expensive that operation is...

2022-09-15 08:06 UTC, mtneug commented
Just tested this locally by deleting the index and restarting Opencast. This did **not** recreate the index. So I think we need a migration.

2022-09-19 19:35 UTC, mtneug commented
This now includes the migrations.

2022-09-21 16:01 UTC, lkiesow reviewed
I'm fine with the automated part going into `r/12.x` since it will be automatically created and will not cause any manual steps, but the migration scripts should probably go into `12_to_13` only, there shouldn't be one for minor versions. Especially if this is already in Opencast since Opencast 8. I'm fine with adding a notice that people can apply this in advance, but I wouldn't do that as a script directory but in the release notes, since otherwise people will wonder what's the difference.

On that note: This should go into the release notes directory anyway.

I'm also wondering if we could always auto-create this by setting the table to create or extend:

https://github.com/opencast/opencast/blob/6900011a4a37bd22d8daf7d7421794e65661ae00/modules/adopter-registration-impl/src/main/resources/META-INF/persistence.xml#L14

2022-10-31 16:14 UTC, gregorydlogan commented
@mtneug ping on this.

2022-11-14 09:40 UTC, ziegenberg requested changes

2022-11-14 09:40 UTC, ziegenberg commented on docs/upgrade/12_to_13/postgresql.sql
> +CREATE INDEX IF NOT EXISTS IX_oc_job_argument_id_argument ON oc_job_argument (id, argument);
This is not going to work. I receive the following error message from our PostgreSQL:

```
index row requires 10032 bytes, maximum size is 8191.
```
This seems to be a hard limit on PostgreSQL.

2022-11-14 09:41 UTC, ziegenberg commented on docs/upgrade/12_to_13/postgresql.sql
> +CREATE INDEX IF NOT EXISTS IX_oc_job_argument_id_argument ON oc_job_argument (id, argument);
Others seem to have stumbled across this before: https://postgrespro.com/list/thread-id/1506742

2022-11-16 00:45 UTC, mtneug commented
Closed in favor of #4450

2022-11-16 00:45 UTC, closed without merging