Fix composer incident codes and messages for process-smil and multiencode.
opencast/opencast pull request #4208
Opened 2022-09-14 18:22 UTC by rute-santos

Needs someone to add the German translation to the properties file. I can only do Portuguese :)

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-09-21 12:56 UTC, mliradelc requested changes
Here are the changes for the German translation

2022-09-21 12:56 UTC, mliradelc commented on modules/composer-ffmpeg/src/main/resources/incident-l10n/org.opencastproject.composer_de.properties
> +20.description = The videos '\#{videos}' could not be encoded using the profiles '\#{profiles}'.
Here is translated to German, if a native speaker can check it would be great.

```suggestion
#  videos The source media
#  profiles The encoding profiles
19.title = Prozess-smil fehlgeschlagen
19.description = Die Videos '\#{videos}' konnten nicht mit den Profilen '\#{profiles}' kodiert werden.
# params:
#  videos The source media
#  profiles The encoding profiles
20.title = Multicode fehlgeschlagen
20.description = Die Videos '\#{videos}' konnten nicht mit den Profilen '\#{profiles}' kodiert werden.
```

2022-09-22 05:16 UTC, gregorydlogan commented
These... these should not be here.  Why aren't they in Crowdin?  Where do these end up being displayed?  Perhaps the better solution here is to move the translations to somewhere else.

2022-09-22 16:57 UTC, rute-santos commented
Having these here was a surprise to me too. They show up in the Workflows Errors & Warning section in the ui. I just fixed the messages; all our process-smil errors were showing up as "caption" :)

2022-09-23 07:49 UTC, mliradelc commented
@gregorydlogan Also surprises me, but it is a very tiny fix, what I can do to add those lines in Crowdin?

2022-10-04 22:08 UTC, gregorydlogan commented
@mliradelc I'm going to merge this since these seem right (I hope?), but here's how to fix this properly:

1) Reimplement [this method](https://github.com/opencast/opencast/blob/18197767bcf13640904c1c3964d71ad192e5fc33/modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/OsgiIncidentService.java#L160) to handle json format stuff
2) Replace the source and translation files with hand-done stuff initially
3) Add the files to [the crowdin config](https://github.com/opencast/opencast/blob/bdc62411967aa514627e6116b7dc9d3e3eafab1a/.crowdin.yaml)

This is worth its own issue, some I'm going to repost this comment as a new issue.

2022-10-04 22:11 UTC, merged