MH-13083: Unify modal navigation
opencast/opencast pull request #423
Opened 2018-09-12 16:17 UTC by jaysuz

(Copied from [Jira](https://opencast.jira.com/browse/MH-13083))
The detail modals in the Admin UI are not consistent considering...

- Title of modal window
- Navigation between individual objects

The goal of this story is to make the detail modals consistent considering the user experience.

2018-09-14 12:03 UTC, KatrinIhler requested changes
I tested this and found a couple of things:

2018-09-14 12:03 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/groupController.js
> +            reloadSelectedRoles();
Switching between groups in the event details window throws a n.role.available.$promise is undefined error and the roles aren't updated.

2018-09-14 12:03 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js
> +        console.log($scope.searchField);
This should be removed.

2018-09-14 12:03 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js
> +
When I create a new user by simply filling out all required fields (so no roles for example), I repeatedly get the error "Error: n.userForm is undefined" for as long as that user exists. I can't reproduce this on develop.opencast.org so this probably has something to do with your changes? No idea with what exactly, though.

2018-09-19 12:10 UTC, jaysuz commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js
> +        console.log($scope.searchField);
Done.

2018-09-19 12:13 UTC, jaysuz commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/groupController.js
> +            reloadSelectedRoles();
Addressed with 590a6b83291a6ca8074747e5492e3328dc4c7ce0.

2018-09-19 12:58 UTC, jaysuz commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js
> +
For me, this happens on the develop branch as well, so I don't think this issue is related to the changes I've made. However, I noticed that the "getSubmitButtonState" method is invoked constantly, thus possibly causing this error. When using the ngClass directive as in 48a49bfb6f2d3d07096b69e17175b3214d5f9464, the error does not occur.

2018-09-19 14:29 UTC, staubesv commented
H  @gregorydlogan & @lkiesow 

It seems that Travis is in trouble:

> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.5:install-node-and-npm (install node and npm) on project opencast-admin-ui: Could not extract the Node archive: Could not extract archive: '/home/travis/.m2/repository/com/github/eirslett/node/8.9.4/node-8.9.4-linux-x64.tar.gz': EOFException -> [Help 1]

I've manually restarted the build but the same error occurred again.

Could you please have a look at why Travis fails?

2018-09-24 14:30 UTC, staubesv commented
@KatrinIhler & @lkiesow Seems the ball is currently in your hands... Is there anything left that needs to be addressed?

2018-09-24 17:12 UTC, lkiesow commented
@staubesv, no idea until I take another look at this…

2018-09-24 21:09 UTC, lkiesow approved these changes

2018-09-24 21:10 UTC, merged