Skip publication channel to workspace operation if media package has no publication
opencast/opencast pull request #4485
Opened 2022-11-22 15:28 UTC by geichelberger

Check if the media package has a publication for the configured channel and skip instead of failing.
Contains a minor refactoring.

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2022-11-23 09:09 UTC, mliradelc requested changes

2022-11-23 09:09 UTC, mliradelc commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/PublicationChannelToWorkspace.java
> +          mediaPackage.getIdentifier(), publicationChannel);
```suggestion
      logger.warn("The media package '{}' contains no publications on channel '{}', skipping.",
          mediaPackage.getIdentifier(), publicationChannel);
```

I like this more  `warn` than `debug`, because if there is an error on the workflow, I want to be warned that the MP doesn't contain the media to be published.

2022-11-23 09:11 UTC, mliradelc commented
It is a nice PR, 

What is the difference between your PR and use `fail-on-error= false`

Anyway, the debug message is something that was missing, not knowing what match fail it is very exhausting.

2022-12-01 12:56 UTC, geichelberger commented
We have no rules on how a workflow operation should be implemented. For me, a workflow is only valid to fail if it throws a `WorkflowOperationException`, else it's just a programming error.

> What is the difference between your PR and use fail-on-error= false
You can not distinguish between a publication is not present, and an error is happening.

And having no publication is like trying to copy a flavor from the publication channel which is not present, which does not fail either.

2022-12-22 09:17 UTC, Arnei approved these changes
Code looks good to me and works as advertised.

I'm not sure whether it is better to skip or throw an error in case of an empty publication. However, I do agree that explicitly handling that case is an improvement regardless, so I'm inclined to approve this.

2022-12-23 20:06 UTC, merged