MH-13129 More Configuration Options For Thumbnails
opencast/opencast pull request #452
Opened 2018-09-26 14:09 UTC by krinnewitz

This PR consists of two commits. The first one adds the possibility to specify multiple encoding profiles to generate thumbnails in different qualities.

The second commit adds configuration options for the flavors to use when publishing to OAI-PMH and external API.

This work is sponsored by SWITCH.

2018-10-25 15:40 UTC, KatrinIhler requested changes
Alright, I tested this and I'm confused:
When I configure two thumbnail profiles for OAIPMH, there is only one thumbnail published when the initial workflow runs, but when I change the Thumbnail in the videoeditor, it correctly publishes two thumbnails to OAIPMH. Is this intended?

2018-10-25 15:40 UTC, KatrinIhler commented on etc/org.opencastproject.adminui.cfg
> +
I feel like the "thumbnail." prefix would make sense for all the configuration keys here since this is all thumbnail-specific, no?

2018-10-25 15:40 UTC, KatrinIhler commented on etc/org.opencastproject.adminui.cfg
> +#api.flavor=*/search+preview
Same here.

2018-10-25 15:40 UTC, KatrinIhler commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
> -   *          encoding properties
While you're at it, could you add a short description of the job parameter?

2018-10-25 15:40 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/ThumbnailImpl.java
> +    return downscaled.stream().map(a -> cloneAttachment(attachment, a.getURI())).collect(Collectors.toList());
Since the composerService can now return null, could this not result in a NullPointerException?

2018-10-25 15:40 UTC, KatrinIhler commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
>        @RestParameter(description = "The encoding profile to use", isRequired = true, name = "profileId", type = Type.STRING, defaultValue = "image-conversion.http") }, reponses = {
Shouldn't this also be updated?

2018-10-25 15:40 UTC, KatrinIhler commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
>        @RestResponse(description = "Results in an xml document containing the image attachment", responseCode = HttpServletResponse.SC_OK),
And this.

2018-10-25 15:40 UTC, KatrinIhler commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
>        logger.warn("Unable to convert image: " + e.getMessage());
and this.

2018-10-25 15:40 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/ThumbnailImpl.java
> +      return internalPublicationResult.getB().get(0);
I'm confused - why do you only return the first result here?

2018-10-25 15:40 UTC, KatrinIhler commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
> +        return null;
Is this wise? I would expect that if the convertImage() job doesn't return any results, there has gone something wrong.

2018-10-25 15:40 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/AdminUIConfiguration.java
> +    oaipmhProfiles = oaipmhProfilesStr.trim().isEmpty() ? new String[] {} : oaipmhProfilesStr.split(",");
Maybe use StringUtils.split here to split at both , and spaces?

2018-10-25 15:40 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/AdminUIConfiguration.java
> +    apiProfiles = apiProfilesStr.trim().isEmpty() ? new String[] {} : apiProfilesStr.split(",");
Same question here.

2018-10-25 15:40 UTC, KatrinIhler commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
>        return Response.status(Response.Status.BAD_REQUEST).entity("sourceImage and profileId must not be null").build();
And this.

2018-10-25 15:40 UTC, KatrinIhler commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
> +      List<Attachment> result = composerService.convertImageSync((Attachment) sourceImage, StringUtils.split(profileIds, ','));
resultS

2018-10-25 15:40 UTC, KatrinIhler commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/ThumbnailImpl.java
> +      return internalPublicationResult.getB().get(0);
Same question as above.

2018-10-25 15:45 UTC, staubesv commented
> When I configure two thumbnail profiles for OAIPMH, there is only one thumbnail published when the initial workflow runs, but when I change the Thumbnail in the videoeditor, it correctly publishes two thumbnails to OAIPMH. Is this intended?

Hi @KatrinIhler If an Adopter would publish more than one thumbnail, his workflow would already do that. With other words: The automatic publication needs to be configured in a way that is consistent of whatever workflows you have.

2018-10-26 06:38 UTC, KatrinIhler commented
@staubesv Yeah, that sounds reasonable. But maybe it could be made clearer that the configuration only applies to the automatic republication of thumbnails, not the initial publication?

And another thing I was thinking about (but that's not directly linked to this PR): Does it make sense to trigger the republication immediately after changing the thumbnail instead of waiting until the user hits Save in the video editor? If I change the thumbnail multiple times because I can't make up my mind, that would trigger republication multiple times.

2018-11-19 09:56 UTC, KatrinIhler commented
@krinnewitz This PR now has conflicts!

2018-11-19 09:59 UTC, staubesv commented
@krinnewitz & @KatrinIhler I am just about raising a new pull request that will replace this one.

2018-11-19 12:59 UTC, staubesv commented
I have just created #575 that replaces this PR...

@KatrinIhler Would be great if you could take the review of #575.

@krinnewitz Could you please close this PR?

2018-11-19 12:59 UTC, staubesv commented on etc/org.opencastproject.adminui.cfg
> +
Fixed in #575.

2018-11-19 13:00 UTC, staubesv commented on etc/org.opencastproject.adminui.cfg
> +#api.flavor=*/search+preview
Fixed in #575

2018-11-19 13:00 UTC, staubesv commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
> -   *          encoding properties
Just omitted in #575 as not related to the PR.

2018-11-19 13:00 UTC, staubesv commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/ThumbnailImpl.java
> +    return downscaled.stream().map(a -> cloneAttachment(attachment, a.getURI())).collect(Collectors.toList());
Fixed in #575 (composerService will not return null in #575).

2018-11-19 13:00 UTC, staubesv commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
>        @RestParameter(description = "The encoding profile to use", isRequired = true, name = "profileId", type = Type.STRING, defaultValue = "image-conversion.http") }, reponses = {
Fixed in #575

2018-11-19 13:00 UTC, staubesv commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/AdminUIConfiguration.java
> +    oaipmhProfiles = oaipmhProfilesStr.trim().isEmpty() ? new String[] {} : oaipmhProfilesStr.split(",");
Fixed in #575

2018-11-19 13:01 UTC, staubesv commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/AdminUIConfiguration.java
> +    apiProfiles = apiProfilesStr.trim().isEmpty() ? new String[] {} : apiProfilesStr.split(",");
Fixed in #575

2018-11-19 13:02 UTC, staubesv commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
>        return Response.status(Response.Status.BAD_REQUEST).entity("sourceImage and profileId must not be null").build();
Fixed in #575

2018-11-19 13:02 UTC, staubesv commented on modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
> +      List<Attachment> result = composerService.convertImageSync((Attachment) sourceImage, StringUtils.split(profileIds, ','));
Fixed in #575

2018-11-19 13:03 UTC, staubesv commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/ThumbnailImpl.java
> +      return internalPublicationResult.getB().get(0);
Added comment in #575

2018-11-19 13:04 UTC, staubesv commented
@KatrinIhler 

> When I configure two thumbnail profiles for OAIPMH, there is only one thumbnail published when the initial workflow runs, but when I change the Thumbnail in the videoeditor, it correctly publishes two thumbnails to OAIPMH. Is this intended?

Yes, it is. At the end of the day, this feature needs to be configured to match whatever the workflows produce. Meanwhile, there is quite some documentation available considering the configuration of this feature.

2018-11-19 13:06 UTC, staubesv commented
> And another thing I was thinking about (but that's not directly linked to this PR): Does it make sense to trigger the republication immediately after changing the thumbnail instead of waiting until the user hits Save in the video editor? If I change the thumbnail multiple times because I can't make up my mind, that would trigger republication multiple times.

The video editor is indeed inconsistent when it comes to the "Save" button: Some data is saved automatically (e.g. metadata changes, comments), some other data requires the user to press the "Save" button.
Probably needs to revision at some point of time, but that is not in scope of this PR.

2018-11-19 16:50 UTC, krinnewitz commented
Replaced by #575

2018-11-19 16:50 UTC, closed without merging