MH-13092: Fix failing scheduling for non-english browsers
opencast/opencast pull request #458
Opened 2018-09-30 20:00 UTC by mtneug

This should fix the scheduling problem in non-english browsers due to the recent usage of a moment.js version that includes locals.

2018-09-30 22:32 UTC, lkiesow commented
Note that this seems to break an admin-ui test. See Travis for details.

2018-10-04 09:56 UTC, KatrinIhler requested changes
I've confirmed that changing the locale of moment locally instead of globally fixes the scheduling bug, however this change breaks the behavior of the counters (see below) as well as some tests - I don't yet know why though.

![screenshot from 2018-10-04 11-33-27](https://user-images.githubusercontent.com/11960278/46466745-61087480-c7cc-11e8-9e93-021d05f344ad.png)

2018-10-04 15:45 UTC, mtneug commented
I found that instantiating `localeMoment` within the function body fixes the failing test, although I have not the slightest idea why.

2018-10-05 13:44 UTC, KatrinIhler approved these changes
I tested it again and now the test and the stats work. I'm not entirely sure why, but it works.

2018-10-05 13:45 UTC, merged