Adds the 'add-force-flavors' config to the publish-engage workflow
opencast/opencast pull request #4617
Opened 2023-01-23 12:57 UTC by marwyg

You can use this new configuration if the publish strategy 'merge' is activated. Elements with these flavors will be added to an existing publication without deleting or overwriting existing elements.

2023-01-23 15:05 UTC, marwyg commented
This is an example, how to add a 480p track, if there are already videos with 720p published.

```
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns="http://workflow.opencastproject.org">

  <id>add-480p-resolution-to-existing-publication</id>
  <title>Create 480p Video</title>
  <tags>
    <tag>archive</tag>
  </tags>
  <description>
     Creates a 480p Version of the existing publicated Videos.
  </description>

  <configuration_panel/>

  <operations>

    <operation
        id="publication-channel-to-workspace"
        description="Copy published 480p video to workspace">
      <configurations>
        <configuration key="source-channel">engage-player</configuration>
        <configuration key="source-tags">480p-quality</configuration>
        <configuration key="target-tags">republish</configuration>
      </configurations>
    </operation>

    <operation
        id="analyze-mediapackage"
        description="Check if 480p video exists.
        If it exists, all following operations will be skipped.">
      <configurations>
        <configuration key="source-tags">republish</configuration>
      </configurations>
    </operation>
    
    <operation
        id="publication-channel-to-workspace"
        if="NOT (${presenter_delivery_exists} OR ${presentation_delivery_exists})"
        description="Copy published 720p videos to workspace">
      <configurations>
        <configuration key="source-channel">engage-player</configuration>
        <configuration key="source-tags">720p-quality</configuration>
        <configuration key="target-tags">republish</configuration>
      </configurations>
    </operation>

    <operation
        id="tag"
        if="NOT (${presenter_delivery_exists} OR ${presentation_delivery_exists})"
        description="Remove engage-streaming, -download and the archive tag from published media">
      <configurations>
        <configuration key="source-tags">republish</configuration>
        <configuration key="target-tags">-engage-download,-engage-streaming,-archive</configuration>
      </configurations>
    </operation>

    <operation
        id="tag"
        if="NOT (${presenter_delivery_exists} OR ${presentation_delivery_exists})"
        description="Creating a work copy of 720p tracks">
      <configurations>
        <configuration key="source-tags">720p-quality</configuration>
        <configuration key="target-flavor">*/work</configuration>
        <configuration key="target-tags">work-copy</configuration>
        <configuration key="copy">true</configuration>
      </configurations>
    </operation>

    <operation
        id="encode"
        if="NOT (${presenter_delivery_exists} OR ${presentation_delivery_exists})"
        exception-handler-workflow="partial-error"
        description="Encoding work tracks to 480p format">
      <configurations>
        <configuration key="source-flavor">*/work</configuration>
        <configuration key="target-flavor">*/delivery</configuration>
        <configuration key="target-tags">480p-quality,engage-download,engage-streaming</configuration>
        <configuration key="encoding-profile">adaptive-480p.http</configuration>
      </configurations>
    </operation>

    <operation
        id="publish-engage"
        if="NOT (${presenter_delivery_exists} OR ${presentation_delivery_exists})"
        max-attempts="2"
        exception-handler-workflow="partial-error"
        description="Publishing to Opencast Media Module">
      <configurations>
        <configuration key="download-source-tags">engage-download</configuration>
        <configuration key="streaming-source-tags">engage-streaming</configuration>
        <configuration key="check-availability">false</configuration>
        <configuration key="strategy">merge</configuration>
        <configuration key="add-force-flavors">presenter/delivery,presentation/delivery</configuration>
      </configurations>
    </operation>

    <!-- post-publish stuff that has to be done -->

    <operation
        id="snapshot"
        if="NOT (${presenter_delivery_exists} OR ${presentation_delivery_exists})"
        description="Archive publishing information">
      <configurations>
        <configuration key="source-tags">archive</configuration>
      </configurations>
    </operation>

    <!-- Clean up work artifacts -->

    <operation
        id="cleanup"
        fail-on-error="false"
        description="Remove temporary processing artifacts">
      <configurations>
        <!-- On systems with shared workspace or working file repository -->
        <!-- you want to set this option to false. -->
        <configuration key="delete-external">true</configuration>
        <!-- ACLs are required again when working through ActiveMQ messages -->
        <configuration key="preserve-flavors">security/*</configuration>
      </configurations>
    </operation>

  </operations>

</definition>

```

2023-04-20 19:53 UTC, gregorydlogan commented
This looks reasonable to me, however the package locks all need to be removed prior to merge.

2023-04-20 19:53 UTC, gregorydlogan requested changes

2023-04-20 19:53 UTC, gregorydlogan commented on modules/engage-paella-player/package-lock.json
These all need to go

2023-09-29 09:18 UTC, KatrinIhler commented
@marwyg Any chance you can rebase this PR to get rid of the additional commits? If you don't have the time, maybe you can pawn this off to someone else...

2023-09-29 11:08 UTC, marwyg commented
@KatrinIhler Rebase done :)

2023-10-10 09:17 UTC, KatrinIhler commented on modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
> +              addForceFlavors);
Thanks for cleaning up the ugly switch-cases...

2023-10-10 09:23 UTC, KatrinIhler approved these changes

2023-10-10 09:23 UTC, KatrinIhler commented
Greg's concerns have been addressed, so I'm gonna go ahead and merge this.

2023-10-10 09:25 UTC, merged