Shows event Title on Paella 7 browser tab
opencast/opencast pull request #4717
Opened 2023-02-24 10:53 UTC by mliradelc

This little PR adds the title on Paella's 7 browser tab

@miesgre  This works but I don't know if is the best place to add it. I set up inside Opencast Plugin instead paella. Feel free to change it or close it if you think that an implementation in Paella 7 upstream would be more appropriate. 

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-02-24 16:48 UTC, miesgre commented
@mliradelc  I think it's not the best place, maybe you can move it to `modules/engage-paella-player-7/src/index.js` file before those lines:

https://github.com/opencast/opencast/blob/a84dd5f0fac4f9883c9c621c7b82e07c11f96a51/modules/engage-paella-player-7/src/index.js#L116-L120

something like:

```javascript
// Add event title to browser tab
document.title = data?.metadata?.title ?? 'Opencast - Unknown video title';

// Load stats 
....
```

2023-02-27 10:12 UTC, mliradelc commented
You are right, 
This is a dirty fix, yours have much more sense.

2023-02-27 11:12 UTC, mliradelc commented
@miesgre I applied your suggestion + I added the series title.

2023-02-27 13:39 UTC, miesgre requested changes

2023-02-27 13:39 UTC, miesgre commented on modules/engage-paella-player-7/src/index.js
> +    document.title =  videoTitle + ' - ' + seriesTitle + ' | Opencast';
const videoTitle = data?.metadata?.title ?? 'Unknown video title';
const seriesTitle = data?.metadata?.seriestitle ?? 'No series';
document.title = `${videoTitle} - ${seriesTitle} | Opencast`;

2023-02-28 08:51 UTC, miesgre approved these changes

2023-03-15 12:24 UTC, merged