Paella 7 matomo plugin
opencast/opencast pull request #4722
Opened 2023-02-28 10:33 UTC by miesgre

This PR  adds two new plugins:
- org.opencast.paella.matomo.userTrackingDataPlugin
  matomo usertracking plugin (will ask for cookie consent)

- org.opencast.paella.cookieconsent
  New button to modify the cookie consent

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-02-28 10:34 UTC, mliradelc commented
Thanks, I will review it!

2023-03-08 10:06 UTC, mliradelc requested changes
Works as expected. The cookie banner appears and is very complete.
Can you make some changes:
- Target branch from `develop` to `r/13.x`
- Add some documentation about this new feature

2023-03-08 10:06 UTC, mliradelc commented on etc/ui-config/mh_default_org/paella7/config.json
> +
Can you add a little description about this in Paella player 7 opencast documentation?

2023-03-09 12:15 UTC, miesgre commented
> Works as expected. The cookie banner appears and is very complete. Can you make some changes:
> 
> * Target branch from `develop` to `r/13.x`
> * Add some documentation about this new feature

Done.

2023-03-09 12:21 UTC, mliradelc approved these changes
Wonderful! Works as expected

2023-03-09 12:56 UTC, merged