Whisper language detection and tagging
opencast/opencast pull request #4770
Opened 2023-03-13 15:41 UTC by mliradelc

**Please Merge #4738 first!**

This PR enables Whisper automatic language code tagging in the way `lang:{code}` Where `code` is the language code using only two characters (es, en, de, it, etc...)

The Tag format comes from the proposal #4407 

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-03-15 03:19 UTC, gregorydlogan approved these changes
Reviewing just the follow-on commits which aren't already in #4738, LGTM.

2023-03-29 19:56 UTC, mliradelc commented
Add "Needs attention" tag, because this commit fixes whisper.

To the RM, add in the changelog:
> If you use whisper, update to the latest version

2023-03-29 20:11 UTC, mliradelc commented
Ready to merge, test files deleted

2023-04-05 15:42 UTC, Arnei requested changes

2023-04-05 15:42 UTC, Arnei commented on docs/guides/admin/docs/workflowoperationhandlers/speechtotext-woh.md
> + | translate          | no       | Transcription is translated into English (Whisper Only)                                                                                                 |
Could you list the accepted values for the `translate key`?

2023-04-05 15:42 UTC, Arnei commented on modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextEngine.java
>     * @return The generated subtitles file.
Since you changed the return type, you should change the return description as well

2023-04-05 15:42 UTC, Arnei commented on modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImpl.java
> +    Boolean translate = Boolean.parseBoolean(arguments.get(2));
`Boolean.parseBoolean()` does not throw an exception if you enter something other than "true", e.g. "yes" would result in `false`. Please use a parsing method that throws an exception for anything other than valid input strings (so for "true", "false" and the empty string I guess?).

2023-04-05 15:42 UTC, Arnei commented on modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/VoskEngine.java
> +    returnValues.put("language",language);
Would probably be nice if we could define "subFile" and "language" as constants somewhere

2023-04-05 15:42 UTC, Arnei commented on modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
> +        FileReader reader = new FileReader((preparedOutputFile.getParent() + "/" + mediaFile.getName() + ".json"));
Don't know how language detection works with whisper, but this does not work for me:
```
	2023-04-05 17:16:28,319 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'speechtotext':
org.opencastproject.speechtotext.api.SpeechToTextServiceException: Error while generating subtitle from http://localhost:8080/assets/assets/e838d659-d8c1-47a4-9868-4f42061b4d90/ed9a9e83-a295-41b7-88e9-efd922d1b06d/2/WasistChaos_flash9.mp4
	at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:168) ~[?:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opencastproject.speechtotext.api.SpeechToTextEngineException: java.io.FileNotFoundException: /home/arnewilken/IdeaProjects/opencast13-2/build/opencast-dist-develop-13-SNAPSHOT/data/opencast/workspace/collection/subtitles/WasistChaos_flash9.mp4.json (Datei oder Verzeichnis nicht gefunden)
	at org.opencastproject.speechtotext.impl.engine.WhisperEngine.generateSubtitlesFile(WhisperEngine.java:187) ~[?:?]
	at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:157) ~[?:?]
	... 6 more
Caused by: java.io.FileNotFoundException: /home/arnewilken/IdeaProjects/opencast13-2/build/opencast-dist-develop-13-SNAPSHOT/data/opencast/workspace/collection/subtitles/WasistChaos_flash9.mp4.json (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:112) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:60) ~[?:?]
	at org.opencastproject.speechtotext.impl.engine.WhisperEngine.generateSubtitlesFile(WhisperEngine.java:180) ~[?:?]
	at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:157) ~[?:?]
	... 6 more
```

2023-04-05 15:43 UTC, Arnei commented
If I have a german video and I want german and translated english subtitles, I have to run the operation twice to get both. Any change I could get both in one go? I have no idea if whisper allows this and it is probably not important. I just thought it would maybe be nice to save on processing power.

2023-04-05 15:44 UTC, Arnei commented
The translation is ... concise, I'll give it that :D

```
WEBVTT

00:00.000 --> 00:27.880
Erzliche willkommen zum Experiment der Woche. Bei den Begriffen Chaos oder Chaos-Vorschung denken viele wahrscheinlich an den
```

```
WEBVTT

00:00.000 --> 00:22.880
Music

00:24.000 --> 00:28.000
Welcome to experiment.
```

2023-04-05 18:53 UTC, merged

2023-04-06 03:16 UTC, gregorydlogan commented
Hah, so I missed @Arnei's review - the perils of working without a browser.  @mliradelc can you file a follow on PR to resolve these?

2023-04-06 07:26 UTC, mliradelc commented
No problems, I will do a follow-up with the review from @Arnei 

@Arnei, I saw your error,  I will check it, because the problem that you have Whisper looking for `filename.mp4.json` while the right is `filename.json`.  That was the problem with Whisper update. I will double-check that.