Paella 7: Allow to disable the cookie consent banner
opencast/opencast pull request #4782
Opened 2023-03-15 11:34 UTC by miesgre

### Your pull request should…

* [x] have a concise title
* [x] closes #4781 
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-03-27 15:25 UTC, mliradelc requested changes
Works as expected, thank you for the commit.

There is another doubt, can Termsfeed integrated into paella or opencast without calling it from their website? Is Termsfeed compatible with our license?

2023-03-27 15:25 UTC, mliradelc commented on etc/ui-config/mh_default_org/paella7/config.json
> +        },
Because TermsFeed is not into opencast, but is loaded from a third party service, this should be false by default.

Also, thinking about computers connected to a local network without internet access, they can't download the cookie consent

2023-03-27 15:45 UTC, miesgre commented on etc/ui-config/mh_default_org/paella7/config.json
> +        },
@mliradelc, In the TermsFeed cookie-consent web page (https://www.termsfeed.com/cookie-consent/) say it is free, but say nothing about the license. If its a problem. We can change it to another library.

The TermsFeed cookie-consent javascript library is added to the opencast bundle, so there will be no problem with computers without internet access. 

I will change the default to false.

2023-03-28 08:00 UTC, mliradelc commented on etc/ui-config/mh_default_org/paella7/config.json
> +        },
Thanks for the change made :) .  I just send mail to “Terms feed”, while they say  “Free”, there are many types of “Free” 

I hope they can answer

2023-03-28 09:24 UTC, mliradelc commented on etc/ui-config/mh_default_org/paella7/config.json
> +        },
I have news, terms feed had answered me, here it is:

```
Yes, you are allowed to use it regardless if the project is commercial or not. The only requirement is to keep the credits link / reference back to us.

We're working on having the license document soon as we're planning to launch the tool on Github.
```

So we are allowed to use it. I will talk about this in today's dev meeting. 😄

2023-03-29 08:10 UTC, mliradelc approved these changes
All good!

Thanks you for the PR!

2023-03-29 08:10 UTC, mliradelc commented on modules/engage-paella-player-7/public/watch.html
> +  <script type="text/javascript" src="cookie-consent/4.1.0/cookie-consent.js" charset="UTF-8"></script>
This was looking for, thanks for changing to a local JS 😄

2023-03-29 08:10 UTC, merged

2023-04-18 07:57 UTC, mliradelc commented
Only for documentation, TermsFeed answered me that we are allowed to use the code, here is the answer:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/8040628/232710648-b9b2dec4-0a97-4e6b-b11d-7cd81a360343.png">