Make Paella 7 Default
opencast/opencast pull request #4875
Opened 2023-04-20 11:33 UTC by lkiesow

This patch updates the default configuration to make Paella 7 the default player for Opencast 14. Paella 6 is still available though and adopters can easily switch back by changing a single configuration option.

This patch also adjust the automatic dependency updates. We argued that we could do half-tested updates for something that is in beta (and actually broke the player once or twice in that process), but we cannot do that for our default players.

Updates should be properly tested from now on and automated updates should go into `develop`.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-04-20 21:40 UTC, gregorydlogan approved these changes

2023-04-20 21:42 UTC, gregorydlogan commented
Note: This should probably have an entry in the release notes!

2023-04-20 22:35 UTC, lkiesow commented
This pull request already includes an entry for the release notes.

2023-04-20 23:09 UTC, gregorydlogan requested changes
Derp, missed the release note bit. Minor spelling issue.

2023-04-20 23:09 UTC, gregorydlogan commented on docs/guides/admin/docs/releasenotes/paella7.txt
> +- Paella 6 is still abailabe and can be configured
```suggestion
- Paella 6 is still available and can be configured
```

2023-04-25 10:28 UTC, lkiesow commented on docs/guides/admin/docs/releasenotes/paella7.txt
> +- Paella 6 is still abailabe and can be configured
Sorry, fixed.

2023-04-25 16:33 UTC, merged