Fix REST docs login problem
opencast/opencast pull request #4921
Opened 2023-04-25 18:18 UTC by lkiesow

The REST docs of Opencast have always been publicly available, but the recently added new admin interface seems to have broken this. Going to the REST docs overview page and not being logged in causes an empty page to be displayed.

This patch fixes the issue by moving from using jQuery to implementing the whole functionality in pure JavaScript which isn't really any harder with modern JavaScript.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-04-26 03:40 UTC, gregorydlogan requested changes
This fixes the first, landing layer.  But it doesn't fix the individual API endpoint page.  Suggestion:
```
diff --git a/modules/common/src/main/resources/ui/restdocs/template.xhtml b/modules/common/src/main/resources/ui/restdocs/template.xhtml
index a11e2e278e..e7ae5e340e 100644
--- a/modules/common/src/main/resources/ui/restdocs/template.xhtml
+++ b/modules/common/src/main/resources/ui/restdocs/template.xhtml
@@ -5,7 +5,7 @@
   <meta name=viewport content="width=device-width, initial-scale=1">
 
   <title>${meta.title} REST Documentation</title>
-  <link rel=stylesheet type=text/css href=docs.css />
+  <link rel=stylesheet type=text/css href=styles/rest_docs.css />
 </head>
 <body>
 <header class=center>
@@ -278,7 +278,7 @@
 
 <!-- JAVASCRIPT below here -->
 <script type=text/javascript src=js/jquery/dist/jquery.min.js></script>
-<script type=text/javascript src=docs.js></script>
+<script type=text/javascript src=scripts/docs.js></script>
 
 </body>
 </html>
```

'course that doesn't actually fix things either, since the testing forms don't work right...

2023-04-26 08:37 UTC, lkiesow commented
To track the second issue, I added https://github.com/opencast/opencast/issues/4922
I would leave this PR to fix the first part.

In the end, the files just need to be included in the `runtime-info-ui` module and copied to the correct place.

2023-04-26 08:50 UTC, Arnei approved these changes
While it does not fix the whole rest docs issue, it fixes the part it says it does. Code looks good too.

2023-04-26 08:52 UTC, Arnei commented
I'm also taking a look at #4922 right now. I don't hink making `docs.js` independent from jquery works in that case, as it uses jquery forms and I don't know how to replace those easily. So I'm currently looking at why it can't find the jquery.min.js anymore.

2023-04-26 16:16 UTC, gregorydlogan commented
https://github.com/opencast/opencast/pull/4928 fully fixes things, yay!

2023-04-27 21:34 UTC, lkiesow commented
I would still like to see this merged oven if jQuery reappears somewhere.
Less dependencies are good.

2023-05-02 16:29 UTC, merged