Update Paella 7 default theme
opencast/opencast pull request #4943
Opened 2023-05-04 11:25 UTC by miesgre

This is the result of the work done with ETHZ in design and accessibility. 

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-05-08 09:04 UTC, mliradelc requested changes
Hi Miguel, thanks for the PR, the new design is awesome and is much moderner than the original. Also, the colors now are in harmony with the rest of the UI.

Now we have found a little visual bug:

<img width="374" alt="Screenshot 2023-05-08 at 08 50 22" src="https://user-images.githubusercontent.com/8040628/236764278-c729ea6c-9cc6-4935-9023-301a03254227.png">

The forward and backward icons are not aligned with the other buttons.

<img width="374" alt="Screenshot 2023-05-08 at 09 02 20" src="https://user-images.githubusercontent.com/8040628/236765213-39ec3d12-80a7-4011-9781-5f829d7db50e.png">

When you highlight the buttons, the difference is bigger, making an unpleasant to sight.

2023-05-08 09:04 UTC, mliradelc commented on modules/engage-paella-player-7/src/icons/forward-icon.svg
You have the backward icon without number, why this SVG uses number (or the number is by default?)?

2023-05-08 09:09 UTC, miesgre commented on modules/engage-paella-player-7/src/icons/forward-icon.svg
The text is not important. It is replaced in paella plugins by the time configured in the plugins. The text in the svg is only used in the editor to check the position.

2023-05-08 09:24 UTC, miesgre commented
> Hi Miguel, thanks for the PR, the new design is awesome and is much moderner than the original. Also, the colors now are in harmony with the rest of the UI.
> 
> Now we have found a little visual bug:
> 
> <img alt="Screenshot 2023-05-08 at 08 50 22" width="374" src="https://user-images.githubusercontent.com/8040628/236764278-c729ea6c-9cc6-4935-9023-301a03254227.png">
> 
> The forward and backward icons are not aligned with the other buttons.
> 
> <img alt="Screenshot 2023-05-08 at 09 02 20" width="374" src="https://user-images.githubusercontent.com/8040628/236765213-39ec3d12-80a7-4011-9781-5f829d7db50e.png">
> 
> When you highlight the buttons, the difference is bigger, making an unpleasant to sight.

It's not a bug, it is done intentionally. ETHZ wanted it like this.
Check this: https://github.com/polimediaupv/paella-ethz/issues/13#issuecomment-1445463260

This is something that can be changed in CSS. Just change the `margin-top` property of these plugins:

Add this to `etc/ui-config/mh_default_org/paella7/custom_theme.css`
```css
.playback-bar .button-plugins .button-plugin-container button[name="es.upv.paella.backwardButtonPlugin"] div{
    margin-top: 0;
}

.playback-bar .button-plugins .button-plugin-container button[name="es.upv.paella.forwardButtonPlugin"] div{
    margin-top: 0;
}
```

2023-05-09 09:33 UTC, mliradelc commented
In that case I think is ok.

Have you tried with a touch screen?

2023-05-09 10:18 UTC, miesgre commented
> In that case I think is ok.
> 
> Have you tried with a touch screen?

We tested in mobile and iPad

2023-05-09 10:52 UTC, mliradelc commented
> > In that case I think is ok.
> > Have you tried with a touch screen?
> 
> We tested in mobile and iPad

Wonderful! In that case for me is approved.

2023-05-09 10:56 UTC, mliradelc approved these changes
Works as intended, and the design questions were answered.

Wait for the dev meeting, if there are no objection. Should me merged before r/14.x

Pinging @wsmirnow and @stefanosgeo to take into account this PR before the branch cut

2023-05-10 12:17 UTC, merged

2023-05-10 16:45 UTC, oas777 commented
Thanks Max for your review - and the comment about the horizontal alignment. As Miguel indicated, we looked at the other option which was not ideal either. Also, I should mention that there will be a "final design review" of Tobira and Paella, so maybe we follow your suggestion after all.

2023-05-11 06:25 UTC, mliradelc commented
Hi Olaf, thank you for your answer. Marcello here at cologne has suggested me this media icon's collection https://github.com/vidstack/media-icons the best, it has MIT license.

Maybe the rollback (forward) design can improve the alignment. Nevertheless, I think right now is a good job and a step forward to a better player UI.

2023-05-15 07:53 UTC, oas777 commented
Thanks for the pointer, but we already decided on the icons 
- https://github.com/feathericons/feather#feather and
- https://v1.heroicons.com/,
both with a MIT licence. And given we aligned them for Paella and Tobira, it's not easy to simply switch...

2023-05-15 08:26 UTC, mliradelc commented
No worries, now with the new Skins options in paella, if any wants other type of icons can change it. 😄