Turn Paella 6 into a plugin
opencast/opencast pull request #4965
Opened 2023-05-21 09:12 UTC by lkiesow

This patch turns the version 6 of the Paella Player included in Opencast into an optional plugin.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-06-02 12:32 UTC, Arnei requested changes
Should probably make mention of this change in the docs:?
General plugin list: https://docs.opencast.org/develop/admin/#modules/plugin-management/
Paella Player 6: https://docs.opencast.org/develop/admin/#modules/paella.player/configuration/#paella-player-6

Makes sense and works in my local installation.

2023-06-02 12:32 UTC, Arnei commented on etc/org.opencastproject.organization-mh_default_org.cfg
> +# Default: /paella7/ui/watch.html?id=#{id}    ← requires plugin
Isn't that the path for Paella 7, which is not a plugin? Did you mean for this comment to go on line 181 instead?

2023-06-27 17:29 UTC, lkiesow commented on etc/org.opencastproject.organization-mh_default_org.cfg
> +# Default: /paella7/ui/watch.html?id=#{id}    ← requires plugin
Correct. Fixed.

2023-06-27 17:36 UTC, lkiesow commented
Updated the docs and fixed the hint in the organization configuration file.

2023-06-28 06:21 UTC, Arnei approved these changes

2023-06-28 06:21 UTC, merged