Switch to Opensearch by default
opencast/opencast pull request #5037
Opened 2023-06-12 20:09 UTC by gregorydlogan

This PR alters the debian documentation to install opensearch over elasticsearch.  Elasticsearch will still work, but new installs should prefer opensearch in the absense of an existing ES install.

### Your pull request should…

* [x] have a concise title
* [ ] ~[close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-06-12 20:10 UTC, gregorydlogan commented
@lkiesow @mtneug Looks like the RPM and Docker docs/setups need updating still?

2023-06-13 08:01 UTC, mtneug requested changes

2023-06-13 08:01 UTC, mtneug commented on docs/guides/admin/docs/installation/debs.md
> +Install Opensearch
Only because this usually really annoys Opencast devs: it is actually written OpenSearch (big S) 😉

2023-06-13 08:03 UTC, mtneug commented
Docker docs don't mention Elasticsearch, but there are a couple of other places when I search for it. Also, should we rename config keys / class names (see https://docs.opencast.org/r/14.x/admin/#configuration/elasticsearch/)?

2023-06-13 13:31 UTC, gregorydlogan commented on docs/guides/admin/docs/installation/debs.md
> +Install Opensearch
Oh for the love of...

This an fFmPeG gets me every time haha

2023-06-13 13:32 UTC, gregorydlogan commented
> Docker docs don't mention Elasticsearch, but there are a couple of other places when I search for it. Also, should we rename config keys / class names (see https://docs.opencast.org/r/14.x/admin/#configuration/elasticsearch/)?

Will check and see for the other places that aren't RPM docs.

Renaming config keys was not done for compat reasons. When we drop ES support entirely I think a rename is worth it.

2023-06-28 03:43 UTC, merged