Alter License Header
opencast/opencast pull request #5120
Opened 2023-07-19 21:54 UTC by gregorydlogan

This PR alters the license header so that it's not Javadocs anymore.  Since this will _doubtlessly_ end up with conflicts, here's the regex I used to make this:

`find ./ -type f -name *.java -exec sed -i '0,/\/\*\*/{s/\/\*\*/\/\*/}' "{}" \;`

### Your pull request should…

* [x] have a concise title
* [ ] ~[close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-07-20 08:58 UTC, ziegenberg requested changes

2023-07-20 08:58 UTC, ziegenberg commented on modules/admin-ui-frontend/app/styles/vendor/bourbon/css3/_background-image.scss
wanna correct this one?

2023-07-20 08:58 UTC, ziegenberg commented on modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/query/package-info.java
this also needs correction.

2023-07-20 08:58 UTC, ziegenberg commented on modules/capture-admin-service-api/src/main/java/org/opencastproject/capture/admin/api/package-info.java
This needs an update.

2023-07-20 08:58 UTC, ziegenberg commented on modules/common/src/main/java/org/opencastproject/serviceregistry/api/package-info.java
This needs an update.

2023-07-20 08:58 UTC, ziegenberg commented on modules/common/src/main/java/org/opencastproject/util/package-info.java
This needs an update.

2023-07-20 17:22 UTC, ziegenberg commented
I'm only half way through the changes ... Hopefully will have time to check the others too

2023-07-25 15:48 UTC, ziegenberg commented on modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/package-info.java
> -/**
This has the wrong license header and the documentation.

2023-07-25 15:49 UTC, ziegenberg commented on modules/composer-service-api/src/main/java/org/opencastproject/composer/layout/package-info.java
> -/**
This was not a license header.

2023-07-25 15:49 UTC, ziegenberg commented on modules/distribution-service-api/src/main/java/org/opencastproject/distribution/api/package-info.java
> -/**
This was not a license header.

2023-07-25 15:50 UTC, ziegenberg commented on modules/distribution-service-download/src/main/java/org/opencastproject/distribution/download/package-info.java
> -/**
This was not a license header.

2023-07-25 15:51 UTC, ziegenberg commented on modules/ingest-service-impl/src/test/java/org/apache/commons/fileupload/MockHttpServletRequest.java
> -/**
This should probably not be modified.

2023-07-25 15:51 UTC, ziegenberg commented on modules/search-service-api/src/main/java/org/opencastproject/search/api/package-info.java
> -/**
This was not a license header.

2023-07-25 15:51 UTC, ziegenberg commented on modules/search-service-impl/src/main/java/org/opencastproject/search/impl/package-info.java
> -/**
This was not a license header.

2023-07-25 15:53 UTC, ziegenberg commented on modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/package-info.java
> -/**
This was not a license header.

2023-07-25 15:53 UTC, ziegenberg commented on modules/series-service-api/src/main/java/org/opencastproject/series/api/package-info.java
> -/**
This was not a license header.

Also, I like the lonely "TODO" in here ;)

2023-07-25 15:54 UTC, ziegenberg commented on modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/package-info.java
> -/**
This was not a license header.

2023-07-25 15:54 UTC, ziegenberg commented on modules/series-service-impl/src/main/java/org/opencastproject/series/impl/package-info.java
> -/**
This was not a license header.

2023-07-25 15:55 UTC, ziegenberg commented on modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/package-info.java
> -/**
This was not a license header.

2023-07-25 15:59 UTC, ziegenberg commented
Before the comments even more, you might wanna look into the following files:

```
modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/package-info.java
modules/composer-service-api/src/main/java/org/opencastproject/composer/layout/package-info.java
modules/distribution-service-api/src/main/java/org/opencastproject/distribution/api/package-info.java
modules/distribution-service-download/src/main/java/org/opencastproject/distribution/download/package-info.java
modules/ingest-service-impl/src/test/java/org/apache/commons/fileupload/MockHttpServletRequest.java
modules/search-service-api/src/main/java/org/opencastproject/search/api/package-info.java
modules/search-service-impl/src/main/java/org/opencastproject/search/impl/package-info.java
modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/package-info.java
modules/series-service-api/src/main/java/org/opencastproject/series/api/package-info.java
modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/package-info.java
modules/series-service-impl/src/main/java/org/opencastproject/series/impl/package-info.java
modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/package-info.java
modules/static-file-service-api/src/test/java/org/apache/commons/fileupload/MockHttpServletRequest.java
modules/statistics-provider-influx/src/main/java/org/opencastproject/statistics/provider/influx/package-info.java
modules/statistics-service-api/src/main/java/org/opencastproject/statistics/api/package-info.java
modules/statistics-service-impl/src/main/java/org/opencastproject/statistics/endpoint/package-info.java
modules/statistics-service-impl/src/main/java/org/opencastproject/statistics/impl/package-info.java
modules/usertracking-api/src/main/java/org/opencastproject/usertracking/api/package-info.java
modules/usertracking-impl/src/main/java/org/opencastproject/usertracking/endpoint/package-info.java
modules/usertracking-impl/src/main/java/org/opencastproject/usertracking/impl/package-info.java
modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/package-info.java
modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/endpoint/package-info.java
modules/workspace-api/src/main/java/org/opencastproject/workspace/api/package-info.java
```

2023-07-25 16:32 UTC, gregorydlogan commented
Current comments addressed.  There are a bunch more package-info files without headers which will be addressed shortly.

2023-07-25 17:09 UTC, ziegenberg commented on modules/series-service-impl/src/main/java/org/opencastproject/series/impl/package-info.java
> + /*
This was a JavaDoc before. Is it on purpose to demote it to a regular comment? See also the other package-info classes.

2023-07-25 17:56 UTC, gregorydlogan commented on modules/series-service-impl/src/main/java/org/opencastproject/series/impl/package-info.java
> + /*
Yep, the goal is to convert all of these into regular comments.  If there are some missing, or some which are still javadocs please point them out

2023-07-25 18:36 UTC, ziegenberg commented on modules/series-service-impl/src/main/java/org/opencastproject/series/impl/package-info.java
> + /*
I'm not talking about the license header but the JavaDoc directly above the `package Xxxxxx;` line. Just to be sure, we're talking about the same thing...


> Yep, the goal is to convert all of these into regular comments. If there are some missing, or some which are still javadocs please point them out

In this case, the following files also need to be changed:

```
modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/query/package-info.java
modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/package-info.java
modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/package-info.java
modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/package-info.java
modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/package-info.java
modules/capture-admin-service-api/src/main/java/org/opencastproject/capture/admin/api/package-info.java:
modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/endpoint/package-info.java
modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/impl/package-info.java
modules/common/src/main/java/org/opencastproject/serviceregistry/api/package-info.java
modules/common/src/main/java/org/opencastproject/util/package-info.java
```

2023-07-28 18:33 UTC, gregorydlogan commented
@ziegenberg ok, think I've got it all this time.  Went through the diff manually locally (so much faster than GH) and the remaining changes *should* be just the header bits.

2023-07-31 06:54 UTC, ziegenberg approved these changes
This looks good now. Ready to merge :)

2023-07-31 07:03 UTC, merged