Fix broken JAR (zip) files
opencast/opencast pull request #5157
Opened 2023-08-07 10:18 UTC by lkiesow

This ensures that our JAR files are actually valid zip files since we seem to have broken files headers in several releases and this is causing issues with recent JVM updates.

This is not a very nice fix, but it should do the trick. It seems like Opencast 15 no longer suffers from this bug. We can probably remove this workaround in that branch. Though I would maybe keep the integrity test around for a bit longer.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-08-07 12:02 UTC, ziegenberg requested changes
I guess it looks fine, just a minor suggestion. Would be nice to have others' approval too.

2023-08-07 12:02 UTC, ziegenberg commented on .github/fix-jars
> +    if ! zip --test "$i" &> /dev/null
ShellCheck says: In POSIX sh, `&>` is undefined. Use the long form instead of the shorthand:
```suggestion
    if ! zip --test "$i" > /dev/null 2>&1
```

`&>` is a bash and ksh extension for redirecting both stdout and stderr. In dash and POSIX sh, use `2>&1` explicitly.

2023-08-07 12:02 UTC, ziegenberg commented on .github/fix-jars
> +      zip -r --compression-method store fix.zip *
Using `./*glob*` looks a bit safer.

```suggestion
      zip -r --compression-method store fix.zip ./*
```

2023-08-07 12:02 UTC, ziegenberg commented on .github/fix-jars
> +  find . -name '*jar' | while read i
ShellCheck says: `read` without `-r` will mangle backslashes.


```suggestion
  find . -name '*jar' | while read -r i
```

2023-08-07 12:02 UTC, ziegenberg commented on .github/fix-jars
`fix-jars` does what says it should do. Run it locally to verify.

2023-08-07 12:02 UTC, ziegenberg commented on .github/test-jars
> +find build/opencast-*/system/org/opencastproject -name '*.jar' | while read jarfile
ShellCheck says: `read` without `-r` will mangle backslashes.
```suggestion
find build/opencast-*/system/org/opencastproject -name '*.jar' | while read -r jarfile
```

2023-08-07 12:02 UTC, ziegenberg commented on .github/test-jars
`test-jars` does what says it should do. Run it locally to verify.

2023-08-07 14:42 UTC, lkiesow commented
Thanks for the review. Applied all changes.

2023-08-07 15:09 UTC, ziegenberg commented
Maybe PR #5158 makes this obsolete?

2023-08-07 16:22 UTC, ziegenberg approved these changes

2023-08-08 11:52 UTC, ziegenberg commented
@lkiesow As most certainly #5158 will find it's into the codebase I suggest throwing `github/fix-jars` overboard and just keeping the verify integrity bits. That shouldn't hurt us and might prevent this from happening again in the future.

2023-08-10 18:10 UTC, lkiesow commented
> @lkiesow As most certainly #5158 will find it's into the codebase I suggest throwing `github/fix-jars` overboard and just keeping the verify integrity bits. That shouldn't hurt us and might prevent this from happening again in the future.

Done. This pull request now just contains the test. Nothing else. Can you do the review/merge?

2023-08-10 23:14 UTC, ziegenberg approved these changes

2023-08-10 23:15 UTC, ziegenberg commented
Looks good to me

2023-08-10 23:15 UTC, merged

2023-10-25 14:56 UTC, JamesUoM commented
As java use to happily parse these jar files in the previous point release it is considered a bug that has been fixed in 11 and 17 https://bugs.openjdk.org/browse/JDK-8313765