MH-13191 Improve performance of event deletion
opencast/opencast pull request #524
Opened 2018-10-25 12:05 UTC by krinnewitz

The AssetManager used to "manually" control the relation between
snapshots and assets. I.e. assets actually have references to snapshots,
but this relationship was only handled on application level. On database
level, there was not explicitly declared relationship between assets and
snapshots.

So when deleting snapshots, the AssetManager had to first figure out,
which snapshots were going to be deleted by the given query and then
"manually" remove all assets referencing the snapshots to be deleted,
before actually deleting the snapshots.

With this patch, the relationship between assets and snapshots is
modeled explicitly on the database level by changing the shema
accordingly. This allows for ON DELETE CASCADE to be used resulting in
only one query being necessary when removing snapshots.

This work is sponsored by SWITCH.

2018-10-29 15:45 UTC, KatrinIhler requested changes
I tested the migration script first and that didn't work for me, but it's possible that I skipped another necessary upgrade step before. When I deleted all tables and recreated them with the other script, it worked fine for me.

2018-10-29 15:45 UTC, KatrinIhler commented on docs/guides/admin/docs/upgrade.md
> +As part of performance optimizations, a foreign key constraint was added to one table. This requires an database schema
'a' instead of 'an'

2018-10-29 15:45 UTC, KatrinIhler commented on docs/guides/admin/docs/upgrade.md
> +update. As with all database migrations, we recommend to make a database backup before attempting the upgrade.
'do' instead of 'make'?

2018-10-29 15:45 UTC, KatrinIhler commented on docs/guides/admin/docs/upgrade.md
> +You can find the database upgrade script in `docs/upgrade/6_to_7/`. This script is suitable for both, MariaDB, and
"for both MariaDB and MySQL" without the ,

2018-10-29 16:11 UTC, krinnewitz commented
Thanks @KatrinIhler. Which database have you tried? mysql or MariaDB? What error message did you get?

2018-10-30 09:12 UTC, KatrinIhler approved these changes
@krinnewitz I use MariaDB. But I just tested this again by deleting all tables, recreating them with the script for 6 and then using the migration script from 6 to 7 and this time it worked, so it was probably my setup from before that was wonky. Lets get to merging! :)

2018-10-30 09:13 UTC, merged