MH-13194 wrong description for endpoint
opencast/opencast pull request #532
Opened 2018-10-30 11:00 UTC by tyfranck

Corrected 'mediapackage' description for /ingest/{wdID} REST endpoint

2018-10-30 13:26 UTC, KatrinIhler requested changes
Definitely a good idea to fix this. The merge commit confuses me though, why is that in here (especially since it doesn't seem to contribute anything)?

2018-10-30 13:26 UTC, KatrinIhler commented on modules/matterhorn-ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
> +  @RestQuery(name = "ingest", description = "Ingest the completed media package into the system, retrieving all URL-referenced files, and starting a specified workflow", pathParameters = { @RestParam
Would you mind removing the 'given' to make it consistent with /ingest without a workflow id?

2018-10-30 14:16 UTC, tyfranck commented on modules/matterhorn-ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
> +  @RestQuery(name = "ingest", description = "Ingest the completed media package into the system, retrieving all URL-referenced files, and starting a specified workflow", pathParameters = { @RestParam
Does your comment about this not contributing to anything related to this pull request or the previous one I closed?

2018-10-30 14:59 UTC, KatrinIhler commented on modules/matterhorn-ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
> +  @RestQuery(name = "ingest", description = "Ingest the completed media package into the system, retrieving all URL-referenced files, and starting a specified workflow", pathParameters = { @RestParam
I'm specifically talking about the first of the two commits "Merge pull request #4 from opencast/r/4.x" - why is that here? What does it do?

2018-11-16 20:29 UTC, lkiesow commented
The changes itself look just fine. @tyfranck, do you mind if we just squash-merge this? That will automatically drop the additional merge commits in here. I guess that would be okay with you as well, @KatrinIhler?

2018-11-19 08:54 UTC, KatrinIhler commented
@lkiesow Sounds good to me, but Github tells me that squash & merge is not enabled for this repository, so how do we do this?

2018-11-19 08:57 UTC, tyfranck commented
Please go ahead. I've found a way to avoid those extra commits. So next time will be a cleaner one... :-)

2018-11-19 09:16 UTC, merged

2018-11-19 09:17 UTC, lkiesow commented
@KatrinIhler, found a way to do that.
Sometimes, being an admin helps ;-)