MH-13127: Make table headers non-interactive by default
opencast/opencast pull request #534
Opened 2018-10-30 18:13 UTC by jaysuz

This will ensure that only table headers with a corresponding _sort by_ action are styled to be interactive.

**Before**
![before](https://user-images.githubusercontent.com/16406401/47740251-9c854a00-dc77-11e8-891f-733f93c58d6d.gif)

**After**
![after](https://user-images.githubusercontent.com/16406401/47740272-a6a74880-dc77-11e8-8f40-fc0ac53e11d3.gif)

Resolves: [MH-13127](https://opencast.jira.com/browse/MH-13127)

2018-11-06 14:25 UTC, KatrinIhler requested changes
Looks good, just one thing:

2018-11-06 14:25 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/configuration/controllers/themesController.js
>               * Temporarily disabled
While you're at it, could you rip out that old, commented code instead of changing it? This has been here for three years for example and is unlikely to ever being used again.

2018-11-06 14:25 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/recordings/controllers/recordingsController.js
>          //}, {
Same here.

2018-11-06 14:25 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/jobsController.js
>          //}, {
And here.

2018-11-06 14:25 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/serversController.js
>          //}, {
And here.

2018-11-06 14:25 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/aclsController.js
>          //}, {
And here.

2018-11-06 14:25 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/usersController.js
>        }, {
And here.

2018-11-06 14:58 UTC, staubesv commented
@KatrinIhler This pull request is not about removing commented code and we would generally recommend to create separate pull requests for code cleanup stuff. In particular, a cleanup pull request following best practises does not just remove unused code from the file currently being worked on but rather removes related code across the whole code base. 
Seem from that point of view, it makes sense to adapt the unused code so that it is at least "up-to-date". 

Agree, though, that it would make sense to remove unused code. But preferably in a separate PR that removes all of the unused code related to one unused feature (incl. backend).

2018-11-06 16:12 UTC, KatrinIhler commented
@staubesv As already discussed in the Technical Meeting, we don't quite agree on this (I would prefer to remove unfinished features completely as well, but I'll take deleting some dead code over none any day), but I'll merge this as is for now and hopefully we can get rid of at least one dead feature by the end of the year.

2018-11-06 16:12 UTC, KatrinIhler approved these changes

2018-11-06 16:13 UTC, merged

2018-11-06 20:04 UTC, staubesv commented
@KatrinIhler I will take care of removing at least one unfinished feature completed across the codebase until end of year. Promised.

2018-11-07 07:24 UTC, KatrinIhler commented
@staubesv Sounds good!