Update Youtube Publication documentation
opencast/opencast pull request #5348
Opened 2023-10-19 13:32 UTC by Arnei

The documentation for publishing to youtube is a bit outdated. I tried updating it based on my experiences with setting it up.

2023-10-23 08:25 UTC, mliradelc approved these changes
I asked another user to try this new configuration, first time he tried to configure Opencast with YouTube. He answered me that the new documentation works.

I validate this documentation.

2023-10-23 08:27 UTC, JulianKniephoff requested changes
I haven't tested it yet, but here are some nitpicks already. 😅

2023-10-23 08:27 UTC, JulianKniephoff commented on docs/guides/admin/docs/modules/youtubepublication.md
> +Opencast can now publish to YouTube. To make use of this, add the [Publish Youtube workflow operation](../workflowoperationhandlers/publish-youtube-woh.md)
```suggestion
Opencast can now publish to YouTube. To make use of this, add the [Publish YouTube workflow operation](../workflowoperationhandlers/publish-youtube-woh.md)
```

2023-10-23 08:27 UTC, JulianKniephoff commented on docs/guides/admin/docs/modules/youtubepublication.md
> +You may also want to add the [Retract Youtube workflow operation](../workflowoperationhandlers/retract-youtube-woh.md)
```suggestion
You may also want to add the [Retract YouTube workflow operation](../workflowoperationhandlers/retract-youtube-woh.md) 
```

2023-10-23 08:27 UTC, JulianKniephoff commented on docs/guides/admin/docs/modules/youtubepublication.md
> +In general, it should be placed near your other `publish` operations.
I'm not sure what you mean by this. Don't all workflow definitions have to live in `etc/workflows`? 🤔

2023-10-23 08:27 UTC, JulianKniephoff commented on docs/guides/admin/docs/modules/youtubepublication.md
> +near your `retract` operations.
See above.

2023-10-23 08:31 UTC, mliradelc commented on docs/guides/admin/docs/modules/youtubepublication.md
> +In general, it should be placed near your other `publish` operations.
Indeed, but he is not talking about the `file` location but rather from inside the workflow. Place the step to publish next to the other publish steps in your workflow.

2023-10-23 08:34 UTC, JulianKniephoff commented on docs/guides/admin/docs/modules/youtubepublication.md
> +In general, it should be placed near your other `publish` operations.
Oh yeah, my bad! 🙈

2023-10-23 14:59 UTC, JulianKniephoff requested changes
Found some minor issues with the docs while trying to follow them, still.

In addition to the inline comments, I ran into the trap that you need to add a test user in the "Configure the API Consent Screen" step when your app is still in testing mode. Otherwise you get an "access denied" in the verification step. Maybe we should hint at this. 🤷‍♀️ 

I also think that the two restarts in the guide aren't actually necessary, so maybe get rid of those as well?

2023-10-23 14:59 UTC, JulianKniephoff commented on docs/guides/admin/docs/modules/youtubepublication.md
> +  - Fill in the rest of the required settings at discretion
These do not show up as indented in the rendered docs which confused me just now. 🤔

2023-10-23 14:59 UTC, JulianKniephoff commented on docs/guides/admin/docs/modules/youtubepublication.md
> +  - **Application type** must be set to `Desktop`
Same here.

2023-10-24 16:26 UTC, ziegenberg commented on docs/guides/admin/docs/modules/youtubepublication.md
> +  - Fill in the rest of the required settings at discretion
This probably needs four spaces of indentation. See line 38 in this file

2023-10-25 07:59 UTC, Arnei commented on docs/guides/admin/docs/modules/youtubepublication.md
> +  - Fill in the rest of the required settings at discretion
Thanks for catching this.

2023-10-25 08:00 UTC, Arnei commented
> I also think that the two restarts in the guide aren't actually necessary, so maybe get rid of those as well?

Did you successfully set this up without restarting?

2023-10-26 12:14 UTC, JulianKniephoff commented
Yes I did. The URL that is mentioned just appears in the log and you can continue to use Opencast even before going through that.

However, it **is** true that if you (re-)start Opencast without having completed that step, stuff won't start up correctly. 🤔

2023-10-26 12:18 UTC, JulianKniephoff requested changes
I think ~~the last commit~~ 3b63b7aa127b670c265435f0f563b2d1a704fb9d includes some accidental config changes.

2023-10-28 05:20 UTC, merged