Youtube-Publication: Throw explicit error if client_secret is malformed
opencast/opencast pull request #5349
Opened 2023-10-19 14:22 UTC by Arnei

Parsing of the client_secret.json may go wrong, but currently the stack trace is not very helpful in making clear when that happens. This should help.

2023-10-23 12:03 UTC, JulianKniephoff requested changes, later dismissed

2023-10-23 12:03 UTC, JulianKniephoff commented on modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/YouTubeV3PublicationServiceImpl.java
> +    logger.debug("Activated Youtube Publication Service");
```suggestion
    logger.debug("Activated YouTube Publication Service");
```

2023-10-23 12:03 UTC, JulianKniephoff commented on modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/auth/ClientCredentials.java
> +      throw new IOException("client_secret file does not contain \"installed\" as a top level key. Did you set the "
Not sure if `IOException` is the right thing to throw here. I would say in this context `IllegalArgumentException` would be more appropriate (since the given `File` argument doesn't have the necessary structure) or **maybe** `java.text.ParseException`. (**Note**, this is not the `ParseException` that's already imported by this file.) Because the `File` can't be parsed into the format needed to extract the thing. (From this POV it's not just JSON, but JSON with a "schema" if you will.)

2023-10-23 12:03 UTC, JulianKniephoff commented on modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/auth/ClientCredentials.java
> +      throw new IOException("client_secret file does not contain \"client_id\".");
See above.

2023-10-23 12:03 UTC, JulianKniephoff commented on modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/auth/ClientCredentials.java
>      return (String) array.get("client_id");
Note that the JavaDoc is kinda sorta lying now.

2023-10-23 14:55 UTC, JulianKniephoff commented
Was able to test this by now as well and it seemed to work. 👌

2023-10-25 08:28 UTC, Arnei commented on modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/auth/ClientCredentials.java
> +      throw new IOException("client_secret file does not contain \"installed\" as a top level key. Did you set the "
Fair point, caught me being lazy about exceptions types there.

2023-10-27 09:24 UTC, KatrinIhler approved these changes
I'm not 100% happy with the IllegalArgumentException, but having two different ParseExceptions is also weird and this does the job. So LGTM.

2023-10-27 09:24 UTC, merged