YT-Publish WOH: Fail more aggressively
opencast/opencast pull request #5350
Opened 2023-10-19 14:36 UTC by Arnei

Currently the Youtube Publish WOH is a bit meek, often only logging little warnings when it fails to publish. This makes the WOH more assertive by having it throw exceptions instead, properly failing the workflow.

2023-10-23 12:10 UTC, JulianKniephoff approved these changes
Code lgtm. Will try to get a test in later as well.

2023-10-23 14:40 UTC, JulianKniephoff approved these changes

2023-10-23 14:40 UTC, JulianKniephoff commented on modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishYouTubeWorkflowOperationHandler.java
> +        throw new WorkflowOperationException("No mediapackage element was found for publishing");
I tested at least these and they indeed work and fail the workflow. 👌

2023-10-27 09:11 UTC, KatrinIhler commented on modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishYouTubeWorkflowOperationHandler.java
> +        throw new WorkflowOperationException("No mediapackage element was found for publishing");
Should this really fail? I think "Skipped" was the right result in this case. We mark other operations as skipped when the selector doesn't match any elements as well.

2023-10-27 09:11 UTC, KatrinIhler requested changes
I don't agree with one of the cases (see ~~below~~ above), the rest looks fine.

2023-10-27 09:35 UTC, Arnei commented on modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishYouTubeWorkflowOperationHandler.java
> +        throw new WorkflowOperationException("No mediapackage element was found for publishing");
Fair enough, might've been a little to eager there.

2023-10-27 09:59 UTC, KatrinIhler commented on modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishYouTubeWorkflowOperationHandler.java
> +        throw new WorkflowOperationException("No mediapackage element was found for publishing");
Actually I just realized that it returns Action.CONTINUE there. I think it should be Action.SKIP to make it obvious nothing happened. Could you do that? :sweat_smile: I can't make a suggestion on unchanged code unfortunately.

2023-10-27 10:06 UTC, Arnei commented on modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishYouTubeWorkflowOperationHandler.java
> +        throw new WorkflowOperationException("No mediapackage element was found for publishing");
Can do that. Not the scope of this PR, but should it be SKIP in other WOHs too then? Like https://github.com/opencast/opencast/blob/cfc7bf1b6d7b713d71e107041844338075c0b38a/modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java#L379

2023-10-27 10:17 UTC, KatrinIhler commented on modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishYouTubeWorkflowOperationHandler.java
> +        throw new WorkflowOperationException("No mediapackage element was found for publishing");
In my opinion yes. I already did this for the tagging operation a while ago, see #5108. But unfortunately this is wildly inconsistent right now.

2023-10-27 10:25 UTC, KatrinIhler approved these changes
Great!

2023-10-27 10:25 UTC, merged