MH-13205 Document, fix and improve thumbnail support
opencast/opencast pull request #536
Opened 2018-10-31 16:54 UTC by staubesv

Oh man... Actually, I wanted to implement [MH-13201
Convert uploaded images to appropriate size and format](https://opencast.jira.com/browse/MH-13201), but stumbled over [MH-13204 The uploaded thumbnail needs to be tagged with 'archive'](https://opencast.jira.com/browse/MH-13204).

Finally ended up with this:

This task is about addressing a number of related issues considering Opencast 6.x new thumbnail feature:

### Archive tag for the uploaded thumbnail (bugfix)
When a user uploads a thumbnail image, it needs to be made persistent. The current implementation missed to add the tag 'archive' to the attachment added to the media package. Without that tag, the Opencast default workflows will not include the uploaded thumbnail in snapshots they create.
As it would be somewhat nasty to hard-code this, I've added the configuration property thumbnail.uploaded.tags.

**Untangle the flavor of the source track from the flavor of the uploaded thumbnail (enhancement)**
The flavor of the attachment created for the uploaded thumbnail was determine by thumbnail.source.flavor.type and thumbnail.source.flavor.subtype. This mixes up the identification of the source track with the flavor of the uploaded thumbnail which is confusing and limiting.
I've introduced thumbnail.uploaded.flavor to make break up the undesirable entanglement. The configuration property thumbnail.source.flavor.type could then be removed as not used otherwise.

**Document the thumbnail configuration (documentation)**
As there are quite a number of configuration properties related to configure the thumbnail feature, I've felt like there should be some documentation about this.
I've refactored the existing documentation related to the Admin UI in the Admin Guide and added a page describing how the configuration properties for the thumbnail feature work.

**Don't hard-code encoding profiles (enhancement)**
During all the work, I've found that the encoding profile used to downscale the thumbnail preview image is hardcoded which is undesirable and weird to document. I therefore introduce the new configuration property thumbnail.preview.profile.downscale.

**Renamed some configuration properties (maintenance)**
I've renamed thumbnail.default.track.primary and thumbnail.default.track.secondary to thumbnail.source.flavor.type.primary and thumbnail.source.flavor.type.secondary for two reasons: Those configuration keys are used together with thumbnail.source.flavor.subtype to create the source flavors. Also, those configuration properties are currently not only used for the default thumbnail (even though this is not necessarily a great things...).

What a day... ;-)

2018-11-01 18:26 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/languages.md
> +Language Configuration
Moved from configuration/ui.md

2018-11-01 18:26 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +Overview
This page is new

2018-11-01 18:26 UTC, staubesv commented on docs/guides/admin/docs/configuration/metadata.md
> +## Configuring the events publisher metadata field
Moved from configuration/ui.md (the metadata configuration has more impact than just admin ui)

2018-11-01 18:28 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/event-filters.md
> +Events Filters Configuration
Reduced configuration/ui.md to "Event Filters Configuration" page configuration/admin-ui/event-filters.md. All other content has been moved to other places.

2018-11-01 18:28 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/event-filters.md
> -Available Language Configuration
Moved to new page configuration/admin-ui/languages.md

2018-11-01 18:29 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/event-filters.md
> -Configuring the events publisher metadata field
Moved to existing page configuration/metadata.md

2018-11-01 18:30 UTC, staubesv commented on docs/guides/admin/docs/configuration/workflow.md
> -At any given point of time, there is exactly one thumbnail available for each published event.
Avoid too duplication -> refers to configuration/admin-ui/thumbnails.md

2018-11-05 19:27 UTC, gregorydlogan requested changes

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/event-filters.md
> +Events Filters Configuration
Loading this page generates a 404, which is probably caused by a bad filename:
```
...
[I 181105 10:52:06 handlers:79] Ignore: /home/greg/opencast/upstream/docs/guides/admin/docs/configuration/admin-ui/images/assetUploadExistingEvent.png
...
[I 181105 10:52:23 handlers:132] Browser Connected: http://localhost:8000/configuration/admin-ui/event-filters/
[W 181105 10:52:37 web:2064] 404 GET /configuration/admin-ui/assetUploadSource.png (127.0.0.1) 6.85ms
...
```

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +The relative position within the cutted video where the default thumbnail is extracted can be configured:
`Within the cutted video` -> `within the final, edited video`

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +uncutted video where the default thumbnail should be extracted.
edited video

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +at an arbitrary position withhin the uncutted version of the video.
`withhin` -> `within`, `uncutted` -> `unedited`

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +**IMPORTANT:** Please ensure that all workflows in your setup will always included this attachment in their snapshots.
An example of how to do this should be added IMO.  Which flavour(s) and/or tags need to be added, and to which operation(s), assuming we're using the default workflow.

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +Opencast will set the following processing settings for the event being edited: `thumbnailType` is set to `0`
This reads like it should be a point form list, but does not render as such.  IMO a point form list makes sense here.  This comment applies to all four thumbnail types.

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +Currenlty, this is supported for External API publication channels (created by WOH publish-configure) and OAI-PMH
Currently

2018-11-05 19:27 UTC, gregorydlogan commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +Overview
This file doesn't mention which configuration file(s) we're documenting.

2018-11-06 12:28 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +Overview
Added.

2018-11-06 12:28 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/event-filters.md
> +Events Filters Configuration
Fixed.

2018-11-06 12:28 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +The relative position within the cutted video where the default thumbnail is extracted can be configured:
Changed to "edited video". Not that this is not necessarily the "final" video. For example, the final video might include an intro video.

2018-11-06 12:29 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +uncutted video where the default thumbnail should be extracted.
Just omitted "uncutted". So "edited video" vs "video" now.

2018-11-06 12:30 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +at an arbitrary position withhin the uncutted version of the video.
Fixed "within", removed "uncutted"

2018-11-06 12:30 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +Opencast will set the following processing settings for the event being edited: `thumbnailType` is set to `0`
Agree, changed to point form list for all thumbnail types.

2018-11-06 12:30 UTC, staubesv commented on docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
> +Currenlty, this is supported for External API publication channels (created by WOH publish-configure) and OAI-PMH
Fixed.

2018-11-06 13:03 UTC, staubesv commented
That is a fun:

![screen shot 2018-11-06 at 14 02 00](https://user-images.githubusercontent.com/1590263/48066032-b8837100-e1cc-11e8-8882-a2f2031bc2b8.png)

So one warning tells me to not indent the lists and the other says that four spaces are expected ;-)

Went for four spaces, let's see what Travis thinks about that.

2018-11-06 20:23 UTC, merged