Add calendar link, and sysadmin meeting to docs.opencast.org
opencast/opencast pull request #5369
Opened 2023-10-27 21:56 UTC by gregorydlogan

This PR:
- Adds the community calendar as a link in the root of docs.opencast.org
- Massages the meeting section to make is easier (IMO) to read
- Adds the Sysadmin meeting to the list of meetings

### Your pull request should…

* [X] have a concise title
* ~[ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* ~[ ] include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-10-28 12:29 UTC, ziegenberg requested changes

2023-10-28 12:29 UTC, ziegenberg commented on docs/guides/.infrastructure/index.html.j2
> +          Meetings are usually.</p>
That's a premature closing `</p>` tag.

```suggestion
          Meetings are usually
```

2023-10-29 20:30 UTC, gregorydlogan commented on docs/guides/.infrastructure/index.html.j2
> +          Meetings are usually.</p>
Good catch, Ty!

2023-10-30 17:17 UTC, ziegenberg approved these changes
Looks good to me.

2023-10-31 16:05 UTC, gregorydlogan commented
Calendar URL link does not function as expected -> Draft until I get this fixed.

2023-11-01 14:40 UTC, KatrinIhler commented
A couple of things:

1. We don't currently plan to record the SysAdmin meetings.
2. We should either mention the time for both meetings or none of them. (I'd actually prefer it if we just described the goal of the meetings and made people look at the calendar for day and time, because we have to keep less places up-to-date, but I don't have a hard opinion on this.)
3. We wanted to rename the Technical meeting to Dev meeting or something to avoid confusion, maybe we should take the chance and change that as well?

2023-11-02 04:11 UTC, gregorydlogan commented
This should be ready to go now.

2023-11-09 20:05 UTC, merged