Paella 7: Hide/Show timeline bar on live events
opencast/opencast pull request #5420
Opened 2023-11-09 08:29 UTC by miesgre

Paella player used to start playing live streams from the beginning of the buffer, so in case the stream had a time buffer, paella started playing from the beginning of the buffer and not from the current moment.

This PR updates paella to version 1.46.1 that fixes that bug and also adds a property to the configuration file that allows to show or hide the time bar in live events.

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2023-11-29 09:25 UTC, KatrinIhler requested changes, later dismissed
I'm gonna roll this out on our testing system in the next few days, but here are my first thoughts:

- As far as I can tell this doesn't actually update the player version (maybe because that already happened), just adds a new config option, right?

- I think we want to aim this at least at OC 15 (which isn't out yet, but will be soon), maybe even OC 14, since this is basically a fix for people who have live streams where you can go back in time.

- But in that case (and maybe in general), we shouldn't change the default behavior (which was hiding the timeline for live events if I understood correctly), just allow people to change it if they want to. So set the new config to true and in case the config key is missing, retain the previous behavior (this is probably easier if we flip the config from ` hide...` to ` show...` because then the default is `false`).

Sorry for the long wait!

2023-11-29 20:23 UTC, miesgre commented
> I'm gonna roll this out on our testing system in the next few days, but here are my first thoughts:
> 
> * As far as I can tell this doesn't actually update the player version (maybe because that already happened), just adds a new config option, right?

paella-core needs tu be updated to 1.46.1, but `dependabot` updated it in commit https://github.com/opencast/opencast/commit/d48978491b1b0d2973fa5baedeb6bab46c5a16fa

> * I think we want to aim this at least at OC 15 (which isn't out yet, but will be soon), maybe even OC 14, since this is basically a fix for people who have live streams where you can go back in time.

Should I rebase to r/15.x? r/14.x?

2023-11-30 10:40 UTC, KatrinIhler commented
Let's aim this at r/15.x for now. If somebody complains, we can still backport this later.

2023-12-07 16:28 UTC, mliradelc approved these changes
I agree with the changes

2023-12-07 16:30 UTC, mliradelc commented
Agree with @KatrinIhler to be in `r/15.x` if someone needs for `r/14.x` they can back port this PR.

2023-12-11 14:50 UTC, merged

2024-01-09 17:40 UTC, KatrinIhler commented on modules/engage-paella-player-7/src/js/EpisodeConversor.js
> +  const isLive = episode?.mediapackage?.media?.track?.some((track) => track.live === true);
This breaks if there's only one track with "x.some is not a function" u_u

2024-01-10 13:34 UTC, KatrinIhler commented on modules/engage-paella-player-7/src/js/EpisodeConversor.js
> +  const isLive = episode?.mediapackage?.media?.track?.some((track) => track.live === true);
Fix is out, see below!