Fix ACL Template Display for Series in old Admin UI
opencast/opencast pull request #5554
Opened 2024-01-24 14:45 UTC by KatrinIhler

PR #5537 fixed the template selection, but accidentally broke the display of already selected templates because `baseAclId` was always set to `undefined`. This fixes that (at least for series, events might be broken in a different way as well).

2024-01-26 08:20 UTC, Arnei requested changes
Changes make sense to me and fix the issue for series. Events/Acls still dont display the template their based on, but afaik they also did not do that beforehand.

My only request is to aim this at r/14.x

2024-01-26 08:44 UTC, KatrinIhler commented
> My only request is to aim this at r/14.x

Done!

2024-01-26 08:56 UTC, Arnei approved these changes

2024-01-31 08:35 UTC, KatrinIhler commented
Approved and discussed -> merging

2024-01-31 08:36 UTC, merged