Add slide text and segments to Tobira harvest API
opencast/opencast pull request #5757
Opened 2024-04-23 14:40 UTC by owi92

See commits. With this PR, the generated slide text is exposed so we can use that in Tobira's search index. I'm not super sure if the filter I built for this could let through false positives or negatives, though in testing this didn't seem to be the case. Please let me know if you think this might be an issue, and/or have any suggestions how this could be solidified.

Furthermore, the slide segments with their respective starting time is passed in order to be used for Paella's slide plugin on the Tobira side.

Related Tobira issues: https://github.com/elan-ev/tobira/issues/368, https://github.com/elan-ev/tobira/issues/1065

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2024-04-23 15:52 UTC, mtneug requested changes

2024-04-23 15:52 UTC, mtneug commented on modules/tobira/src/main/java/org/opencastproject/tobira/impl/Item.java
> +          })
You probably want to only search for element with flavor `mpeg-7/text`.

2024-04-23 22:25 UTC, owi92 commented on modules/tobira/src/main/java/org/opencastproject/tobira/impl/Item.java
> +          })
Oh right, that is much simpler and more accurate. Thank you!

2024-04-25 11:06 UTC, LukasKalbertodt approved these changes
Tested it locally and it works! I only have one note, but that's not too important. I think this can be merged.

2024-04-25 11:06 UTC, LukasKalbertodt commented on modules/tobira/src/main/java/org/opencastproject/tobira/impl/Item.java
> +          .findFirst();
I wonder... what if there are multiple of these elements? You just take the first here. Can anyone say whether in the real world, there might be multiple such elements?

But this isn't a blocker. I also just trust Matthias with the `mpeg-7/text` filter. I don't have enough experience to say whether that filters for less or more than what we want. :shrug:

2024-05-06 19:20 UTC, gregorydlogan commented
This seems to work to me.  Have not checked the Tobira/UI side of things, but the server side stuff shows up just fine.

2024-05-06 19:20 UTC, merged