MH-12816 Make waveform size configurable in WOH
opencast/opencast pull request #579
Opened 2018-11-19 16:12 UTC by staubesv

The size of the waveform image that is produced by the waveform service can currently only be configured globally.
This patch moves the configuration parameters relevant for waveform image size from the waveform service
configuration to the workflow operation configuration so that Opencast can produce different waveform sizes.

2018-11-29 14:54 UTC, KatrinIhler requested changes
Apart from the one thing it's looking good!

2018-11-29 14:54 UTC, KatrinIhler commented on modules/waveform-ffmpeg/src/main/java/org/opencastproject/waveform/ffmpeg/WaveformServiceImpl.java
> +   * @param height height of waveform image
Documented parameters don't match the actual parameters below.

2018-11-30 11:45 UTC, staubesv commented on modules/waveform-ffmpeg/src/main/java/org/opencastproject/waveform/ffmpeg/WaveformServiceImpl.java
> +   * @param height height of waveform image
Fixed.

2018-11-30 14:44 UTC, KatrinIhler approved these changes

2018-11-30 14:45 UTC, merged