Add audio check before subtitle generation
opencast/opencast pull request #5842
Opened 2024-05-14 10:02 UTC by marwyg

Fixes #5818

This PR introduces a straightforward audio check in the subtitle generation method. Previously, the whisper process would throw an exception and halt the workflow if no audio was present. With this update, tracks lacking audio will be simply skipped during subtitle generation, preventing workflow interruptions.

2024-05-15 15:35 UTC, KatrinIhler commented
This is not a blocker, but I think it'd be nice if the operation was marked as Skipped if no track contained audio, ergo no transcription took place. Stuff like this makes workflow debugging easier. But this would require for the checking to happen before calling createSubtitles(), and keeping track of if we do that for at least one track.

More thoughts: In most cases if more than one track has audio, that audio is probably identical for every track. Running transcription more than once is probably overkill and can cost precious time. I would love to see a configuration `transcribe-first-only` or something, for only transcribing the first track with audio that is found.

2024-05-16 15:28 UTC, marwyg commented
@KatrinIhler These are nice ideas. It's not done yet, but I added some more functionality. With this, you can define a "track selection strategy". Like "Only Presenter" or "Try Presenter First" and similar.

2024-05-17 09:21 UTC, marwyg commented
I added 2 workflow configurations.
With `limit-to-one` you can set if max one transcription shall be generated.
With `track-selection-strategy` you can control which tracks shall be used for the transcription.

2024-06-10 17:05 UTC, gregorydlogan requested changes
Very minor nits.  Also will conflict with #5879, which will be merged in a couple of minutes.

2024-06-10 17:05 UTC, gregorydlogan commented on modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
> +            "Speech-to-Text job for media package '%s' failed, because of wrong workflow xml configuration. "
Workflow may be yaml ;)

2024-06-10 17:05 UTC, gregorydlogan commented on docs/guides/admin/docs/workflowoperationhandlers/speechtotext-woh.md
> +| track-selection-strategy | no       | try_presenter_first | Use this in combination with `limit-to-one`. Define your strategy what tracks shall be selected for subtitle generation. If you use the `
Defaults should match documentation.

```suggestion
| track-selection-strategy | no       | everything | Use this in combination with `limit-to-one`. Define your strategy what tracks shall be selected for subtitle generation. If you use the `source-flavor` `*/source`, because your are unsure which track of your dual stream includes the audio, you can use the `track-selection-strategy` to try transcribing the presenter track first with the option`try_presenter_first` for example. These are the possible strategy options: `presenter_or_nothing`: only uses presenter tracks. `presentation_or_nothing`: only uses presentation tracks. `try_presenter_first`: looks for presenter tracks first, if there are no usable, try to transcribe the other tracks. `try_presentation_first`: looks for presentation tracks first, if there are no usable, try to transcribe the other tracks. `everything`: just transcribe everything (this is the default). |
```

2024-06-10 17:05 UTC, gregorydlogan commented on modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
> +    String limitToOneConfig = StringUtils.trimToEmpty(operation.getConfiguration(LIMIT_TO_ONE)).toLowerCase();
I would strongly urge the use of `BooleanUtils.toBoolean` here.  You still need to trim the string, but then you don't need to worry about user input being `True` vs `true`.

2024-06-13 12:32 UTC, marwyg commented
Thank you for the review, I changed all the things you mentioned. 
Because of the conflict, I rebased my branch and force pushed it.

2024-06-20 21:01 UTC, merged