F/mh-12649 clone workflow operation handler
opencast/opencast pull request #59
Opened 2018-01-24 12:59 UTC by sebastian-weiser

Clone-WorkflowOperationHandler

2018-01-24 13:34 UTC, lkiesow commented on docs/guides/admin/docs/workflowoperationhandlers/clone-woh.md
> +	<operation
Please refrain from using tabs in Opencast whenever possible

2018-01-24 13:42 UTC, lkiesow commented
@sebastian-weiser, can you please add a unit test for this operation? Tip: You can create a test coverage report for a specific module if you run `mvn cobertura:cobertura` in that modules folder. The generated report can then be found at `target/site/cobertura/index.html`.

2018-02-09 12:43 UTC, sebastian-weiser commented
Tests have been added

2018-02-22 14:06 UTC, staubesv requested changes
I've done a first round of code review ("code skim over", no tests yet).

Besides some minor comments, I've found to issues:

1. target-flavor, targetFlavor, ...

An Opencast flavor has a type and a subtype, e.g. type=presenter and subtype=source would be usually read as presenter/source.

Your code somewhat suggests (configuration key name, variable names) that you are working on target flavors where you actually mean the subtype of the target flavor.
Please adjust the names of the configuration key and the variables to make this more clear.

2. Highly specific WOH

It would be desirable to have the WOH a little less specific, e.g. if someone would want - for whatever reason - to create a clone with a different flavor, this WOH could not do it.
A possible solution code be to allow "?" for target-flavor, e.g. target-flavor = ?/source, presenter/?, ?/? whereas the ? would be replaced by the corresponding type or subtype of the source flavor of the respective media package element.
I once did something like that for WOH prepare-av, although it is not exactly "standard".
I'm not expecting you to implement this, consider it a suggestion.

2018-02-22 14:06 UTC, staubesv commented on docs/guides/admin/docs/workflowoperationhandlers/clone-woh.md
> +The CopyWorkflowOperationHandler can be used to clone media package elements from one flavor to another.
Is it now "CloneWorkflowOperationHandler" or "CopyWorkflowOperationHandler"? Please decide...

Also, "[...] from one flavor to another" seems incorrect, as the target-flavor could be equal to the source-flavor. Maybe just say: "[...] can be used to clone media package elements".

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +      return createResult(mediaPackage, Action.CONTINUE);
According to the documentation, you claim that the WOH would be skipped in this case...

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +    if (sourceFlavorOption == null) {
Are you sure that you want to do this? 

Please either a) adjust the documentation to indicate that source-flavor will default to \*/\* in case omitted or b) make source-flavors a mandatory option (and also adjust the documentation).

Personally, I would be in favor of b) as the admin can explicitly set source-flavors to \*/\*. But as this might be a matter of taste, I leave the choice up to you. But please do ensure the documentation is adjusted to whatever option you choose ;-)

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +      logger.debug("No matching elements found, skipping action.");
Maybe change to "[...] skipping **operation**."

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +      // Store the new Flavor for the loop, so that there are noe duplicates
[...] new **f**lavor [...] no duplicates

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +        // Get the element's flavor if neccessary (there should always be one I guess?)
There is, please remove "(there should always be one I guess?)"

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +      throw new WorkflowOperationException(format("Unable to copy %s: %s", sourceFile.getPath()));
More placeholders (%s) than variables? Is the use of the method format necessary?

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/test/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandlerTest.java
> +  public void testTagsAsSourceFlavor() throws Exception {
A tag is not a flavor, so the method name is somewhat inconsistent ;-)

2018-02-22 14:06 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +        // Create new Flavor or get existing previously created one
Hmm... Is it a substantial benefit to cache the newly generated flavors here? I suggest to just create the new flavor for each media package from scratch as it makes the code easier to understand...

2018-02-26 14:05 UTC, sebastian-weiser commented
Thank you for your remarks @staubesv , I changed the corresponding locations.
The target-flavors can now be given with type and subtype (though I chose the more common * instead of the ?).

2018-02-27 11:30 UTC, staubesv requested changes
I've found two issues left (see individual comments):

- Weird behavior with default value of source-flavors
- Redundant check introduces with latest updates of this PR

2018-02-27 11:30 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +    // if no source-favor is specified, all flavors will be checked for given tags
This is still not documented.

Note that I've just found a reason that strongly suggests to remove this default option:

In the following example...

```
      <operation
                id="clone"
                fail-on-error="true"
                exception-handler-workflow="ng-partial-error">
                <configurations>
                        <configuration key="source-tags">archive</configuration>
                        <configuration key="target-flavor">*/target</configuration>
                </configurations>
        </operation>
```

... source-flavor would default to \*/\* which results in just all media package elements being selected. I don't think that a user would expect this behavior.

2018-02-27 11:30 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +    else if (!targetFlavorOption.contains("/") || targetFlavorOption.split("/").length != 2)
This check is redundant as MediaPackageElementFlavor.parseFlavor would throw an IllegalArugmentException  in

`  MediaPackageElementFlavor targetFlavor = MediaPackageElementFlavor.parseFlavor(targetFlavorOption);`

See

```
  public static MediaPackageElementFlavor parseFlavor(String s) throws IllegalArgumentException {
    if (s == null)
      throw new IllegalArgumentException("Unable to create element flavor from 'null'");
    String[] parts = s.split(SEPARATOR);
    if (parts.length != 2)
      throw new IllegalArgumentException(format("Unable to create element flavor from \"%s\"", s));
    return new MediaPackageElementFlavor(parts[0], parts[1]);
  }
```

Please remove.

2018-02-28 12:12 UTC, sebastian-weiser commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +    // if no source-favor is specified, all flavors will be checked for given tags
This should already cause the selector to select only media-packages-elements that match the flavor AND the tags:

```java
// Select the source flavors
MediaPackageElementFlavor sourceFlavor = MediaPackageElementFlavor.parseFlavor(sourceFlavorOption);
elementSelector.addFlavor(sourceFlavor);

// Select the source tags
for (String tag : asList(sourceTagsOption)) {
  elementSelector.addTag(tag);
}

// Look for elements matching the tags and the flavor
Collection<MediaPackageElement> elements = elementSelector.select(mediaPackage, true);
```

Therefore specifying only tags should lead to a selection over all elements with these tags, I would say this is the expected behavior

2018-02-28 12:15 UTC, sebastian-weiser commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +    // if no source-favor is specified, all flavors will be checked for given tags
(Added this information to the documentation though)

2018-02-28 12:43 UTC, staubesv commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +    // if no source-favor is specified, all flavors will be checked for given tags
Oh, sorry: Haven't looked at the selector deep enough... thanks for adding a info to the documentation.

2018-03-01 20:27 UTC, staubesv commented
@sebastian-weiser Thanks for implementing all comments. I've started to test this PR, but the WOH failed:

> Exception message WorkflowOperationException: java.lang.IllegalArgumentException: http://localhost:8080/assets/assets/cacd8eb7-2b43-420b-8699-588fc5d46a5d/90ae22e8-dc50-4d44-a93b-0b468df723f4/3/sintel_trailer_480p.mp4 must point to a working file repository collection

I've used the current state of opencast/develop, ran the "fast" workflow and used source-flavor=\*/\*. It is true that those media package elements are lying in the archive (aka asset manager).

While adding a WOH ingest-download would likely help, the WOH should (at least I think so) also work without.

Can you reproduce this?

2018-03-08 17:38 UTC, lkiesow requested changes

2018-03-08 17:38 UTC, lkiesow commented on modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CloneWorkflowOperationHandler.java
> +        toFileName = "." + extension;
`+=` or you would create a filename consisting only of the extension

2018-03-08 20:46 UTC, merged

2018-03-09 07:57 UTC, staubesv commented
Hi @lkiesow, this WOH did not work when I tested it. Since you have merged it: Did it work for you?

2018-03-09 08:51 UTC, lkiesow commented
Arrgh, sorry! This time, I merged this by accident.

How shall we continue?
Since it doesn't break anything, I can just ask @sebastian-weiser, to continue working on this.
Or do you prefer me to revert my merge?

2018-03-09 08:54 UTC, staubesv commented
@lkiesow No big deal, assuming that @sebastian-weiser will provide a follow-up pull request before the feature freeze of Opencast 5.0 on April 3th.

@sebastian-weiser When I've tested this locally, the WOH failed (see comment) above. Can you please have a look at this and provide a follow-up pull request? Note that @lkiesow also found a bug (see comment about file extenstion).