Add more admin-UI Tobira endpoints
opencast/opencast pull request #6091
Opened 2024-08-12 12:26 UTC by owi92

This adds
 - a) an endpoint to get paths of pages in Tobira that host an event
 - b) an endpoint to update the path of a series in Tobira

This shouldn't break any existing behaviour.

These are needed for additional requirements of https://github.com/opencast/opencast-admin-interface/issues/311.
I will link the corresponding Tobira and admin-UI PRs here once I have opened them, as they are necessary to test this.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

2024-08-13 12:16 UTC, owi92 commented
Converted to draft bc we might still need to change some things on the Tobira side, which will then trickle down to this and the admin-UI PR.

2024-10-29 09:25 UTC, Arnei requested changes, later dismissed

2024-10-29 09:25 UTC, Arnei commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
> +      return Response.status(Status.SERVICE_UNAVAILABLE)
When testing I am always running into this response. It seems that `TobiraService.getTobira([...])` creates a new `TobiraService`, but all the fields in the service are `null`. Not sure how this is supposed to work, if there's something I forgot to configure please tell me.

2024-10-29 09:47 UTC, KatrinIhler commented
FYI: Branch cut for OC 17 is on November 6!

2024-10-29 09:59 UTC, Arnei commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
> +      return Response.status(Status.SERVICE_UNAVAILABLE)
Nvm, the issue was missing configuration (which should be better documented in the Tobira docs, so nothing to change here)

2024-10-29 10:06 UTC, Arnei submitted a review, later dismissed

2024-10-29 10:06 UTC, Arnei commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
> +  @Path("{eventId}/tobira/pages")
The endpoint returned "{eventId}/tobira/pages"

```

{
  "baseURL": "http://localhost:3080",
  "hostPages": [
    {
      "path": "/",
      "title": null,
      "ancestors": []
    }
  ]
}
```

The video has a title, so I would expect the title field to not be `null`.

2024-10-29 11:28 UTC, Arnei approved these changes
After receiving instructions on how to properly test this with Tobira, I can confirm that the endpoints added by this PR do what they are supposed to do.

Code looks reasonable too, from what I understand of it.

2024-10-29 12:12 UTC, KatrinIhler commented
Well, in that case... :magic_wand:

2024-10-29 12:12 UTC, merged