Add user info to roles for admin ui
opencast/opencast pull request #6382
Opened 2024-12-11 14:16 UTC by Arnei

Adds user information for user roles to admin ui GET endpoints. The frontend wants to render user roles like ROLE_USER_ARNE with user information like username and email, so instead of having to do perform multiple GET requests and then mix-and-matching roles and users in the frontend, it seemed prudent to change the backend instead.

To that end, ACLs are not sent as is anymore, but transformed into the format used by the frontend so that user information can be more easily attached.

**Requires frontend changes, otherwise this PR will break the frontend: https://github.com/opencast/opencast-admin-interface/pull/1006**

### How to test this patch

Check the frontend PR for more information on how to test this patch.

2025-01-14 17:22 UTC, gregorydlogan commented
This works correctly, however it needs to be held until the next admin ui release, and should be merged concurrently with the (future) PR where that release is brought into 17.x!

2025-03-18 16:28 UTC, marwyg requested changes
I looked through the code and have some questions and suggestions. There is one case I would also like to test, but not today anymore.

2025-03-18 16:28 UTC, marwyg commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
> +//    episodeAccessJson.put("acl", AccessControlParser.toJsonSilent(activeAcl));
Should this comment stay like this?

2025-03-18 16:28 UTC, marwyg commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/EndpointUtil.java
> +    }
You could remove the "protected". Its easier to read (and doesn't make any difference I think)

2025-03-18 16:28 UTC, marwyg commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
> +//      seriesAccessJson.put("acl", AccessControlParser.toJsonSilent(seriesAccessControl));
Should this also stay in?

2025-03-18 16:28 UTC, marwyg commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
> +  }
Could this be a security issue? Because I see no security check, but there is a check in "loadUser()" I think. I will test this. Other endpoints in this class are also checking the input and returning a "bad request" in case the input is empty for example.

2025-03-18 16:28 UTC, marwyg commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
> +  public Map<String, Object> generateJsonUser(User user) {
Is there a reason changing this to public? I didn't find a usage outside this class.

2025-03-19 13:40 UTC, marwyg commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
> +  }
Okay never mind, I did take a second look at this and especially at the other endpoints in this class.

2025-03-25 08:03 UTC, Arnei commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/EndpointUtil.java
> +    }
Checkstyle requires us to specify access level modifiers.

2025-03-25 08:06 UTC, Arnei commented on modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
> +  public Map<String, Object> generateJsonUser(User user) {
The original idea was to use this function in the event and series endpoints as well, as they now send user data. That did not end up working out. Changed it per your suggestion.

2025-04-01 11:28 UTC, snoesberger commented
I did test the functionality of this PR together with the admin UI changes (https://github.com/opencast/opencast-admin-interface/pull/1006) successfully. The changes worked as expected in the new admin UI.
But first I had to do a rebase to r/17.x (locally on my side), some of the files, like `modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java`, are outdated.

2025-05-05 11:49 UTC, marwyg approved these changes
I took a second look. My points were addressed and things were changed where possible. It can be merged.

2025-05-16 20:29 UTC, merged