MH-12684 Make License List Provider More Flexible
opencast/opencast pull request #69
Opened 2018-01-26 14:57 UTC by krinnewitz

This patch adds a new metadata type 'ordered_text' which allows for
listproviders to configure the order, as well as a "selectable" value
for each entry. This can be used to display e.g. licenses in a
meaningful order as well hiding entries if desired. "Hiding" doesn't
actually mean hiding in this case. If "selectable" is false for an
entry, the entry is hidden as long as it isn't already selected as the
current value.

For licenses, there is the following use case: Previously, Creative
Commons 3.0 was selected by users to publish their recordings. Now,
there is Creative Commons 4.0 added to the list and the list of licenses
grows longer and longer. While it is not feasible to change the license
for old events, for new events only Creative Commons 4.0 should show up
in the list. So we cannot remove Creative Commons 3.0, but can hide it
for new events as well as for old events, which were published under a
different license. This is now possible by setting "selectable" to false
for old licenses.

This work is sponsored by SWITCH.

2018-03-08 07:29 UTC, KatrinIhler commented
I'm gonna review this - though the merging will have to be done by someone with the required rights. :)

2018-03-08 12:51 UTC, KatrinIhler requested changes
This works as advertised and I can see why someone would want to have the possibility of custom ordering for listprovider options. It's consistent with other recent changes (see PR #24) and might make sense for other listproviders in the future as well (for example languages) to move most used options to the top instead of them being buried deep down.

A few things to consider concerning the selectable option:

* If you change from a now deprecated license to another license and close the event window, you cannot change it back since the deprecated license will no longer be selectable for this event (and we can't yet revert to older snapshots).

* This will not be backwards compatible with older licenses-config-files.

* This keeps deprecated licenses from being set in the UI for new events, they can however be set via rest e.g. by using /ingest.

It might be more reasonable to instead remove deprecated options from the listprovider config altogether, but allow them to remain part of an older event's metadata if they were set before (right now they disappear from view in the UI, but remain part of the dublin core, so behavior is inconsistent). This would keep deprecated options from building up in the listprovider config files only because some old events from years ago still need them.

Thoughts?

2018-03-08 12:51 UTC, KatrinIhler commented on modules/admin-ui/src/main/webapp/scripts/shared/partials/editableSingleSelect.html
>      </div>
Right now, whenever we add another option (like 'translatable' or 'ordered' here) this means that the amount of alternative selects in this file is multiplied by two. Maybe it would be a better idea to:
1. sort options alphabetically in the directive if no explicit order is given and remove orderBy here completely, thus removing the need to check 'ordered' here
2. maybe even translate in the directive instead of in the html, thus removing the other check? Not sure if that's a good idea though.

2018-03-08 12:51 UTC, KatrinIhler commented on etc/listproviders/licenses.properties
> +CC0={"label":"EVENTS.LICENSE.CC0", "order":8, "selectable": true}
I think the meaning of the 'selectable' property might be easier to understand if it was renamed to something like "deprecated", since this conveys that it should no longer be used, but will be tolerated if it was selected before the change.

2018-03-08 12:57 UTC, staubesv commented on etc/listproviders/licenses.properties
> +CC0={"label":"EVENTS.LICENSE.CC0", "order":8, "selectable": true}
Hmm... 'selectable' seems to better indicate the purpose in my opinion as setting it to true very much means that the item is selectable. 

Not sure whether deprecated is more understandable or correct: While we plan to not offer certain licences in the Admin UI for selection, we don't officially deprecated them. Indeed, if the learning management systems still want to use the older licenses, that is fine for us. So strictly, we do not deprecate those licenses, but rather make them unavailable in the Admin UI for selection.

2018-03-08 13:09 UTC, KatrinIhler commented on etc/listproviders/licenses.properties
> +CC0={"label":"EVENTS.LICENSE.CC0", "order":8, "selectable": true}
@staubesv Ah, okay, then I misunderstood the purpose. Then 'selectable' is indeed what you want.

2018-03-08 13:12 UTC, staubesv commented on etc/listproviders/licenses.properties
> +CC0={"label":"EVENTS.LICENSE.CC0", "order":8, "selectable": true}
> If you change from a now deprecated license to another license and close the event window,  you cannot change it back since the deprecated license will no longer be selectable for this  event (and we can't yet revert to older snapshots).

We ensured that if an user opens the license selection, the currently selected licence will be shown as an option. It is true that once another license is set, the user cannot switch back.
But at the end of the day, the user has selected the new license - accidentally or not. Having the Admin UI supporting the versioning of the backend would (in my opinion) be the remedy for that, but that is way out of scope.

> This will not be backwards compatible with older licenses-config-files.

I don't understand... could you please elaborate?

>This keeps deprecated licenses from being set in the UI for new events, they can however be set via rest e.g. by using /ingest.

This is a usability improvements for the Admin UI. Its goal is not to deprecate licenses but to improve the usability in the Admin UI assuming that a user has no motivation to select an older version of the same license.

> It might be more reasonable to instead remove deprecated options from the listprovider config altogether, but allow them to remain part of an older event's metadata if they were set before (right now they disappear from view in the UI, but remain part of the dublin core, so behavior is inconsistent). This would keep deprecated options from building up in the listprovider config files only because some old events from years ago still need them.

The reason why we need to keep the old licenses in the list provider is that we store technical identifiers in the dublincore (by intention). 
Example: 
Displayable value: Creative Commons 2.5 Attribution Switzerland
Technical value: http://creativecommons.org/licenses/by/2.5/ch/

2018-03-08 13:20 UTC, staubesv commented
... to summarize, my overall comments are:

- The goal of this PR is not the deprecation of licenses but rather an usability improvement in the Admin UI based on the assumption that users have no particular reason to select an old version of an license
- We do need the old versions in the list provider since they are a) in the archive and b) still supported (in our case, we don't have direct control whether a learning management system user still can select old versions as those systems are not under our direct control)

What do you think?

2018-03-08 13:36 UTC, KatrinIhler commented
@staubesv I think I understand the purpose of this pullrequest much better now. In that case, I don't have much to complain about except for the growing of editableSingleSelect.html.

2018-03-08 21:45 UTC, krinnewitz commented
Thanks for your review. I changed the editableSingleSelect to have the filters "orderBy" and "translate" applied conditionally from within the directive.

2018-03-09 06:52 UTC, KatrinIhler approved these changes
Looking good now!

2018-03-09 08:15 UTC, merged