MH-13221 Improve behaviour of single-select metadata fields
opencast/opencast pull request #732
Opened 2019-02-20 17:02 UTC by KatrinIhler

Updated version of #603.

2019-02-21 10:23 UTC, staubesv requested changes
Looks promising, but introduces a bug: Try to left-click a single select drop down. Result: The dropdown is opened but just closes again.

Can you please fix this?

2019-02-21 12:22 UTC, KatrinIhler commented
@staubesv Argh, this PR will haunt me forever...gonna look into this.

2019-02-22 13:58 UTC, KatrinIhler commented
@staubesv Alright, next try!

2019-02-26 09:18 UTC, staubesv approved these changes

2019-02-26 09:18 UTC, merged