F/mh 13451 improve delete event button
opencast/opencast pull request #791
Opened 2019-03-21 14:50 UTC by KatrinIhler

2019-03-21 14:58 UTC, KatrinIhler commented
@staubesv Just noticed that this doesn't quite work as intended yet, give me a few more minutes! ;)

2019-03-21 15:09 UTC, KatrinIhler commented
@staubesv Ready for review!

2019-03-25 09:06 UTC, staubesv requested changes
The behaviour is not really consistent:

Case 1:
User selects one or more events without publications.
Button: "Delete" (red)

Case 2:
User selects one or more events with publications.
Button: "Retract" (green)

Case 3:
User selects one or more events without publications and one or more events with publications.
Button: "Retract" (green)

Case 3 is suggesting that no events are deleted.

What do you think about the handling of case 3?

2019-03-25 09:23 UTC, KatrinIhler commented
@staubesv Good question. I assume in that case some events are deleted and others just retracted? In that case the button should reflect that...

2019-03-25 09:26 UTC, staubesv commented
@KatrinIhler Yes, both the delete and retract operations will be executed.

2019-03-25 09:27 UTC, KatrinIhler commented
@staubesv Alright, I'm gonna try to take a quick look at this today.

2019-03-27 15:35 UTC, KatrinIhler commented
@staubesv How about this? Not quite sure about "Retract/Delete" yet, maybe an "or" would be preferable...opinions?

2019-03-29 08:04 UTC, staubesv commented
@KatrinIhler I suggest "Retract & Delete" as this label is only shown if both retractions and deletions will be performed.

2019-03-29 13:26 UTC, KatrinIhler commented
@staubesv I think that wording is confusing because users could assume that opencast retracts the published events and then deletes all events, which...would make sense, but is not what is happening.

2019-04-01 12:12 UTC, staubesv approved these changes

2019-04-01 12:12 UTC, merged