MH-13459, Make Paella Use UI Configuration Service
opencast/opencast pull request #799
Opened 2019-03-24 19:21 UTC by lkiesow

…this allows us to drop Paella's own configuration service.

2019-03-25 13:44 UTC, miesgre requested changes
@lkiesow You can remove the `Paella player configuration folder` section from `etc/custom.properties` file also.

2019-03-25 13:44 UTC, miesgre commented on docs/guides/admin/docs/releasenotes.md
> +- The default configuration for the Paella player has been moved to `etc/ui-config/mh_default_org/paella/config.json`
Should this be added also to `upgrade.md` file?
Why there is a `Configuration Changes` section in both files?

2019-03-25 15:20 UTC, lkiesow commented on docs/guides/admin/docs/releasenotes.md
> +- The default configuration for the Paella player has been moved to `etc/ui-config/mh_default_org/paella/config.json`
The final docs are composed by the release managers anyway. Let them figure out the merge ;-)
It doesn't make sense to have it in both places.

2019-03-25 15:21 UTC, lkiesow commented
Removed the option from the `custom.properties` and fixed the merge conflicts.

2019-03-26 07:54 UTC, miesgre approved these changes

2019-03-26 08:36 UTC, merged

2019-03-26 08:37 UTC, lkiesow commented
Thanks for the review, @miesgre