WIP: MH-12703: Add userdirectory for Moodle
opencast/opencast pull request #89
Opened 2018-02-12 10:12 UTC by mtneug

This PR adds a Moodle user and role provider analogous to the Sakai user and role provider. To efficiently query the necessary information, the [moodle-tool_opencast](https://github.com/unirz-tu-ilmenau/moodle-tool_opencast) plug-in has to be installed in Moodle. There is still a minor convenience feature that has to be implemented on Moodle site, which effects the documentation included in this PR. This work is therefore WIP, but I figured that at least the code can be reviewed. Function wise this integration should work.

2018-03-06 13:16 UTC, mtneug commented
This is now ready for a review.

2018-03-16 08:21 UTC, mtneug commented
Any change we might find a reviewer until 22.3 😬? Otherwise I won't be able to work on this until the 5.x feature freeze (but no pressure, if it can't be done for 5.x there is 6.x 🙂).

2018-03-16 08:30 UTC, smarquard commented
At a glance, the code looks good to me. It would be ideal to find a reviewer who also uses moodle and can test it in production. But if no-one else volunteers, I'd be prepared to merge it in time for 5.x, as there's no reason it should wait until 6.x and it only really affects people who switch it on, so it's low-risk for everyone else.

2018-03-29 16:39 UTC, wsmirnow requested changes
The code looks good so far and works as expected. Can you please solve the review comments.

2018-03-29 16:39 UTC, wsmirnow commented on docs/guides/admin/docs/configuration/security.user.moodle.md
> +group with the title 'Moodle'. You can then add additional roles to this group,
..with the _name_ 'Moodle'.. (not title)

2018-03-29 16:39 UTC, wsmirnow commented on modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleWebServiceException.java
> +public class MoodleWebServiceException extends Exception {
Can you please add documentation for this exception class.

2018-04-01 10:02 UTC, mtneug commented
I have adapted the PR according to your comments.

2018-04-03 10:39 UTC, mtneug commented
@wsmirnow is this good to go or do I need to work on it some more?

2018-04-03 14:37 UTC, wsmirnow commented
As there are minor requested changes (documentation of an exception) I suggest to merge this PR and create a patch afterwords. So the feature will be available in 5.x.

2018-04-03 15:42 UTC, mtneug commented
@wsmirnow I already added the documentation

2018-04-03 16:40 UTC, wsmirnow commented
I've created an other ticket (see MH-12805) for review fixes. I will provide the requested changes there.

2018-04-03 16:46 UTC, merged